### ISSUE TITLE
HttpRequest.url missing scheme, host, port etc

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#143]
It would be good to have the url properly passed along, rather than just getting the `path` value of it in `url` of `HttpRequest`. This is needed for Hawk authentication.

**Comment by haf** [comment]
This code will have to change:

``` fsharp
    let url s (x : HttpContext) = async { if s = x.request.url then return Some x else return None }
```

**Comment by ademar** [comment]
Shall we make `HttpRequest.url` of type `System.Uri` ?

**Comment by haf** [comment]
Yes, I think so, but I also think this:

``` fsharp
type Host = string

// ...
type Request =
  url : Uri
  host : Host option
// ...
```

So that in consuming code `val host : string -> WebPart` can set the `host` property and we don't have to change the `url` after it's bound after accepting the request/socket from a binding.

It fits with my thought consuming code, too: https://github.com/logibit/logibit.hawk/blob/master/src/logibit.hawk/Server.fs#L94

**Comment by haf** [comment]
Here's the thing though; host is a required field:

```
A client MUST include a Host header field in all HTTP/1.1 request messages . If the requested URI does not include an Internet host name for the service being requested, then the Host header field MUST be given with an empty value. An HTTP/1.1 proxy MUST ensure that any request message it forwards does contain an appropriate Host header field that identifies the service being requested by the proxy. All Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request message which lacks a Host header field. 
```

so this would be more appropriate, given that we may respond on any host name:

```
type Host =
  | ServerClient of string
  | ClientOnly of string
```

**Comment by ademar** [comment]
I did not understood that last bit, which cases represent `ServerClient`and `ClientOnly` ?

**Comment by haf** [comment]
We should have two cases; the first where only the client has cared about the Host header and sent it, like it's required, or in the other case, we have a 'host' applicative that reads the host-header and sets it to the web request. In that case both the client and server have agreed on a host header; otherwise, the server may be responding to any host header and hence the client can spoof any header it wants.

**Comment by haf** [comment]
Or even:

```
type Host =
  | ServerClient of string
  | ClientOnly of string
  | Forwarded of bound:string * client:string
  member x.value =
    match x with
    | ServerClient v -> v
    | ClientOnly v -> v
    | Forwarded (bound, _) -> bound
```
