### ISSUE TITLE
[cookie] shout loudly at the programmer if >4KiB cookie

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#152]
From the [session](https://github.com/SuaveIO/suave/pull/146) PR.

If we're storing in the cookie state store, we might be tempted to save too large items in it; if we do there should be some way of being notified about it.

The code already logs the string length; which is serialised ASCII; add a check in `Cookie.set_cookie` for the large size with a Warn level.

**Comment by danieljsummers** [comment]
I'm giving this one a shot.

**Comment by haf** [comment]
@danieljsummers Excellent; give a shout if you have any questions!

**Comment by danieljsummers** [comment]
@haf How is this for the error message?

COOKIE '%s' TOO LARGE! Value length should not exceed 4096 (%d received); consider alternate storage

(where %s is the name of the cookie, and %d is the actual length of the value field)

**Comment by haf** [comment]
Yes, that's indeed SCREAMING AT THE USER ;) You could also add to the message that this means that the data in the cookie will be corrupted in some browsers.

**Comment by danieljsummers** [comment]
Right - I only put the check on the setCookie method.  I just [submitted the PR](https://github.com/SuaveIO/suave/pull/442).
