### ISSUE TITLE
Suggestion: File restructuring

### ISSUE THREAD

**Issue by varon** [SuaveIO/suave#167]
At the moment there's a relatively tiny number of files with an enormous number of types in them, none of which are in sub-folders. It's really really hard to find your way around the codebase.

This would also give us an opportunity to write more `.fsi` files, as they'll be more manageable single tasks.

I'd like to take the time to refactor the structure of the project to a more clean hierarchy with the following guidelines:

- One file per module
- If a module has nested types, group those in a folder of the same name.
- Major types should be placed into their own file where possible

Folders are supported by the tooling at the project level. To manipulate them in VS, you'll need [Visual FSharp Power Tools](https://fsprojects.github.io/VisualFSharpPowerTools/)

This would probably a significant change, so I'd like some input from @haf and @ademar before undertaking it.

**Comment by haf** [comment]
Are we done :)~?

**Comment by haf** [comment]
Closing until other information is available.
