### ISSUE TITLE
[testing] painful to modify request

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#173]
- lots of 'overloaded' functions which is bad for discoverability
 - hard to know what's been set

Suggestion: rewrite with Http.fs which uses an immutable structure to set everything

**Comment by ademar** [comment]
Henrik, can you ilustrate these issues with concrete examples ?

**Comment by haf** [comment]
Yes, for example, I want to add a custom header to the request; that's currently hard.

I've been looking into Http.fs to solve the problem, but it has some problems of its own.

**Comment by ademar** [comment]
What do you mean hard ?

```fsharp
set_header "X-Doge-Location" "http://www.elregalista.com/46263312.jpg"
```

**Comment by haf** [comment]
I mean when testing; setting the header on the request. =)

**Comment by haf** [comment]
I added a fn `(f_request : HttpRequestMessage -> HttpRequestMessage)` while waiting for something better.

**Comment by haf** [comment]
Released v0.20.2 with that function in.

**Comment by haf** [comment]
Also see https://github.com/relentless/Http.fs/pull/44

**Comment by haf** [comment]
Fixed with f-n to modify request.
