### ISSUE TITLE
[build] Can not load Suave.Testing.fsproj on VS 2012

### ISSUE THREAD

**Issue by ademar** [SuaveIO/suave#175]
Error	2	The imported project "C:\Program Files\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	Z:\workarea\suave\src\Suave.Testing\Suave.Testing.fsproj	50	3	Tests

**Comment by haf** [comment]
We want to make sure F# 3.1's targets are loaded; it seems Suave.Tests.fsproj loads F# 3.0's targets.

**Comment by haf** [comment]
Related to build failure?

```
 Pong -> C:\projects\suave\examples\Pong\bin\Release\Pong.exe
321C:\projects\suave\examples\Load\Load.fsproj : error MSB4057: The target "Build" does not exist in the project.
```

https://ci.appveyor.com/project/AdemarGonzalez/suave/build/1.0.312
