### ISSUE TITLE
[ssl support] Support SNI

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#177]
Currently we bind a SSL cert to a specific IP: we should support SNI to go with the new and nice `host` applicative.

This should be doable through miTLS and through the OpenSSL support we have even though it's not supported in .Net proper, which would make us the only .Net web server to have such support.

[How to do it with OpenSSL](http://stackoverflow.com/a/22375715/63621)

If using this, we should probably automatically apply `Suave.Http.Applicatives.host`.

**Comment by ademar** [comment]
:cake:
