### ISSUE TITLE
[nuget] package suave.dll modified date

### ISSUE THREAD

**Issue by pavelhritonenko** [SuaveIO/suave#190]
I downloaded nuget package version 0.21.1 from https://www.nuget.org/api/v2/package/Suave/0.21.1 and see, that `/lib/net40/suave.dll` has a strange modification date `2102-08-12 12:48`. If I refer to this assembly in my project, MSBuild can not determine that project is up-to-date because freshest input was modified on `2102-08-12 12:48:12`.

![image](https://cloud.githubusercontent.com/assets/2510026/5702173/47ffd988-9a67-11e4-8959-f846561e3328.png)

**Comment by pavelhritonenko** [comment]
There is workaround. In each project that uses Suave I added Post-Build that sets the date of the modification to the current time:

    copy /b "$(TargetDir)/suave.*" +,,

**Comment by haf** [comment]
Cool... That was the same value as in my folder. Let me release a new version without that funny problem.

**Comment by haf** [comment]
Funny, they are wrong now, too. 
![screen shot 2015-01-12 at 16 19 19](https://cloud.githubusercontent.com/assets/193115/5705070/ce152a28-9a76-11e4-9ac8-505edcb07aa1.png)

But not on disk (i.e. when they are compressed with nuget they get the strange timestamp)

![screen shot 2015-01-12 at 16 20 01](https://cloud.githubusercontent.com/assets/193115/5705081/e0ce9d84-9a76-11e4-9a1c-c693638833c8.png)

**Comment by haf** [comment]
![screen shot 2015-01-12 at 16 25 17](https://cloud.githubusercontent.com/assets/193115/5705203/b89cd60e-9a77-11e4-9314-c5969f553de6.png)

**Comment by haf** [comment]
Created an issue on NuGet https://nuget.codeplex.com/workitem/4412 for it.

**Comment by pavelhritonenko** [comment]
Strange that I see this problem only with this library of ~100 used packages. Thank you for response.

**Comment by haf** [comment]
Mono version:

```
➜  ~  mono --version
Mono JIT compiler version 3.10.0 ((detached/92c4884 Thu Nov 13 23:27:38 EST 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.4svn-mono-(detached/e656cac)
	GC:            sgen
```

**Comment by vasily-kirichenko** [comment]
This bug causes every project that references Suave to build every time. Could you fix it?

**Comment by ademar** [comment]
Possible related:

> System.IO.Packaging doesn't capture file timestamps

https://github.com/OctopusDeploy/Issues/issues/829

Will keep looking

**Comment by ademar** [comment]
I've pushed version v.0.24.0 with proper timestamps.

Building the nuget on Windows does not exhibit this problem.

**Comment by haf** [comment]
This is still an issue, because I don't run windows.

**Comment by ademar** [comment]
yeah but this is a problem of nuget

**Comment by ademar** [comment]
what can you do here to fix it ? besides generating the nugets on windows ?

**Comment by haf** [comment]
I've linked the NuGet issue to this thread and I've also sent e-mails to the responsible people in the nuget team, awaiting replies, so if this issue which is linked is closed, it loses signal strength. Purely a human endeavour, therefore. =) Sure, Suave can't so anything about it, but while I'm trying to chat up the MSFT-shielded NuGet team, perhaps we could have it open? Please?

**Comment by ademar** [comment]
OK. Is it possible to bypass NuGet with Paket ? I've heard they have a pack command now.

**Comment by haf** [comment]
I can't find it. Perhaps in some future version? /cc @forki

**Comment by kolektiv** [comment]
It's just gone in, I imagine it's in the alpha version at the moment. I
believe fake support will happen shortly after too, which will be genuinely
awesome.

**Comment by forki** [comment]
it's in alpha channel but we're streamlining and stabilizing. Also expect a FAKE task very very soon.

**Comment by haf** [comment]
Sweet, remember to verify filestamps in the compressed output on mono ;)

**Comment by haf** [comment]
@pavelhritonenko I just tested `paket pack` and it works very nicely. Would you consider doing a PR with the changed bits to make this project package through that command rather than NuGet to get around this bug?

**Comment by pavelhritonenko** [comment]
Nuget package 0.3.12 have same issue: https://api.nuget.org/packages/suave.0.31.2.nupkg

![image](https://cloud.githubusercontent.com/assets/2510026/10243299/588814ba-6900-11e5-8a1c-51c2471466a2.png)

**Comment by haf** [comment]
Removing in favour of #378.
