### ISSUE TITLE
Suave hangs on exactly every other request in very simple test app

### ISSUE THREAD

**Issue by jamesjrg** [SuaveIO/suave#201]
Steps to reproduce:

I have a simple Suave test app running in Windows 8 which consists soley of this:

```
module Program

open Suave
open Suave.Http
open Suave.Web

[<EntryPoint>]
let main argv = 
    web_server default_config (RequestErrors.NOT_FOUND "404 not found" ) 
    0
```

I have the Postman API tester (http://www.getpostman.com), which I use to send POST requests to the server. I send the post data "a a" (without the quotation marks). Given that all requests will match the same web part, the exact url doesn't matter. I have the following further information:

- I checked the hex stream of the postman request and it uses the correct CRLF linebreaks

- The issue does not occur if I remove the space in the post data (although removing the space may just hide the bug)

- The error occurs without failure *exactly* every other time. The first request always succeeds, the next hangs, the next succeeds, the next hangs, etc.

- I changed Suave's Visual Studio build config to target Any CPU so the pdb output matched the AnyCPU type of my test app, and then attached a debugger to the Suave dll running via my test app.

I put a break point at the beginning of function  ```let process_request ({ connection = connection...``` where read_line is called. The breakpoint in process_request is always hit, but the debugger only steps into read_line every other time, when the request succeeds.

On the occasions when the request succeeds, the debugger steps from process_request to SocketMonad.Delay to read_line as you would expect.

On the occasions when the request hangs the debugger skips over the call to read_line, and the contents of the binding first_line have somehow been set to "a aPOST /asdshadsa HTTP/1.1"

**Comment by ademar** [comment]
this is not a bug per se but a design issue and will be solved on #198

**Comment by jamesjrg** [comment]
Oh, OK! I assumed I only needed to parse the post data if I actually needed it, but I guess soon I won't need to explicitly parse it anywhere.

**Comment by ademar** [comment]
@jamesjrg new release should had fixed this problem.
