### ISSUE TITLE
Consider adding the "single F# Script" to the Getting Started instructions

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#202]
Please take a look at https://gist.github.com/dsyme/9b18608b78dccf92ba33 and consider adding it as a "Getting Started" technique.  I'll send a PR if others like the technique (and you don't get to it first)

It is cool because it is a fully self-contained F# script that uses a Paket technique that is very reusable in other scripting settings.

**Comment by haf** [comment]
I've added it to https://github.com/SuaveIO/suave/commit/4701f38d4949e2608202f4ad6697b2849b1069cc but I need to get the CI server up again to push it.

**Comment by dsyme** [comment]
That's great @haf 

I think adjust it so it doesn't use FSharp.Data - just serves a static string or System.DateTime.Now as usual.
