### ISSUE TITLE
Underscores and ticks in API and possible API review

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#204]
Hi Suavers,

I'm considering featuring Suave in Chapter 2 or 3 of the revised Expert F# 4.0, using the getting started script here: https://github.com/SuaveIO/suave/issues/202, since it's a great example of power scripting.  WebSharper will still be featured later.

One thing that concerns me is the prevalence of underscores in the Suave API and docs.  Normally, F# APIs just don't use "_" in names.  I'm wondering, what's the rationale for this?

Going further, I wonder if you'd be opening to doing an API review with me at some point - or I could do it offline and submit a proposed patch implementing API revisions I would recommend.  Of course I would need to use the library a fair bit.

Let me know what you think, I really like the direction Suave is going and want to help make it something we'd reference in the book

Thanks
Don

**Comment by ademar** [comment]
Hi Don,

I think there was not much of a rationale just that we happened to settle on that style; perhaps because `camelCase` is usually associated with OOP languages vs `snake_case` being more prevalent in languages that *look* like F# ie Python, OCaml, Ruby

I do not feel strongly either way. If @haf agrees we can revisit the naming conventions.

We are definitely open to an API review and welcome any feedback you may have, we feel honoured you have taken an interest in the project :)

Regards,

Ademar

**Comment by haf** [comment]
Hi Don,

That's great news =).

I agree with Ademar in general. For me underscores is an escape from the terror of C# and also a way to make the code more amenable to non-CLR programmers, with experience in e.g. OCaml/ML or Ruby or Haskell.

It seems that you are trying to keep together the F# eco-system, and for that good cause I'd be willing to reconsider previous naming choices.

**Comment by dsyme** [comment]
Fantastic, I'm enjoying looking over the library.

You are right that I guess I'd like to keep the F# ecosystem "together".  This may be quite challenging in this case as I do understand why you want to culturally move away from C# naming conventions, to put some cultural distance between you and the .NET world for this library.  Tricky.

BTW I also noticed the use of tick-marks ' in the API, e.g. stateful'.   They should definitely be removed. I adjusted the title of this issue to reflect that.

I'll send an initial "low hanging fruit" PR and make some notes for discussion

**Comment by haf** [comment]
Alright, sounds good. As long as we make it a branch of its own, or a large PR, so that downstream consumers don't have to update their API usages multiple times.

**Comment by dsyme** [comment]
@haf @ademar - are you both in Stockholm (or European time)?  I'm wondering if we could have a chat about this. I've been taking a look at this and I think it's the right direction - it would likely make Suave much more central to the F# community in the long run. But equally I understand it would be adjusting your existing naming conventions and would benefit from considerable discussion between 3-4 people.  Above all I'd like to gauge how you both feel about it.  Email me? thanks

**Comment by dsyme** [comment]
@ademar - I see you're in Toronto?

**Comment by dsyme** [comment]
@haf - point taken about "make the code more amenable to non-CLR programmers".

**Comment by varon** [comment]
This seems like a good idea.

 My 2c is that you should stick with the conventions of the standard library of the language. I'd be behind such a move.

**Comment by kolektiv** [comment]
Anecdata, but I've spoken to people who were a bit hesitant about Suave not feeling F# like. Not sure if that's a helpful comment, but maybe interesting :)

**Comment by dsyme** [comment]
Previously I didn't mind too much either way - I love the "style" of Suave either way, and am impressed with the code and functionality.  

However when I came to include the sample in Expert F# 4.0, I really did think "yes, the priority is to have this look right to F# programmers".  I think we can get it to the point where it's light, accessible and F#-idiomatic.

**Comment by haf** [comment]
We could have a chat today at 16:00 UTC? That would probably suit us all? Skype?

**Comment by dsyme** [comment]
That time works for me!

**Comment by haf** [comment]
Skype handle: `h.feldt`

**Comment by varon** [comment]
If possible, I'd like to be included in the Skype chat.

In terms of utility, I might be able to provide some insight as to how the API feels to someone unfamiliar with the library. More generally, however, I'm interested and believe I'd stand to learn a lot from the discussion.

**Comment by ademar** [comment]
I will be busy this morning and won't be online till later in the afternoon - tomorrow is a better day for me. Regardless you guys can go ahead and meet today to get the ball rolling.

Cheers

**Comment by haf** [comment]
Let's meet today and chat and get the ball rolling then -- I think we're all pretty much on the same page already anyway (based on what's been said in this thread). Varon, if you want you can join in. Add me on skype and we'll set up a three-way conversation.

**Comment by haf** [comment]
![dsc_0230](https://cloud.githubusercontent.com/assets/193115/6150784/b5a5d3b8-b211-11e4-9bae-d0d98aa80cd8.JPG)

Some notes from the discussion.

**Comment by haf** [comment]
Docs [for the intern](https://github.com/SuaveIO/suave/commit/f7ecf33af4c8057c5b104e380225e8bc53ba4f06)

**Comment by scitesy** [comment]
Thank you for making the meeting notes available!

**Comment by haf** [comment]
We discussed removing `SuaveTask<'a>` completely and naming it all:

``` fsharp
type AsyncHttpTask = Async<HttpContext option>
type WebPart = HttpContext -> AsyncHttpTask
```

**Comment by haf** [comment]
We said I'll add an example model binding.

**Comment by haf** [comment]
@scitesy You're welcome =)

**Comment by haf** [comment]
Didn't we add obsoletes for all changes to very public APIs?

![screen shot 2015-02-19 at 10 38 51](https://cloud.githubusercontent.com/assets/193115/6264356/97c21eca-b823-11e4-924c-0fa2192d638c.png)

**Comment by ademar** [comment]
@haf I've included a number of missing obsoletes in #214

**Comment by haf** [comment]
Ok, great! =)

**Comment by haf** [comment]
Seems like we're wrapped up this issue, haven't we?

**Comment by haf** [comment]
Thanks to @dsyme for your great work!
