### ISSUE TITLE
Race condition question

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#209]
I'm trying to understand if there is a race condition here,  Lots of concurrent processing jobs share access to mutable stacks a,b and c:

      let readArgs = b.Pop()
      let writeArgs = c.Pop()
    ...
      a.Push acceptArgs
      b.Push readArgs
      c.Push writeArgs

Since multiple threadpool threads are writing to these stacks, the pops and pushes represent a race condition, don't they?

**Comment by ademar** [comment]
Is it ? I think you get a race condition when one thread try to acquire two contending resources simultaneously; this is not whats happening here though ..

It would certainly reduce contention acquiring the triplet in one shot.

**Comment by haf** [comment]
Right now we have primitive performance testing that also serve as race condition checking, they run every testrun, but they could be improved by also sending a hash of the body which could be a random string, on every request -- that way it would be easier to observe data any potential data corruption.

**Comment by dsyme** [comment]
As far as I understand, the stacks are coordinated. 

If thread 1 pops from A, then suspends, then thread 2 pops from A and B, then thread 2 gets inconsistent entries (entry 2 from A and entry 1 from B)?

**Comment by ademar** [comment]
Access to the stacks is synchronized 

https://github.com/SuaveIO/suave/blob/master/src/Suave/Sockets/SocketEventArgsPool.fs

I do not think the stacks are coordinated.

**Comment by dsyme** [comment]
OK, I see, so the stacks are just used for saving allocations, and it doesn't matter if the pair of obejcts popped here

      let readArgs = b.Pop()
      let writeArgs = c.Pop()

don't match the pair pushed here:

      b.Push readArgs
      c.Push writeArgs

I'll close this then, thanks
