### ISSUE TITLE
v0.24 and v0.25 has wrong tags in git repo

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#212]
They should be tagged `v0.24.0` and `v0.25.0`, not `v.0.25.0` nor `v.0.24.0`.

 - [x] new tags from old
 - [x] update release references (/releases)
 - [x] remove old tags.

**Comment by ademar** [comment]
oops .. i tried editing one of these and a new one was created ..

**Comment by ademar** [comment]
Ok, I'm taking care of renaming the tags

**Comment by ademar** [comment]
It is fixed now, let me know if you find anything out of place.
