### ISSUE TITLE
Please give getting-started level info on hosting suave websites

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#218]
I asked this on twitter.. I'm still struggling to work out the best way to actually host suave websites once authored. An Azure VM? An AWS VM? Some service that will take my code directly from GitHub as soon as I push it?  I can do the first two - it's not rocket science - but it's not as smooth as it feels like it should be and I'd like to make it really simple for other people to replicate (including people who may never have any web server programming before).

It would be helpful if some basics about this were covered in the http://suave.io material.  

Best regards
don

**Comment by ademar** [comment]
We can do a tutorial for Heroku, like this one http://blog.ashleytowns.id.au/posts/2013-04/2013-04-01-running-csharp-fsharp-xbuild-nuget-on-heroku.html

I'll give it a shot.

**Comment by haf** [comment]
I made https://github.com/SuaveIO/Melano -- did you see it? Is it something like that, but with more screenshots and more of an in-depth guide you're after?

**Comment by dsyme** [comment]
Yes, a full tutorial for a freemium hosting service like heroku would be good. Melano looks ok but if you do that please choose a specific freemium hosting service and explain w.r.t. that.

I tried to create a Heroku buildpack but failed.

The end experience I was aiming for is to have a single "app.fsx" script in my repo, which is a Suave + Paket script (like the one on http://suave.io), which when I push to github will deploy to heroku or some other hosting.

My attempts to spec a Heroku buildpack are [here](https://github.com/dsyme/mono-suave-buildpack/) and my attempt to use it are [here](https://github.com/dsyme/fsharp-suave-heroku-getting-started).  

Here's what I tried:

```
heroku login
git clone https://github.com/fsprojects/fsharp-suave-heroku-getting-started.git -d myproj
cd myproj
heroku create shielded-springs-9874 --buildpack https://github.com/dsyme/mono-suave-buildpack.git 
heroku git:remote -a shielded-springs-9874
git push heroku master  
```
but I got this error about "no Cedar-supported app":  I couldn't work out how to get beyond this.
```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote:
remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to shielded-springs-9874.
remote:
```
I tried to actually "publish" the buildpack but it didn't seem to make any difference

```
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
apt-get install git
heroku plugins:install https://github.com/heroku/heroku-buildkits 
git clone https://github.com/dsyme/mono-suave-buildpack/ 
cd mono-suave-buildpack
heroku buildkits:publish dsyme/mono-suave-buildpack-test 
```

We really need to make this 100% simple for people, right now it seems really hard to get F# + Suave up and hosted.  Ideally we'd eventually push F# +Suave support into one or more freemium hosting services.

**Comment by dsyme** [comment]
(I'm actually making more progress on this - you need to have a .sln file in the application directory for heroku to accept it)

**Comment by haf** [comment]
This works except the part where it stalls on paket install https://github.com/haf/sample-hello-fsharp - for your reference since you seems to be going in a similar direction

**Comment by ademar** [comment]
> I was aiming for is to have a single "app.fsx" script in my repo, which is a Suave + Paket script 

@dsyme Since the buildpack is going to compile the repo + download Paket + nugets, etc the "app.fs(x)"  wouldn't need the Paket ceremony.

**Comment by dsyme** [comment]
@haf - The Deis support looks very close to being superb Does deis have a Windows client? And it would be good to outline or link to the easiest paths to getting Deis VMs on a reputable provider.

@ademar - Yes, I #if'd the Paket download out

**Comment by haf** [comment]
@dsyme Deis/hosting is sort of blocked on the F# foundation not replying to my e-mail about an official F# docker image.

**Comment by dsyme** [comment]
@haf I know they want to approve that.  I think @tpetricek can give you approval under the mandate of the Core Engineering Group of the FSSF.  What do you actually need - an email or blog post or ...?

**Comment by haf** [comment]
@dsyme No, I just needed confirmation from them, which I got the 15th September. I restarted the communication with docker-hub today.

**Comment by reidev275** [comment]
Anything on self hosting Suave?  I have supporting app projects for my company where Suave would be great, but I need to host it behind a firewall so that it has network access to protected assets.

**Comment by haf** [comment]
Just run `startWebServer` and it's self hosted.

**Comment by reidev275** [comment]
Right, that works well until the server is restarted, fsi is stopped etc.  Unfortunately all my hosting experience is with IIS.  Doesn't mean I want Suave hosted there, but I need to have it someplace where I can assign dns and have the site come back up after restarts and the like.

**Comment by haf** [comment]
Windows; place it in a service: https://github.com/SuaveIO/suave/blob/master/examples/TopshelfService/Program.fs

Linux: place it in a service manager:

``` bash
cat <<CONF >/etc/systemd/system/myapp.service
[Unit]
Description=Logibit Qvitoo
Wants=bus-org.freedesktop.NetworkManager.target
After=bus-org.freedesktop.NetworkManager.target

[Service]
EnvironmentFile=/etc/sysconfig/myapp
User=myapp
ExecStart=/opt/myapp/start
Restart=always
RestartSec=5
CONF
systemctl daemon-reload
systemctl enable myapp
systemctl start myapp
```

**Comment by reidev275** [comment]
awesome, thank you!
