### ISSUE TITLE
Generated api docs

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#223]
Hi guys,

What are your thoughts on generated api docs?  I took a look at running FSharp.Formatting and the results looked ok, but it would need to be integrated into your build + deploy process.

I saw a previous PR using FSharp.Formatting but it doesn't seem to have been committed.

Also, the docs are getting a bit big for a single page, it would be good to split them out into multiple pages?

(All this comes because I was thinking of tweeting a link to the Heroku example, when I realized that the docs really needed improving, so I thought I'd take a look at it)

**Comment by dsyme** [comment]
Here's the branch where I started working on this: https://github.com/SuaveIO/suave/compare/master...dsyme:api-docs?expand=1

My though was to normalize Suave to use the standard FSharp.Formatting workflow where the canonical copy of all the docs live in "master" and the build process publishes to "gh-pages"

So the branch contains all the existing content of "gh-pages" plus a generate.fsx script to generate the API doc pages.

What's missing is the stuff to automatically transfer the "output" across into a clone of gh-pages and  commit it (e.g. on a "release" build).  In other repos this is normally orchestrated by FAKE

**Comment by ademar** [comment]
I like this. 

At this point we wouldn't need the branch "gh-pages" since we are not serving http://suave.io from GitHub. We are actually pushing the output of Jekill to a vm on Azure where it is served by Suave it-self.

Which takes me to the next point. 

We can start serving the site http://suave.io from Heroku with the recipe Don has just created and stop paying for the Azure VM.

**Comment by ademar** [comment]
So I'm thinking we should attach a (floating) menu to the righ (or left) of our content and move stuff to its own articles. End up with a cleaner simplified home page. 

What do you guys think ?

**Comment by haf** [comment]
Sounds like a good thing all around: changing to heroku and splitting out content into sub-pages.

If all of the tooling works well on mono, which was the problem in the thread for docs, then let's go for it.

**Comment by dsyme** [comment]
Yes, we need to check the docs tooling works on Mono.  Building docs as part of mono CI seems one way to do this. I'll send a WIP PR that does this

Two questions:

* Why not let github serve the pages?  It seems simplest.

* Would you be open to moving to FAKE for automation?

**Comment by haf** [comment]
I think it's a matter of dog-fooding, mostly. If we build a web server, we should use it for our own web serving...

The upside of this is that when we improve the docs for e.g. server-sent-events we can publish those events from the server. Or when we want SSL, or any other feature that goes beyond static web pages.

**Comment by ImaginaryDevelopment** [comment]
We could use githubpages for comparison or fall-back?

**Comment by haf** [comment]
These docs have been generated at https://suave.io/Suave.html.
