### ISSUE TITLE
tcp request processing failed

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#228]
```
[V] 2015-04-06T13:51:12.5074830Z: tcp request processing failed [Suave.Tcp.tcp_ip_server.job] exn:
System.Exception: did not find header, because header_params received None
  at Suave.Utils.Parsing.headerParams (Microsoft.FSharp.Core.FSharpOption`1 header) [0x00000] in <filename unknown>:0
  at Suave.Web+ParsingAndControl+loop@207-31.Invoke (System.Tuple`2 _arg2) [0x00000] in <filename unknown>:0
  at <StartupCode$Suave>.$SocketMonad+Bind@15-1[System.Tuple`2[Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.String,System.String]],Suave.Sockets.Connection],Suave.Types+HttpContext].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 _arg1) [0x00000] in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@787-1[Microsoft.FSharp.Core.FSharpChoice`2[System.Tuple`2[Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.String,System.String]],Suave.Sockets.Connection],Suave.Sockets.SocketUtils+Error],Microsoft.FSharp.Core.FSharpChoice`2[Suave.Types+HttpContext,Suave.Sockets.SocketUtils+Error]].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 a) [0x00000] in <filename unknown>:0
```

**Comment by ademar** [comment]
Do you have a repo ? I suspect there is a missing (required) header in the request.

**Comment by haf** [comment]
Repro: https://github.com/haf/Http.fs/commit/f8859ccf003bba5508a10424d328d346e23f146b

**Comment by haf** [comment]
Run ./build.fsx

**Comment by ademar** [comment]
Finding difficulty to build/run this on Windows and Linux ...

**Comment by haf** [comment]
Hmm, ok... What errors are you getting?

**Comment by ademar** [comment]
Never mind got it to build. The FAKE reference in the build script is
incorrect.



On Monday, April 6, 2015, Henrik Feldt <notifications@github.com> wrote:

> Hmm, ok... What errors are you getting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/228#issuecomment-90082302>.
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by haf** [comment]
I just pushed https://github.com/haf/Http.fs/commit/f657607de8823d524f3556916acd0d167e8544ed that bootstraps FAKE properly.

**Comment by haf** [comment]
You can see what it sends: https://github.com/haf/Http.fs/blob/f657607de8823d524f3556916acd0d167e8544ed/HttpClient.UnitTests/RequestBody.fs#L42

**Comment by ademar** [comment]
I found the bug - we haven't implemented 100-Continue (ref #72). 

http://haacked.com/archive/2004/05/15/http-web-request-expect-100-continue.aspx/

**Comment by haf** [comment]
Wow, that's pretty obscure...

**Comment by ademar** [comment]
There is a workaround at the end of the article.

**Comment by haf** [comment]
Yeah, ok. Did you try it in the repro?

**Comment by ademar** [comment]
I just did, I see is still broken.

**Comment by ademar** [comment]
Just speculating .. but it seems like the post data is not being sent??

**Comment by ademar** [comment]
Or there is an extra CRLF somewhere ...

**Comment by haf** [comment]
That might be the case; I'll add in verbose logging for us to have a look... Right now I'm rebasing against master, just finished that.

**Comment by ademar** [comment]
The problem is that the payload you are constructing is invalid. I suspect it might not be possible to cook a custom valid payload with the HttpRequest class.

These two yields here are incorrect. https://github.com/haf/Http.fs/blob/feature/bodies/HttpClient/HttpClient.fs#L405

That content type header should be part of the headers that were already sent by HttpClient (you may not have control over this.)

**Comment by ademar** [comment]
Actually I had already encountered this problem and this was the solution.

https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Parsing.fs#L43

**Comment by haf** [comment]
I'm not sure about what you're saying is correct.

This is what a POST looks like:

![screen shot 2015-04-06 at 22 52 00](https://cloud.githubusercontent.com/assets/193115/7012199/9cc022fe-dcaf-11e4-8c44-33e2c6c69cb9.png)

Content-Type exists both inside the upload stream and in the request headers.

**Comment by ademar** [comment]
That is not what I mean. 

You are sending the line `"Content-type: multipart/form-data; boundary=yadayadayda"` in the body of the POST, instead of as a regular HTTP header.

In case of a multipart post the first line of the body should be the boundary string.

**Comment by haf** [comment]
Ok, I've moved it to the header and Suave is still hanging. See https://github.com/relentless/Http.fs/commit/b7c1da05357854d170e6158078406a522a2502be

**Comment by haf** [comment]
I think suave is hanging on the multipart/mixed request data, because that's not something we widely test, since browsers never send it.

**Comment by ademar** [comment]
OK, almost there.

What is happening is that 'HttpRequest' is ignoring the `Content-type` header you are seting and it is generating its own with a different boundary string.

That is why you need to do this somewhere.

``fsharp
httpContent.Headers.TryAddWithoutValidation("Content-Type","multipart/form-data; boundary=99233d57-854a-4b17-905b-ae37970e8a39") |> ignore
```

**Comment by ademar** [comment]
Between we do have a test for parsing multipart. It shows how to send a multipart payload.

https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Parsing.fs#L46 

Wireshark helps debugging this things, you would have noticed the malformed requests.

**Comment by haf** [comment]
That's not the case, here's the output of `nc -l localhost 1234` when I use the library:

```
 nc -l localhost 1234
POST /filenames HTTP/1.1
Content-Type: multipart/form-data; boundary=wlWKnnjndntwebXx:bUbgUQvCaRbpN
Content-Length: 603
Expect: 100-continue
Connection: keep-alive
Host: localhost:1234

--wlWKnnjndntwebXx:bUbgUQvCaRbpN
Content-Disposition: form-data; name="submit-name"

Larry
--wlWKnnjndntwebXx:bUbgUQvCaRbpN
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

Hello World
--wlWKnnjndntwebXx:bUbgUQvCaRbpN
Content-Disposition: form-data; name="files"; filename="file2.gif"
Content-Type: text/plain

...contents of file2.gif...
--wlWKnnjndntwebXx:bUbgUQvCaRbpN
Content-Disposition: form-data; name="files"; filename="tracker.gif"
Content-Type: image/gif
Content-Transfer-Encoding: base64

AQID
--wlWKnnjndntwebXx:bUbgUQvCaRbpN--
```

With this file:

```
#!/usr/bin/env fsharpi

#I "bin/Debug"
#r "HttpClient.dll"

open HttpClient

let firstCt, secondCt, thirdCt =
    ContentType.Create("text", "plain"),
    ContentType.Create("text", "plain"),
    ContentType.Create("image", "gif")

let req =
    createRequest Post "http://localhost:1234/filenames"
    |> withBody
        //([ SingleFile ("file", ("file1.txt", firstCt, Plain "Hello World")) ]|> BodyForm)

                        // example from http://www.w3.org/TR/html401/interact/forms.html
        ([   NameValue { name = "submit-name"; value = "Larry" }
             FormFile ("files", ("file1.txt", firstCt, Plain "Hello World"))
             FormFile ("files", ("file2.gif", secondCt, Plain "...contents of file2.gif..."))
             FormFile ("files", ("tracker.gif", thirdCt, Binary [|1uy; 2uy; 3uy |]))
        ]
        |> BodyForm)

let response = req |> getResponse

printfn "%O" response
```

Your example code is for HttpClient, but I'm using HttpWebRequest in the back, just like HttpClient is.

**Comment by ademar** [comment]
In this request you are still sending `Expect: 100-continue`, you need to
disabled that.

On Tue, Apr 7, 2015 at 10:35 AM, Henrik Feldt <notifications@github.com>
wrote:

> That's not the case, here's the output of nc -l localhost 1234 when I use
> the library:
>
>  nc -l localhost 1234
> POST /filenames HTTP/1.1
> Content-Type: multipart/form-data; boundary=wlWKnnjndntwebXx:bUbgUQvCaRbpN
> Content-Length: 603
> Expect: 100-continue
> Connection: keep-alive
> Host: localhost:1234
>
> --wlWKnnjndntwebXx:bUbgUQvCaRbpN
> Content-Disposition: form-data; name="submit-name"
>
> Larry
> --wlWKnnjndntwebXx:bUbgUQvCaRbpN
> Content-Disposition: form-data; name="files"; filename="file1.txt"
> Content-Type: text/plain
>
> Hello World
> --wlWKnnjndntwebXx:bUbgUQvCaRbpN
> Content-Disposition: form-data; name="files"; filename="file2.gif"
> Content-Type: text/plain
>
> ...contents of file2.gif...
> --wlWKnnjndntwebXx:bUbgUQvCaRbpN
> Content-Disposition: form-data; name="files"; filename="tracker.gif"
> Content-Type: image/gif
> Content-Transfer-Encoding: base64
>
> AQID
> --wlWKnnjndntwebXx:bUbgUQvCaRbpN--
>
> With this file:
>
> #!/usr/bin/env fsharpi
>
> #I "bin/Debug"
> #r "HttpClient.dll"
>
> open HttpClient
>
> let firstCt, secondCt, thirdCt =
>     ContentType.Create("text", "plain"),
>     ContentType.Create("text", "plain"),
>     ContentType.Create("image", "gif")
>
> let req =
>     createRequest Post "http://localhost:1234/filenames"
>     |> withBody
>         //([ SingleFile ("file", ("file1.txt", firstCt, Plain "Hello World")) ]|> BodyForm)
>
>                         // example from http://www.w3.org/TR/html401/interact/forms.html
>         ([   NameValue { name = "submit-name"; value = "Larry" }
>              FormFile ("files", ("file1.txt", firstCt, Plain "Hello World"))
>              FormFile ("files", ("file2.gif", secondCt, Plain "...contents of file2.gif..."))
>              FormFile ("files", ("tracker.gif", thirdCt, Binary [|1uy; 2uy; 3uy |]))
>         ]
>         |> BodyForm)
>
> let response = req |> getResponse
>
> printfn "%O" response
>
> Your example code is for HttpClient, but I'm using HttpWebRequest in the
> back, just like HttpClient is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/228#issuecomment-90586906>.
>



-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by haf** [comment]
Yes, I know, but you've already tested with disabling it. I've created a simplest-possible-repo here: https://github.com/haf/Http.fs/commit/8f4aa97a12794fbbb77a7af25046b3fa03bcfdf1

**Comment by ademar** [comment]
Let me run the tests I'll get back to you.

**Comment by haf** [comment]
Thanks a lot, @ademar  =)

**Comment by ademar** [comment]
According to the standard there should be a CRLF after each boundary including the last one.

> The boundary must be followed immediately either by another CRLF ...
>  close-delimiter := "--" boundary "--" CRLF ; 

http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

It seems there is no CRLF after the last boundary you sent so Suave blocks on waiting for more data on the socket.

**Comment by haf** [comment]
The last thing isn't called `boundary`, it's called `close-delimiter`. It seems to me, reading the BNF in the RFC, that it's not required:

```
multipart-body := preamble 1*encapsulation 
               close-delimiter epilogue 

encapsulation := delimiter CRLF body-part 
```

**Comment by ademar** [comment]
> close-delimiter := "--" boundary "--" CRLF

**Comment by haf** [comment]
I can't find that in the docs? (see my comment above)

**Comment by ademar** [comment]
You right it is not there .. I picked it up from here http://www.freesoft.org/CIE/RFC/1521/16.htm

**Comment by ademar** [comment]
But nevertheless it says so in words in the first link

> The boundary must be followed immediately either by another CRLF

**Comment by haf** [comment]
I think we should be on the safe side and not assume a CRLF after, since there's a public RFC that doesn't specify it.

**Comment by haf** [comment]
Yes, but they are talking about the 'boundary' then, not specifically the 'close-delimiter', and the docs also say:

     The encapsulation boundary following **the last body part is a distinguished delimiter that indicates that no further body parts will follow**. Such a delimiter is identical to the previous delimiters, with the addition of two more hyphens at the end of the line:

     --gc0p4Jq0M2Yt08jU534c0p-- 

    There appears to be room for additional information prior to the first encapsulation boundary and following the final boundary. These areas should generally be left blank, and **implementations should ignore anything that appears before the first boundary or after the last one**.

**Comment by haf** [comment]
Besides HttpListener supports it, so I would say we should be open to no CRLF ;).

**Comment by haf** [comment]
[RFC1521](https://www.ietf.org/rfc/rfc1521.txt) from IETF isn't match the one from FreeSoft -- so there seems to be consensus that it's not required in both RFC1521 and RFC1341.

**Comment by ademar** [comment]
You are correct, I'll fix this in Suave.

**Comment by haf** [comment]
I'm also fixing the opposite in the client, to be 'more' towards the standard.

**Comment by haf** [comment]
Ok, crashing on something else now:

```
[V] 2015-04-07T16:18:55.5084450Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2015-04-07T16:18:55.5949150Z: listener started in 78.296 ms with binding 0.0.0.0:1234 [Suave.Tcp.tcp_ip_server]
[V] 2015-04-07T16:18:59.9241510Z: 127.0.0.1 connected, total: 1 clients [Suave.Tcp.tcp_ip_server.job]
[V] 2015-04-07T16:18:59.9299710Z: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcp_ip_server.job] [Suave.Socket.BufferManager]
[V] 2015-04-07T16:18:59.9342720Z: -> processor [Suave.Web.request_loop.loop]
[V] 2015-04-07T16:18:59.9423790Z: reserving buffer: 802816, free count: 98 [Suave.Web.read_till_pattern.loop] [Suave.Socket.BufferManager]
[V] 2015-04-07T16:18:59.9926630Z: <- processor [Suave.Web.request_loop.loop]
inside suave
[V] 2015-04-07T16:19:00.0072980Z: 'Connection: keep-alive' recurse [Suave.Web.request_loop.loop]
[V] 2015-04-07T16:19:00.0073920Z: -> processor [Suave.Web.request_loop.loop]
[V] 2015-04-07T16:19:00.0088540Z: freeing buffer: 802816, free count: 99 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-04-07T16:19:00.0129830Z: tcp request processing failed [Suave.Tcp.tcp_ip_server.job] exn:
System.Exception: invalid url: ''
  at Suave.Web+ParsingAndControl+processRequest@292-1.Invoke (System.Tuple`2 _arg1) [0x00000] in <filename unknown>:0
  at <StartupCode$Suave>.$SocketMonad+Bind@15-1[System.Tuple`2[System.String,Suave.Sockets.Connection],Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext]].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 _arg1) [0x00000] in <filename unknown>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@789-1[Microsoft.FSharp.Core.FSharpChoice`2[System.Tuple`2[System.String,Suave.Sockets.Connection],Suave.Sockets.SocketUtils+Error],Microsoft.FSharp.Core.FSharpChoice`2[Microsoft.FSharp.Core.FSharpOption`1[Suave.Types+HttpContext],Suave.Sockets.SocketUtils+Error]].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 a) [0x00000] in <filename unknown>:0
```

**Comment by ademar** [comment]
Same test ? Here it runs fine after patching the CRLF.

**Comment by haf** [comment]
Really? Yeah, same test.

**Comment by haf** [comment]
This: 6ff0b76

**Comment by ademar** [comment]
I works with this chapuza here:

```fsharp
let private formatBodyFormData clientState encoding formData boundary =
        let kk = 
          generateFormData clientState encoding boundary formData
          |> String.concat CRLF
        (kk + CRLF) |> encoding.GetBytes
```

**Comment by haf** [comment]
Funky, let me investigate tomorrow.

**Comment by haf** [comment]
@ademar So I'm still getting errors, currently improving Suave to tell me where it's at.

**Comment by haf** [comment]
Ok, this is turning into a large changeset ;)

**Comment by haf** [comment]
This was fixed for me a while ago, closing.
