### ISSUE TITLE
Consider how we parse request data

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#229]
Right now it's fairly ad-hoc. I would feel safer if we could use a parser like FParsec instead of hand-coded logic to find boundaries etc. Right now we have multipart/form-data that's silently blocking a connection based on input; if talking about DoS attacks like we did before; just browsing the code and tricking it into throwing an exception is enough to make requests never return.

Let's pretend I'm the bad guy, and try to find vulnerabilities/problems with the code:

Example code:

``` fsharp
      if not(firstLine.Equals("--")) then
        let! partHeaders, connection = readHeaders connection
        let contentDisposition = partHeaders %% "content-disposition"
        let fieldname = 
          (headerParams contentDisposition).TryLookup "name"
          |> Option.get
          |> (fun x -> x.Trim('"'))
        let contentType = partHeaders %% "content-type"
        match contentType with
        | Some(x) when x.StartsWith("multipart/mixed") ->
          let subboundary = "--" + x.Substring(x.IndexOf('=') + 1).TrimStart()
          return! loop subboundary { ctx with connection = connection }
        | Some(x) ->
          let tempFileName = Path.GetTempFileName()
          use tempFile = new FileStream(tempFileName, FileMode.Truncate)
          let! a, connection = readUntil (ASCII.bytes(eol + boundary)) (fun x y -> async { do! tempFile.AsyncWrite(x.Array, x.Offset, y) } ) connection
          let fileLength = tempFile.Length
          tempFile.Close()
          if fileLength > 0L then
            let filename =
              (headerParams contentDisposition).["filename"].Trim('"')
            let upload = 
                { fieldName     = fieldname
                  fileName      = filename
                  mimeType      = (contentType |> Option.get) 
                  tempFilePath = tempFileName }
            return! loop boundary { ctx with request = { ctx.request with files = upload :: ctx.request.files};  connection = connection }
          else
            File.Delete tempFileName
            return! loop boundary { ctx with connection = connection }
```

This code has these concerns:

 - parsing by large pieces of arrow-code (if not ( ... ))
 - parsing by bytes
 - temporary file handling
 - stream IO to disk/buffering
 - taking finished parse data and transforming into DTOs
 - content-type matching

It does not meet the SRP.

Some patterns:

 - `let! a, connection = readUntil (ASCII.bytes(eol + boundary)) (fun x y -> async { do! tempFile.AsyncWrite(x.Array, x.Offset, y) } ) connection` is repeated twice

### What if?

 - Content-Type: multipart/form-data; charset=utf-16 was on the request was UTF-16; each character will now be four bytes, but this parsing logic assumes it's ASCII/one byte: `ASCII.toStringAtOffset byts 0 byts.Length`
 - I send a file named: `Hello\" World.txt`?
 - I send a form-control named: `There\"we\"go`?
 - I want to unit-test the parsing logic? I can't, because statics are used to access the FileSystem. And because it's bound inside the Socket, I have to create a real socket to test the algorithm that operates on purely in-memory data
 - I send base64-encoded data, which is valid according to the spec
 - I send a multipart/mixed and then, according to the spec don't have a fieldname for every uploaded file (that would crash here: `(headerParams contentDisposition).TryLookup "name" |> Option.get`
 - I use the header: `Content-Transfer-Encoding` and encode part of the request with e.g. IBM487 or Latin1, inside the form-data?
 - I have a header with `;` inside its value? That would make headerParams fail.
 - No `Content-Type` is supplied for a form-data control/value? That would crash the server's tcp job and block that connection forever (until some OS timeout at least).
 - The boundary header key-value is **not** the first key-value pair of the `Content-Disposition` header? That makes this code forwards-incompatible, if we ever get another key-value (or there's one I don't know about)

**Comment by haf** [comment]
This has mostly been fixed - since there's no clear action point here, I'm closing. However, it's still a valid point and I think these edge cases will show themselves as potential DoS attacks as this would fail the request and not close the socket.

**Comment by ademar** [comment]
Yeah I am also not happy about this code and have been wanting to dedicate some time to work on it. It seems like the next most interesting thing to do for me now so I think I'll will come back to it soonish.
