### ISSUE TITLE
Does SuaveIO support live reload ?

### ISSUE THREAD

**Issue by darting** [SuaveIO/suave#232]
Hi there, is there any tool for live-reloading SuaveIO web applications ?

such as: https://github.com/codegangsta/gin

thanks

**Comment by haf** [comment]
You could probably use the linked utility for it, actually: https://github.com/codegangsta/gin/blob/master/lib/runner.go#L60 -- it's a reverse proxy that looks at the modified-date of files.

**Comment by ademar** [comment]
Live-reloading, in what sense? Suave will reload static files if they are modified.

**Comment by railcar88** [comment]
In dynamic language web app world often while in debug mode any code change would reload the running process. In this case a compile on the f# would need to happen before process reload. I think this what is requested.

**Comment by haf** [comment]
The proxy would in this case need to track the last-modified-date of the dlls and re-launch it; very doable imo.

**Comment by tpetricek** [comment]
I wrote a simple script to do this using F# Compiler Service - see the `host.fsx` script here: https://github.com/tpetricek/Fun3D/commit/a74bc622e13b9e708ba0202f60f7791a109d9268

**Comment by haf** [comment]
Cool! This will go nicely together with https://github.com/fsprojects/FsReveal/issues/35#issuecomment-78716092 when that's done. We could roll it all up into a web part of its own.

**Comment by haf** [comment]
I'm closing this issue as it's a nice discussion topic. In general the CLR doens't support unloading so it would have to be on a process level like is done where you're linking.
