### ISSUE TITLE
Suave sometimes locks files

### ISSUE THREAD

**Issue by tpetricek** [SuaveIO/suave#236]
I've been using Suave with FsReveal and FsLab runner - here, the typical scenario is that you start the server and then edit the source files, which then triggers re-generation of some HTML that is then copied to the output folder (from which Suave is hosting things).

Sometimes (sorry, I don't have 100% repro), the copying of files fails because the files are locked. As far as I can see, there is nothing else on my machine that could be locking the files (I might be wrong though), so I suspect that Suave might be locking some files?

Did anyone report the same issue? What would be the best way to look into this (e.g. to find out what files are locked by who)?

Also, when I clone Suave, building "src/Suave.sln" (on Windows) fails (with error in "Suave.Razor"):

> warning MSB3245: Could not resolve this reference. Could not locate the assembly "RazorEngine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

> ...src\Suave.Razor\Library.fs(11,6): error FS0039: The namespace or module 'RazorEngine' is not defined
> ...src\Suave.Razor\Library.fs(52,25): error FS0039: The namespace or module 'Razor' is not defined

**Comment by haf** [comment]
If you're on windows, there's the SysInternals' tool `handle` which I was using quite often when I was using Windows. It takes a string-like thing and then searches for that substring in all processes' open handles.

If you're on unix you can use `lsof -p <pid>` where `pid` is the process id of your process and it will list every handle that process is using.

**Comment by haf** [comment]
These lines:

https://github.com/SuaveIO/suave/blob/master/src/Suave/Http.fs#L516-L518

https://github.com/SuaveIO/suave/blob/master/src/Suave/Compression.fs#L102-L124

To me, it seems like the file stream is disposed properly.

**Comment by tpetricek** [comment]
Thanks for the pointers! I'll investigate this next time it happens - yeah, I had a look at these two places in the source code too and they looked good to me...

**Comment by haf** [comment]
Might it be just that your browser is reading the files; therefore suave is; just as you want to write to them? Could it be that the thing your write with tries to take an exclusive lock?

**Comment by haf** [comment]
I'm closing, because I'm not sure Suave is causing these errors. If you have a repro or we could observe it then we can reopen this issue.

**Comment by wastaz** [comment]
I'm having the same issue. Running a very small suave application that serves static files. Running grunt in parallell that does some basic concatenating and less compilation. After editing files/refreshing the page in browser and so on a couple of times I can reliably make Suave lock the files.

Here is the output of SysInternals handle:

    ------------------------------------------------------------------------------
    tretton37Reporter.exe pid: 4728 FREDRIKFORSA330\Fred
    14: File  (---)   C:\Windows
    1C: File  (---)   C:\Users\Fred\code\tretton37Reporter\tretton37Reporter\bin\Debug
    7C: Section       \Sessions\1\BaseNamedObjects\2608.msys-1.0S3.shared.02012-07-05 14:56
    AC: Section       \Sessions\1\BaseNamedObjects\2608.msys-1.0S3.Fred.02012-07-05 14:56
    B4: Section       \Sessions\1\BaseNamedObjects\2608.msys-1.0S3.Fred.02012-07-05 14:56
    E0: Section       \Sessions\1\BaseNamedObjects\cygpid.F08
    138: Section       \...\Cor_SxSPublic_IPCBlock
    13C: Section       \BaseNamedObjects\Cor_Private_IPCBlock_v4_4728
    25C: File  (---)   C:\Windows\assembly\pubpol3.dat
    274: File  (---)   C:\Users\Fred\code\tretton37Reporter\tretton37Reporter\bin\Debug\Suave.dll
    278: File  (---)   C:\Users\Fred\code\tretton37Reporter\tretton37Reporter\bin\Debug\tretton37Reporter.pdb
    294: Section       \Sessions\1\BaseNamedObjects\NLS_CodePage_437_3_2_0_0
    2C4: Section       \Sessions\1\BaseNamedObjects\windows_shell_global_counters
    318: Section       \Sessions\1\BaseNamedObjects\NLS_CodePage_1252_3_2_0_0
    320: Section       \Sessions\1\BaseNamedObjects\NLS_CodePage_437_3_2_0_0
    418: Section       \BaseNamedObjects\__ComCatalogCache__
    4B0: File  (---)   C:\Users\Fred\code\tretton37Reporter\web\index.html
    56C: File  (---)   C:\Users\Fred\code\tretton37Reporter\web\app\output\entire_application.js
    570: File  (---)   C:\Users\Fred\code\tretton37Reporter\web\templates\report.html
    574: File  (---)   C:\Users\Fred\code\tretton37Reporter\web\bower_components\angular\angular.js
    584: File  (---)   C:\Users\Fred\code\tretton37Reporter\web\bower_components\angular-route\angular-route.js
    ------------------------------------------------------------------------------

The suave application in question looks like this:

    ﻿open Suave
    open Suave.Http
    open Suave.Types
    open Suave.Http.Applicatives
    open Suave.Http.Files
    open Suave.Http.Successful
    open Suave.Web

    let appDir = "../../../web/"

    let serveStaticFile filename =
        sprintf "%s%s" appDir filename
        |> file

    let serveStaticFileIfFileExists filename =
        if System.IO.File.Exists(appDir + filename) then
            serveStaticFile filename
        else
            serveStaticFile "index.html"

    let app =
        choose [
            GET >>= choose [
                path "/" >>= serveStaticFile "index.html"
                pathScan "/%s" serveStaticFileIfFileExists
            ]
        ]

    [<EntryPoint>]
    let main argv =
        printfn "Current working directory: %s" System.Environment.CurrentDirectory
        startWebServer defaultConfig app
        0

**Comment by ademar** [comment]
I've pushed v0.30.1 to nuget that includes the above change 5f4d18aac7fdc4179388789ac1753bcdc0d38f55; do you want to give it a try and see if it solves the problem ?

**Comment by tpetricek** [comment]
Nice, kudos to @wastaz for looking into this. I'll try this when doing my next FsReveal talk next week :P

**Comment by wastaz** [comment]
I've only done some quick and basic testing, but from what I can see that seems to have fixed the problem! +1 :)
Thanks for the quick fix @ademar
