### ISSUE TITLE
Basic Authentication Docs

### ISSUE THREAD

**Issue by jasonzoladz** [SuaveIO/suave#238]
Would you add a "Basic Authentication" section -- that documents how to use basic authentication with Suave -- to suave.io?  It would round-out the explanation of features.

I'm coming to F# from Haskell and Scala (with no real experience with .Net).  I'd love to (mostly) avoid asp.net if I can.  :)

**Comment by haf** [comment]
Hehe, understandable. We have an example here: https://github.com/SuaveIO/suave/blob/master/examples/Example/Program.fs#L87 (calls to https://github.com/SuaveIO/suave/blob/master/examples/Example/Program.fs#L19)

Is this enough? It's a line of code; the applicative 'fails' when then authentication passes, so that the control flow of the choice continues looking further below.

**Comment by haf** [comment]
Here's a Hawk sample: https://github.com/logibit/logibit.hawk/#usage-suave-example

**Comment by jasonzoladz** [comment]
Thanks!  The Hawk example was exactly what I needed.  I really appreciate it.

(When you make your next update to suave.io, you might consider adding a section on authorization and authentication.)

**Comment by haf** [comment]
I will, there's some docs in the README for Hawk, I hope it's enough to get you started. We would welcome very much help on the docs front -- https://github.com/SuaveIO/suave/tree/gh-pages is where the docs live. If you want, of course. Otherwise, I hope you enjoy the lib/server ;)

**Comment by ImaginaryDevelopment** [comment]
The section on auth at https://suave.io/composing.html is woefully outdated (is my guess). I could not get it to compile, at all. there are no open statements listed that would lead to a solution. 

This worked instead however: 

```
let requiresAuthentication _ =
            choose
                [ GET >=> path "/public" >=> OK (sprintf "Hello anonymous we are in %s" Environment.CurrentDirectory)
                  // access to handlers after this one will require authentication
                  Authentication.authenticateBasic ((=) ("foo", "bar")) <|
                  //GET >=> path "/protected" >=> request (fun x -> OK ("Hello " + (x.userState.["userName"]|> string))) 
                    choose [
                        GET >=> path "/" >=> OK ("Hello authenticated person")
                        GET >=> browseHome //serves file if exists                       
                    ]
                ]
        requiresAuthentication()
        |> startWebServer defaultConfig
```

**Comment by haf** [comment]
@ImaginaryDevelopment Sorry about the outdated docs. Do you think you could PR?

**Comment by ImaginaryDevelopment** [comment]
I think I can

**Comment by ImaginaryDevelopment** [comment]
done https://github.com/SuaveIO/suave/pull/373

**Comment by haf** [comment]
Thanks!
