### ISSUE TITLE
Move all ASP.NET and XSP stuff to a separate project

### ISSUE THREAD

**Issue by dsyme** [SuaveIO/suave#240]
One of the many things I like about Suave is that it's F#-code-straight-to-the-web.  No dependencies, no mental burden from other frameworks.  

In particular Suave is free of any dependency on ASP.NET.  While ASP.NET has many good sides, it also comes with a lot of history and baggage, and each version tends to increase that.  I like the fact that Suave gives a way to approach TCP and HTTP in a mentally freeing way independent of other frameworks. Raw F# + web.

For this reason I'd recommend that we put all Suave + SomeOtherWebFramework into a separate project.  e.g. a project http://github.com/suaveio/Suave.Xsp?  I'd be happy to help with that.

Cheers!
Don

**Comment by haf** [comment]
+1

**Comment by ademar** [comment]
But Suave.Xsp resides in a different project already .. or you meant a different repository ?

These libraries Suave.Xsp, Suave.Razor, etc are delivered in its own DLLs/nugets.

**Comment by dsyme** [comment]
Yes, I meant a separate repo :)

**Comment by haf** [comment]
@dsyme Since it's already a different project and this ticket hasn't moved for a while now, I'm closing it. If you feel strongly about this, let's open a new ticket about extracting all project that have dependencies. I'd be especially interested in getting access to a matrix build infrastructure from the F# foundation so that Suave + dependencies can be tested for all combinations of mono/windows and nuget packages.

**Comment by dsyme** [comment]
To clarify - yes, my request was to move all ASP.NET stuff to a different repository, and keep the Suave repository itself a clean library very free of dependencies on any other web frameworks.

Re matrix build - please send that request to the FSSF board, or perhaps @tpetricek could just take it from here.

**Comment by haf** [comment]
Sorry, but I have to ask; what would be the gain? Will you use the repo to explain the dependencies to beginners in a book? Perhaps if you could give a use-case?

**Comment by dsyme** [comment]
It's just a preference really - to ensure that Suave continues to feel light and simple and free of dependencies on the "big" Microsoft and other frameworks (both in using it, and as a repository for build/test/issues purposes). And ensure that any framework dependencies it picks up are properly isolated and factored out into other repositories.  It's a bit like MBrace.Core (core programming model) v. MBrace.Azure (mapping that to Azure).

But it's entirely up to you, it's just a suggestion, it's been closed so let's move on :)
