### ISSUE TITLE
Validate server-key size on boot

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#248]
Repro: Start the web server with a key that is not 32 bytes long.

Details: This happens at runtime, after starting, serving requests:

<blockquote>
System.Exception: internal error on encryption Choice2Of2 (InvalidKeyLength "key should be 32 bytes but was 30
<blockquote>

**Comment by ademar** [comment]
Have you done any research on this? Very weird bug; I can not see how this can happen.

I have seen this one though, it could be related.

https://ci.appveyor.com/project/AdemarGonzalez/suave/build/1.0.505#L296

**Comment by haf** [comment]
Yes, I know the reason of that - that test has a 1/256 chance of failing, see https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Utils.fs#L59

We should really zero out enough for it to be very unlikely for a range of zeroes to be there, something like zeroing out 5 bytes; 1/256^5 = 1/1 099 511 627 776

**Comment by danieljsummers** [comment]
This bit me the other day in all my cookie adventures.  :)  Would a single-case DU be a good fix?

Something like...
```fsharp
module ServerKey

  type T = ServerKey of byte[]

  let mkRandom = ServerKey (Crypto.generateKey HttpRuntime.ServerKeyLength)

  let mk (key : byte[]) =
    match key.Length with
    | 32 -> ServerKey key
    | len ->
        [some warning about the length being off, and that we're proceeding with a random one]
        mkRandom

  let value (ServerKey sk) = sk
```

**Comment by haf** [comment]
@danieljsummers 

Thanks for looking into this!

 - I think that the DU case isn't really making it less likely that you generate the wrong key; because we can still have the module named `ServerKey` to generate it
 - Docs on how to call `create` (not `mk`) to generate it
 - I think we should throw like is the case now, otherwise you'll get strange errors of the user session resetting any time you reset a particular process, which makes it even harder to debug in a distributed system setting with many replicas of the web frontend – and you've even set a specific key, so "it should be fine" – better then to crash.

**Comment by danieljsummers** [comment]
OK - great.  I'll work on this once I get my session/state documentation done.  I'm guessing the size-check-on-startup would be [go here, as the first line of `startWebServerAsync`](https://github.com/SuaveIO/suave/blob/f0831e3ed00c611f78a04ac30d3a065403470274/src/Suave/Web.fs#L38).
