### ISSUE TITLE
Support international form keys

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#254]
I was wondering what the specs say about i18n forms? Are all form field names uri encoded before post?

I created a small test-case showcasing some of the errors that may crop up with Suave.

**Comment by haf** [comment]
Output:

```

      Ã¶dlan: Choice2Of2 "Couldn't find key 'Ã¶dlan' in NameOptionValueList"
      å°: Choice2Of2 "Couldn't find key 'å°' in NameOptionValueList"
      
```

**Comment by ademar** [comment]
This has been fixed now.
