### ISSUE TITLE
Handling control chars?

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#255]
It seems we have a failing test with a timeout, probably from having the Tcp client do a failwith and then killing itself before responding with Bad Request:

```
GET / returns 200 OK with passed string-Falsifiable, after 95 tests (0 shrinks) (StdGen (1594145699,296010222)):

"xD	!m"

with exception:

Fuchu.AssertException: should finish request in 5000ms

Expected: true

Actual: false
```

The hex for those two chars are `207f`.

I tried adding a unit test, but can't get it to fail. If we can't reproduce this and we've investigated all locations of failwith, we should close this issue.

**Comment by haf** [comment]
Test case failure here https://travis-ci.org/SuaveIO/suave/builds/63298489#L321

**Comment by haf** [comment]
@ademar Any input?

**Comment by ademar** [comment]
I think this bug is obsolete.
