### ISSUE TITLE
[files] files always sent

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#261]
Actual:

![screen shot 2015-06-08 at 00 29 08](https://cloud.githubusercontent.com/assets/193115/8026431/71d21a92-0d75-11e5-934f-7c72033a7afb.png)

![screen shot 2015-06-08 at 00 29 41](https://cloud.githubusercontent.com/assets/193115/8026432/7e4037b4-0d75-11e5-9a5e-8b0bba5f2062.png)

Expected:

![screen shot 2015-06-08 at 00 33 03](https://cloud.githubusercontent.com/assets/193115/8026442/f6327eb2-0d75-11e5-8c12-ca1f4d744983.png)

Sample response headers:

```
< HTTP/1.1 304 Not Modified
< Server: nginx
< Date: Sun, 07 Jun 2015 22:31:56 GMT
< Content-Type: text/html
< Content-Length: 0
< Connection: keep-alive
< Strict-Transport-Security: max-age=15768000
```

So while Content-Length: 0 is returned, it seems it still sends the file.

**Comment by ademar** [comment]
> it seems

Can we get concrete proof of this? the graphic might be incorrect or misleading.  Looking at the code I do not see how such thing could happen.

Note there nginx there in the mix.

**Comment by haf** [comment]
I will have a deeper look; I agree it's strange considering the code.

The wall-time taken to download is there though. I couldn't reproduce w/ curl because it closes the socket if Content-Length = 0.

**Comment by haf** [comment]
One more data point supporting my theory, when enabling proxy caching in the reverse proxy, no contents are sent, but for uncached assets, like styles.css all the contents are sent:

<img width="1408" alt="screen shot 2015-07-17 at 01 04 24" src="https://cloud.githubusercontent.com/assets/193115/8737205/e30c89f4-2c1f-11e5-8dd4-ab91689eceb5.png">
