### ISSUE TITLE
default route handling doesn't work as expected on Azure deployment

### ISSUE THREAD

**Issue by Indy9000** [SuaveIO/suave#269]
Hi guys, 
Default route doesn't seem to work when deployed to Azure. On localhost this serves index.html as expected but not on Azure.

minimal working proj here: https://github.com/Indy9000/suave-test-01
site deployed here: http://suave-test-00.azurewebsites.net/

    let app : WebPart = 
        choose [
           GET >>= choose [ path "/" >>= file "index.html"; browseHome ];
           NOT_FOUND "Found no handlers." 
        ]

**Comment by haf** [comment]
Does this solve your issues? https://github.com/tpetricek/suave-fshome https://github.com/tpetricek/suave-xplat-gettingstarted
