### ISSUE TITLE
Consider embracing structured log messages

### ISSUE THREAD

**Issue by adamchester** [SuaveIO/suave#270]
I thought it's time to start an issue here for discussion. I believe the issue of structured log messages can be separated from structured logging in general.

Here is an example of what structured log messages would enable:
![image](https://cloud.githubusercontent.com/assets/570470/8428572/dab23336-1f62-11e5-9a7f-761f69deb96b.jpg)

Original proposal: https://twitter.com/adamchester/status/608031081351118849
Related discussion: adamchester/MessageTemplates#1
Similar discussion: https://github.com/akkadotnet/akka.net/issues/1045

**Comment by haf** [comment]
Hey, how did it go? I saw you finished a large portion of it?

**Comment by adamchester** [comment]
It's going well, I think :)

I have been working on an F# implementation of "message templates" recently (although this first version is the one to throw away - it's using a slow regex for now while I experiment).

I believe I will need an "optimised" single-file F# module which can simply "format" a structured message as a string. The formatted string can then be consumed by logging sinks that don't have structured message capabilities. This file could be packet-referenced or manually copied into Suave when it's ready.

See here if interested:
https://github.com/adamchester/MessageTemplates/commit/0a724b1698b1d4ce2a05b5d772072a4fd564cb64#diff-dc211eaea9c008fb5ea1f35e3ac024ff

**Comment by haf** [comment]
Looking good =)

**Comment by haf** [comment]
Let's do the discussion in https://github.com/SuaveIO/suave/pull/288 instead.
