### ISSUE TITLE
Possible issue with Random

### ISSUE THREAD

**Issue by xkrt** [SuaveIO/suave#273]
Hi,

https://github.com/SuaveIO/suave/blob/master/src/Suave/Globals.fs#L5

As far I understand `Globals.random` may be used from different threads simultaneously, but System.Random class is not thread safe, see http://blogs.msdn.com/b/pfxteam/archive/2014/10/20/9434171.aspx.

Possible solution:
```fsharp
module ThreadSafeRandom =
    open System
    open System.Threading

    let private seed = ref Environment.TickCount
    let private rnd = new ThreadLocal<Random>(fun () -> Random (Interlocked.Increment seed))

    let next minInclusive maxExclusive =
        rnd.Value.Next(minInclusive, maxExclusive)

    let nextBytes buf =
        rnd.Value.NextBytes(buf)
```

https://github.com/SuaveIO/suave/blob/master/src/Suave/Utils/Crypto.fs#L50
Same possible issue with `Crypto.cryptRandom`, MSDN says it is not thread safe.

**Comment by haf** [comment]
That's true; how about making a PR? Good catch!

For reference, random is used for:

 - generate a request id (multi-threaded)
 - generate the server-key on start (mostly single-threaded)

**Comment by ademar** [comment]
Is it possible to write a thread-safe random generator without locks ?

**Comment by xkrt** [comment]
@ademar as far I understand my solution above without locks. Will send PR a little bit later.

**Comment by ademar** [comment]
AFAIK `Interlocked` still uses locks.

**Comment by ademar** [comment]
Anyhow, please proceed. I  was just wondering if it was mathematically possible to code such a thing without locks.

**Comment by xkrt** [comment]
@ademar well, I cant imagine how it can be anyhow possible without any "atomic read-increment-write" since every thread should get its own unque seed for `Random`.

Anyway `Interlocked.Increment` called only single time on every thread on static `Random` initialization and [MSDN](https://msdn.microsoft.com/en-us/library/sbhbke0y(v=vs.110).aspx) says that `On modern processors, the methods of the Interlocked class can often be implemented by a single instruction` so there should be no any performance problems.

**Comment by ademar** [comment]
@xkrt I see what you mean. Yeah, this is a nice solution. Thanks!
