### ISSUE TITLE
Unable to use SSL with Nuget Suave

### ISSUE THREAD

**Issue by ckpearson** [SuaveIO/suave#280]
I'm adding Suave.openssl via nuget which pulls in suave and all the other usual dependencies.

However, when I try and follow the SSL getting started and spin up an `X509Certificate` I get the following:

> "The type referenced through `OpenSSL.X509.X509Certificate` is defined in an assembly that is not referenced. You must add a reference to `ManagedOpenSsl`

I've had a look around online and I can download the OpenSSL.NET project and dependencies, but a look in the Suave repo seems to show that these are all there, as well as the config needed to pick the right native library based on which OS is running.

So I'm at a bit of a loss how to resolve this.

**Comment by haf** [comment]
You only get the dll for Suave.OpenSSL in the nuget:

<img width="476" alt="screen shot 2015-07-31 at 15 10 40" src="https://cloud.githubusercontent.com/assets/193115/9007929/5b5599e2-3796-11e5-9b3d-31e832b22a90.png">

You need to add ManagedOpenSsl.dll in your bin/ folder on Windows.

**Comment by ckpearson** [comment]
Thanks, what about running on other platforms, how would this roll in with deployment etc? Also, where would I grab the relevant dlls from? Could I just grab them from the Suave repo?

**Comment by haf** [comment]
On other platforms the .so files (linux) and .dylib (OS X) should be looked up from the environment, from the `LD_LIBRARY_PATH` environment variable. On linux you do `apt-get install openssl` or `yum install openssl`. LibreSSL should be ABI compatible though.

The Suave repo doesn't update the version of OpenSSL, so if you grab ours you'll have the old insecure versions in use.

**Comment by ckpearson** [comment]
Ok... so this is a lot more complicated than I assumed! Would be great if there was a tutorial / the SSL section on the website reflected this.

**Comment by ademar** [comment]
This is our mistake, ManagedOpenSsl.dll should be packed with the nuget.

On Fri, Jul 31, 2015 at 9:15 AM, Henrik Feldt <notifications@github.com>
wrote:

> On other platforms the .so files (linux) and .dylib (OS X) should be
> looked up from the environment, from the LD_LIBRARY_PATH environment
> variable. On linux you do apt-get install openssl or yum install openssl.
> LibreSSL should be ABI compatible though.
>
> The Suave repo doesn't update the version of OpenSSL, so if you grab ours
> you'll have the old insecure versions in use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/280#issuecomment-126689147>.
>



-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by ademar** [comment]
For now, you could take the files from here and dump them in your bin folder.

https://github.com/SuaveIO/suave/tree/master/libs

**Comment by ademar** [comment]
yeah caveat emptor, this lib still supports all the old insecure protocols.

**Comment by haf** [comment]
@ademar https://github.com/Albacore/albacore/wiki/nugets_pack https://github.com/Albacore/albacore/blob/master/lib/albacore/nuget_model.rb#L240

**Comment by haf** [comment]
@ckpearson Did this solve your issue? Otherwise, please tell us and we can reopen it.

**Comment by ckpearson** [comment]
Yes thanks, I'm going to work on it without SSL initially and then add it in later to avoid spending too much time on getting it to work :P Thanks for your help.
