### ISSUE TITLE
Consider remove FsPickler dependency

### ISSUE THREAD

**Issue by xkrt** [SuaveIO/suave#282]
Hi,

I always think about Suave as "elegant tiny library with no external dependecies (except f# core and .net itself of course)" and I really, really love that. It is in the spirit of functional programming - compose some libraries to build the application.

Dependency on FsPickler makes some inconvenience for me, I have to write binding redirects. Things becomes more complicated by the fact that FsPickler not backward compitable (depends on specific versions) and I get deserialize errors in parts of my system that unrelated to Suave.

I think dependency on FsPickler - step from "good tiny library" to "framework".

As far I see FsPickler only used in `CookieStateStore` module, maybe you consider add serialize/deserialize funcs to it public interface or extract it in some "interface type" (something like `Suave.Logging.Logger`).

**Comment by ademar** [comment]
I also vote for getting rid of the dependency. I have found these problems myself.

**Comment by haf** [comment]
Sure, go for it. A big plus would be to create a pluggable nuget that you can use to configure Suave with itself with. Like a single entry point: `apply : SuaveConfig -> SuaveConfig` that sets its serialisation and deserialisation functions. =)

**Comment by legomind** [comment]
just wanted to express my interest in this as well

**Comment by xkrt** [comment]
I can do it, if you guys tell me how exactly it should be done

**Comment by haf** [comment]
I think your suggestion of adding cookie serialisation/deserialisation functions to the configuration is a nice idea.

**Comment by haf** [comment]
@xkrt starting work on this now.

**Comment by haf** [comment]
@legomind @xkrt Would you like to test out master and validate the behaviour?

**Comment by xkrt** [comment]
@haf I didnt have any code using cookies, but looking good for me. Single remark - word spelling Seriali**z**er :)

**Comment by haf** [comment]
Spelling: Allow me to say – lol. ;)
