### ISSUE TITLE
formData string-> Choice<string,string> is a bit confusing

### ISSUE THREAD

**Issue by wallymathieu** [SuaveIO/suave#289]
Perhaps it would be clearer to use Some and None?

**Comment by haf** [comment]
The idea is that the second string contains an error message. Unfortunately F# doesn't have a nice type for that, so Choice it is... This allow you to use Choice as a monad as a part of parsers, validators and server-side outcomes without wrapping and unwrapping all the time, as well as without capturing the error variables manually.

**Comment by wallymathieu** [comment]
What kind of error message do you want to serve up? Isn't it only if the key exists in the form or not?

**Comment by haf** [comment]
Yes, exactly.


```
let getFirstOpt (target : NameOptionValueList) (key : string) =
  match target |> List.tryPick (fun (a,b) -> if a.Equals key then b else None) with
  | Some b -> Choice1Of2 b
  | None -> Choice2Of2 (sprintf "Couldn't find key '%s' in NameOptionValueList" key)
```

As opposed to:

```
HTTP/1.1 400 BAD REQUEST
Headers ..

The key was not found in the collection
```

**Comment by wallymathieu** [comment]
Yes, an interesting choice. The api for the library (as I've seen it so far) is quite raw and non magical. Perhaps adding some documentation to the formData property?

**Comment by haf** [comment]
@wallymathieu perhaps that will be your first PR :) We welcome new contributors; if you have any other questions don't hesitate to ask!

**Comment by wastaz** [comment]
Just a suggestion, wouldn't it be clearer to define a result type such as the one in Chessie

    type Result<'TSuccess, 'TMessage> = 
        | Ok of 'TSuccess * 'TMessage list
        | Bad of 'TMessage list

It wouldn't really change the code as such (I mean, you don't even have to have a list of 'TMessage to be honest - one could pretty much just make a copy of the choice type and rename it), though it would make it a bit more obvious than using the ChoiceXOfY?

**Comment by wallymathieu** [comment]
That would clearer :+1:

**Comment by haf** [comment]
Yes, I agree, that's what I meant with that F# should have such a type.

Redefining it in every project is slightly too painful imo, and you can't even depend on it as defined here then without then also depending on suave.

Plus, you'd still have to exit the Result applicative and enter the Choice applicative instead, so you'd still have to wrap.

Can I suggest you file a suggestion at https://fslang.uservoice.com/? We'd like something like https://github.com/elm-lang/core/blob/master/src/Result.elm#L30 in the core language

**Comment by wallymathieu** [comment]
That would be sweet to add to the core library. I've added an [issue](https://github.com/fsharp/fsharp/issues/479) to fsharp. However, it would still make sense to declare this type in suave until we get something like that in the core language.

**Comment by haf** [comment]
Sorry, but I don't agree, for the two reasons I stated in the previous comment.

**Comment by wallymathieu** [comment]
Then file the suggestion on https://fslang.uservoice.com/

**Comment by haf** [comment]
But I'm not suggesting it, you are. I'm happy enough with Choice as it stands right now. I'd much rather get higher kinded types, kinds and cross-assembly inline static method resolution...

Unless there's something new, I'm closing this. If new arguments/ideas emerge we can reopen this issue.

**Comment by wallymathieu** [comment]
Sure! I'll add a suggestion.

**Comment by haf** [comment]
Just to be clear, I do agree with you. It is just that I find choice better than option.

**Comment by cartermp** [comment]
Now that F# 4.1 has the result type (thanks, @wallymathieu!), would y'all be amenable to changing `formData` to use that?

Happy to send a PR; though this will most certainly break people using `formData` today.  Breaking people, even with a major version bump (I assume Suave follows semver) may cause difficulties.  Adding another member or overload is easier, but I'm also not the fondest of stuffing the latest-preferred method onto a type and calling it good.

**Comment by wallymathieu** [comment]
Problem is that it's a lot of breaking changes, question is how @haf want to go forward with it.
