### ISSUE TITLE
Missing OpenSSL examples

### ISSUE THREAD

**Issue by simra** [SuaveIO/suave#291]
Actually a couple open issues with respect to SSL/TLS here:
1. The examples on suave.io are out of date. http://suave.io/bindings.html
2. Per issue #280 the nuget packages are incomplete (for windows).
3. The actual code sample was commented out by @haf in commit #286. Probably for a good reason, but it would be great to get a better understanding of the reason and the overall the state of SSL support.

I'm especially interested in a Windows solution.  Is there some upstream work that needs to be pushed to the SSL library maintainers?

**Comment by haf** [comment]
@simra Thank you for putting together information about the state of SSL.

Anecdotally none of us are using the SSL in production at this state, but it should be working for PoCs. I'm myself waiting until we've got Hasicorp's Vault completely configured with the SSL backend, because I'm using a load balancer in front of the suave-based cluster of nodes.

In summary, this is a good ticket; work that is much needed. =)

**Comment by CumpsD** [comment]
Just to be sure, does Suave right now support SSL?

**Comment by ademar** [comment]
In principle yes, there is a module Suave.OpenSSL; last time I checked it was working but as far as I know nobody is using it and haven't been production tested.

**Comment by CumpsD** [comment]
It seems to be a very confusing thing, the suave docs specify this: `let sslCert = new X509Certificate("suave.pfx","easy");`

Except, there is no such overload in ManagedOpenSsl (which I downloaded from the libs folder in Suave)

I have a pfx file, and I can probably make a regular BCL X509Certificate, but this ManagedOpenSsl thing :(

**Comment by CumpsD** [comment]
Ok, I figured out how to load a PFX with the libraries, if anyone needs: https://github.com/exira/static-mailer/blob/72fdebf37bafc48ea7277ee4a6b2a758df5c3b3d/src/Program.fs#L28-L31

**Comment by CumpsD** [comment]
Now 1.0 is released, it is marketed to support SSL out of the box, instead of the having to include openssl, but the docs still have the old stuff.

How do you use the new SSL implementation? How do I get it to use PFX file?

**Comment by haf** [comment]
@ademar Is the best person to ask about this.

**Comment by ademar** [comment]
See https://github.com/SuaveIO/suave/blob/master/examples/Example/Program.fs#L191

**Comment by CumpsD** [comment]
Thanks, just finished my migration to 1.0 :+1:

**Comment by haf** [comment]
Closing in favour of the managed API of v1.0.
