### ISSUE TITLE
Headers duplication problem

### ISSUE THREAD

**Issue by xkrt** [SuaveIO/suave#293]
Hi, I have following code:

```
Authentication.authenticateBasic (flip List.contains authorizedUsers)
    >>= Writers.setHeader "WWW-Authenticate" "Basic realm=\"my custom message\""
```
And got this response:
```http
HTTP/1.1 401 Unauthorized
Server: Suave/0.30.0.0 (http://suave.io)
Date: Fri, 28 Aug 2015 09:02:45 GMT
WWW-Authenticate: Basic realm="my custom message"
WWW-Authenticate: Basic realm="protected"
Content-Length: 42

No permission -- see authorization schemes
```

As you can see `WWW-Authenticate` duplicated, first - my custom message, second - Suave built in message. I just want override built in message with my custom.

I think reason for this is:
```fsharp
type HttpResult =
  { status  : HttpCode
    headers : (string * string) list
    content : HttpContent
    writePreamble : bool }
```
`headers` have type `(string * string) list`, not `Map<string,string>` (or some Map that preserve order if it important).

**Comment by xkrt** [comment]
Just find http://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
and this http://tools.ietf.org/html/rfc2617#section-4.6

As far as I understand response may have more than one `WWW-Authenticate` header, but with different authentication schemes and user may choose between them.

Ok, I test this with Chrome and it show me my custom message, not Suave built in.

But duplication of other headers may still can be a problem.

**Comment by xkrt** [comment]
My current workaround for prevent `WWW-Authenticate` duplication:
```fsharp
[<AutoOpen>]
module Utils =
    /// remove all headers with specified key
    let unsetHeader key (ctx: Suave.Types.HttpContext) =
        { ctx with response = { ctx.response with headers = List.filter (fst >> (<>) key) ctx.response.headers } }
        |> succeed

Authentication.authenticateBasic (flip List.contains authorizedUsers)
	>>= unsetHeader "WWW-Authenticate"                                 // Authentication.authenticateBasic always set `Basic realm="protected"`
	>>= Writers.setHeader "WWW-Authenticate" (sprintf "Basic realm=\"%s\"" unauthorizedMessage)
	>>= Response.response HTTP_401 [||]
```

**Comment by haf** [comment]
How about a `Writers.putHeader` with overwrite-existing semantics?

**Comment by xkrt** [comment]
@haf it will be great

**Comment by ademar** [comment]
What about the other way around, `setHeader` will override-existing and `putHeader` not ? 

I understand that is breaking but I think there shouldn't be anybody relying in that.

**Comment by xkrt** [comment]
@ademar `addHeader` and `setHeader` clear for me (and xml docs will be useful too)
