### ISSUE TITLE
Having more control in handling of file uploads

### ISSUE THREAD

**Issue by pfgherardini** [SuaveIO/suave#296]
Hi all,

First of all thank you very much for the great work on Suave.

I was wondering if there is (or you are planning on) a way to control how Suave handles file uploads in multipart form data. I've browsed the code in Web.fs and as things stand now Suave will directly save the file on disk and set the path to the tmp file in the HttpRequest object. This seems risky as someone might upload something huge and completely fill up your disk. I have looked at the code and I did not find any way to control this behavior, Is this correct?

Thanks in advance,

Federico

**Comment by ademar** [comment]
Hi Federico,

Yes, you are correct; we need to introduce a max upload size.

I think we will need to add a one or two parameters, `postMaxSize` and `uploadMaxFilesize`,  to the configuration record here https://github.com/SuaveIO/suave/blob/master/src/Suave/Types.fs#L482

 You are welcome to send a PR with this fix if you have the time :)

**Comment by haf** [comment]
Perhaps we should enable Suave to read the files lazyily?

**Comment by haf** [comment]
I'm adding this to the 'Proven parsing' milestone; because I'd like to have Suave be able to do both lazy and eager parsing in a more declarative manner that makes features like this easier to implement.
