### ISSUE TITLE
Monadic structure on WebParts

### ISSUE THREAD

**Issue by tpetricek** [SuaveIO/suave#298]
There is one thing that I find a bit puzzling or unexpected with `WebParts`. I was mainly just curious if I'm missing some motivation here...

Suave uses `>>=` for composing web parts, which is an operator normally used with monads, but `WebPart` is not really a monadic computation. For monads, we'd need to have `WebPart<'T>`. This would probably be something like:

     type WebPart<'T> = HttpContext -> Async<option<'T * HttpContext>>

I guess this would make some things a bit more complex, so I quite like having just `WebPart` (but then using `>>=` is a bit unfortunate - not that I'd have a better operator suggestion though).

The nice thing with `WebPart<'T>` would be that we could avoid the mismatch between `path` and `pathScan`, because `path "/foo"` would be `WebPart<unit>` and `pathScan "/foo/%s"` would be `WebPart<string>`.

Also, if you want to currently write some helper that calculates something and also sets some HTTP headers, you end up writing somewhat ugly code returning `'T * WebPart` (and then re-composing things becomes hard).

I'm not really suggesting a change - mainly just curious what was the original thinking behind this!

**Comment by ademar** [comment]
Hi Tomas, 

Yes, you are correct. `WebPart `is not a monad, and `>>=` is not `bind`, if you go by the signature it is actually a Kleisli arrow.

When I chose the symbol I did not know what I was doing (not that I know better today) and I was trying to make it a monad.

Today, I feel reticent to change the symbol; I think it would only prejudice people with knowledge of category theory and I don't want newbies to get distracted by that.

Still, I like symmetry and correctness; if we can modify the signature in such a way that we get more expressiveness I am open to that.

We perhaps should put a note in the docs clarifying that our `>>=` is not the classical `bind`.

**Comment by ademar** [comment]
We talked before about this before

https://gitter.im/SuaveIO/suave/archives/2015/02/11
https://gitter.im/SuaveIO/suave/archives/2015/02/12

**Comment by ademar** [comment]
Also relevant @panesofglass suggested that (equivalent) signature before https://github.com/SuaveIO/suave/issues/153#issuecomment-70373188

**Comment by tpetricek** [comment]
Thanks for the links! Yeah, I think both designs have advantages & disadvantages - most of the time, the current one works pretty well, actually. Was just curious :) 

I don't think you could call it Kleisli composition (that's an operation on monad). When talking about Suave, I just say that `>>=` composes web parts, which is what it does. My feeling is that sometimes, reading about monads make people try to use them everywhere, even when they're not needed!

(IMO having `WebPart<T>` would be a bit more uniform, but also typically less usable - so I'm happy with the current better usability option)
