### ISSUE TITLE
[bug] evict printf, sprintf, etc from codebase

### ISSUE THREAD

**Issue by ademar** [SuaveIO/suave#300]
These functions are not thread-safe.

**Comment by haf** [comment]
Source?

**Comment by ademar** [comment]
Here,

> "worth noting that printf and family are not thread-safe"

http://fsharpforfunandprofit.com/posts/printf/

I really don't have much in the manner of source but my multithreaded program is crashing all over sprintf and reflection land. Looking at the source code of printf it seems some effort went into make it thread-safe (see https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/printf.fs#L1241) but they don't make guarantees about it anywhere that I can see.

Also it is slow as molasses, for that reason alone I would like to get rid of them.

**Comment by ademar** [comment]
More info, I was only able to run my libuv socket backed for Suave after getting rid of those functions.

**Comment by haf** [comment]
Them not being thread-safe is absolutely bonkers! I'm going to have to rewrite *a lot* of code that's using them!

**Comment by dsyme** [comment]
AFAIK sprintf is entirely thread safe.  

Like most console output, printf can interleave output (it uses calls to System.Console.Out underneath)

**Comment by eiriktsarpalis** [comment]
You can create drop-in replacements for printf/printfn using the following declarations:
```fsharp
let printf fmt = Printf.ksprintf System.Console.Write fmt
let printfn fmt = Printf.ksprintf System.Console.WriteLine fmt
```
The `Console.Write*` methods are thread safe so this work fine.

**Comment by haf** [comment]
I'm not sure this is a real problem... @ademar Can we close this?

**Comment by ademar** [comment]
Yeah the functions are thread-safe all right. Nevertheless some of these `printf`, `sprintf` usages could be replaced for faster expressions. Closing now since it is not that important.
