### ISSUE TITLE
How to implement server-push over websocket in suave?

### ISSUE THREAD

**Issue by vietnt** [SuaveIO/suave#307]
can I write something like this

    let echo (ws: WebSocket) =
        fun ctx -> socket {
            let loop = ref true            
            while !loop do
                let! message = Async.Choose (ws.read()) (inbox.Receive())
                match message with
                | Choice1Of2 (wsMessage) ->
                    match wsMessage with
                    | Ping, _, _ -> do! ws.send Pong [||] true
                    | _ -> ()
                | Choice2Of2 serverMessage -> do! ws.send Text serverMessage true
        }

or do I need 2 seperate socket-loop for concurrent read-write? 

Thank you!

**Comment by ademar** [comment]
I think that should work, with just one loop. 

Not sure if you example type-checks, does it ?

**Comment by vietnt** [comment]
> Not sure if your example type-checks, does it ?
No, AFAIK there isn't an proper implementation of Async.Choose 
Is there a way to implement *Async.Choose* in Suave ? :)

**Comment by ademar** [comment]
OK, I see that is not going to work, `Async.Choose` wouldn't do what we want.

I think the way to do it is, as you said before, with two loops and run them in parallel.

**Comment by vietnt** [comment]
Could you please check the following implementation, is this good?

    let handleWebsocketConnection (ws: WebSocket) =
        fun context -> 
            let loop = ref false
            let inbox = MailboxProcessor.Start (fun inbox -> async {
                let close = ref false
                while not !close do
                    let! op, data, fi = inbox.Receive()
                    let! _ = ws.send op data fi
                    close := op = Close                    
            })

            socket {
                while !loop do
                    let! m = ws.read()
                    match m with
                    | Text,data,true -> () //process incoming message
                    | Ping,_,_ -> 
                        inbox.Post (Pong, [||], true)
                    | Close,_,_ -> 
                        inbox.Post (Close, [||], true)
                        loop := false
                    | _ -> ()
            }

**Comment by ademar** [comment]
Yeah, I think that would work.

**Comment by vietnt** [comment]
Thank you!
