### ISSUE TITLE
Cookies are broken in 0.32

### ISSUE THREAD

**Issue by OlegZee** [SuaveIO/suave#309]
Repro steps:

  1. start examples\Example project.
  1. navigate to http://localhost:8082/session
  1. *NOTICE* the page displays infinite redirection

Redirection happens in the following line:

        match x |> HttpContext.state with
        | None -> Redirection.FOUND "/session" // restarted server without keeping the key; set key manually?

because of state cannot be initialized. The reason is that Suave cannot decode "old" the cookie. Works well with 0.31.2.

**Comment by haf** [comment]
@OlegZee I'll have a look at it...

<img width="267" alt="screen shot 2015-10-13 at 19 19 45" src="https://cloud.githubusercontent.com/assets/193115/10462503/63902482-71df-11e5-91c8-0a9e889c4b11.png">

Works for me who doesn't have a cookie set already.

The comment tells the reason. We've changed the cookie serialiser and you should set a key for your serialiser (both of these will invalidate cookies).

Let me see if I can't provide the app example for this.

**Comment by ademar** [comment]
This happens because the old cookie state was encrypted with a different key. The sample program will generate a new key on every run. 

f you want to read cookies across reboots you need to persist the server key.

**Comment by OlegZee** [comment]
I removed cookie vis F12 tools and it work just once. After restarting server it fails to read the old key (it's ok) but it fails to clean the cookie state too. I'm on it right now.

**Comment by haf** [comment]
I'm doing a fix for this... 1 sec plx

**Comment by OlegZee** [comment]
Cool, just wonder what is happening in there. And sad that I lost a chance to contribute :)

**Comment by haf** [comment]
Currently pushing v0.32.1. Sorry about the bug :)

**Comment by OlegZee** [comment]
Thank you very much! This is unbelievable customer service :)

**Comment by haf** [comment]
@OlegZee  Spread the word! ;)
