### ISSUE TITLE
Simplify file handling

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#310]
As a newbie user, getting started with Suave,
Suave's security thinking, that files need to be firmly rooted and inside a given home directory,
Imposes on my ease of use when writing code. E.g. I can't just say: `Files.file "cute-cat.jpg"` because that path is not rooted.

We should consider how easy it is to get started with cute cats.

If you've used the `Files` module, what's your input?

<img width="617" alt="6 files 1" src="https://cloud.githubusercontent.com/assets/193115/10526668/8a39dd90-738c-11e5-9874-3c035aa8ebb7.png">

**Comment by haf** [comment]
Closing, no input at all.

**Comment by ademar** [comment]
I think the situation here will be clearer once we document the `File` combinators.

**Comment by haf** [comment]
Let's create an issue for that for v1

**Comment by haf** [comment]
Files as #330
