### ISSUE TITLE
Interest in choosing a different operator for >>= ? 

### ISSUE THREAD

**Issue by amcguier** [SuaveIO/suave#311]
I was curious if there'd be any interest in doing a breaking version change to redefine WebPart composition to use a different operator than >>=, or alternatively changing the calling conventions so that >>= works more like a standard monadic bind? 

The current operator is inlined, which prevents the operator from being overloaded, which means if you're doing something like:
http://fsharpforfunandprofit.com/posts/recipe-part2/
you can't introduce the more standard usage of the operator into the namespace as Suave already defines it in an incompatible way.

Just for reference sake, the was some previous discussion of this in:
https://github.com/SuaveIO/suave/issues/298

I'd be glad to help out with making the change, or testing it!

**Comment by haf** [comment]
Redefining is too large a change that will break too much, despite our version number. But we could define an alternative module that exposes different things than now. What do you think of that?

**Comment by amcguier** [comment]
An alternative module would work fine for me. The only trick would be the >>= as defined couldn't leak into the namespace of that module or we'd be back to square one, which might be hard since it's defined in the primary interface file.

To be clear, when I suggested the change, I wasn't thinking of continuing with the >>= operator and redefining it's behavior like as described #298, I was thinking more keeping the behavior the same and choosing another operator for the same operation that didn't have another accepted meaning. A find and replace, if you will.

Either way would work for my use case really. Thanks for the consideration.

**Comment by haf** [comment]
I'm thinking that you could create a module that manually aliases everything from the present module of `>>=` and then just open that instead? And go through all [<AutoOpen>] to ensure they are at least one step under a child module of the module containing `>>=`.

**Comment by haf** [comment]
Do you understand what I mean? You can do a module like:

``` fsharp
module SuaveAltBindindings

let (*>>) = Suave.Http.bind
let never = Suave.Http.never
let ...
```

And then in your code, you never open `Suave.Http` which contains the original operator.

**Comment by amcguier** [comment]
That does make sense. I'll take a look at whipping this up early next week maybe and see how I do.

**Comment by dubiousdavid** [comment]
I would suggest using `>=>` in place of `>>=`, as that is the correct operator, while offering `>>=` in addition, for a time, to give folks time to make the switch in their code.

**Comment by haf** [comment]
Closing in favor of a PR, when it comes.
