### ISSUE TITLE
WebSharper sample appears to no longer work

### ISSUE THREAD

**Issue by panesofglass** [SuaveIO/suave#312]
With the `defaultConfig`, I can get the WebSharper sample to run, but I always see a socket error. When trying the new libuv-based listener, <s>the build</s>it failed. (NOTE: I can no longer remember what happened, but "build" here strikes me as wrong.)

cc: @granicz @Tarmil

**Comment by haf** [comment]
Do you think you could write a unit test for it?

**Comment by panesofglass** [comment]
I'll try to do it on the plane Monday.

**Comment by haf** [comment]
@panesofglass Can you give it a shot with `v0.33.0-libuv.1`, please?

**Comment by haf** [comment]
And you say; 'the build failed'; how can the build be affected by the choice of a CLR class? Could you post your errors?

**Comment by haf** [comment]
Dealing with this in our own sample... Will report back.

**Comment by panesofglass** [comment]
Ah, sorry I never got to this. I have reproduced it using WebSharper's own WebSharper.Suave lib in https://github.com/c4fsharp/c4fsharp. I'll try again later.
