### ISSUE TITLE
suave.libuv (0.33 pre-release) ignore keep-alive ?

### ISSUE THREAD

**Issue by vietnt** [SuaveIO/suave#313]
WeighHttp + Suave.Libuv 0.33 + libuv 1.7.5 (64bit)
OS: Windows 10 Pro

previous versions (Suave 0.32) + WeighHttp run OK

**Comment by haf** [comment]
Could you link us to how to reproduce this? WeighHttp doesn't turn up when googling...

**Comment by vietnt** [comment]
link to [WeigHttp] https://dl.dropboxusercontent.com/u/73053229/WeigHTTP-0.3-Win32.zip

code to reprocedure: 

    [<EntryPoint>]
    let main argv = 
        let cfg = { defaultConfig with tcpServerFactory = LibUvServerFactory(); maxOps = 1000 }
        startWebServer cfg (OK "hello world")
        System.Console.ReadLine() |> ignore
        0

**Comment by haf** [comment]
Thank you. I think it's great that we have people like yourself to test prereleases!

/ping @ademar

**Comment by ademar** [comment]
Keep-alive shouldn't depend on the tcp layer.

On Saturday, 24 October 2015, Henrik Feldt <notifications@github.com> wrote:

> Thank you. I think it's great that we have people like yourself to test
> prereleases!
>
> /ping @ademar <https://github.com/ademar>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/313#issuecomment-150823775>.
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by vietnt** [comment]
more tests, hope it help!

default tcp factory:
- with keep-alive: 13,300 req/sec
- without: 4,900 req/sec

libuv-factory: 
- with keep-alive: 1,700 req/sec 
- without: 1,700 req/sec (same)

**Comment by vietnt** [comment]
Everything seems ok with single-connection (e.g browser), and weigHttp report 99%+ failed requests -> it may **force-close** the connection in every failed requests (99% in this case) -> no diff between keep-alive vs non keep-alive.

I will retry the test with another tool and update the result

**Comment by vietnt** [comment]
ab (apache bench) (os: Windows)

same result for: suave 0.32 | (suave 0.33 - libuv | default tcp)
- with keep-alive: ab hang forever
- without keep-alive: ok

**Comment by haf** [comment]
```
➜  suave git:(master) ✗ ab -k -c 15 -t 20 http://127.0.0.1:8082/hello
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
Completed 20000 requests
Completed 25000 requests
Completed 30000 requests
Completed 35000 requests
Completed 40000 requests
Completed 45000 requests
Completed 50000 requests
Finished 50000 requests


Server Software:        Suave/0.33.0.0
Server Hostname:        127.0.0.1
Server Port:            8082

Document Path:          /hello
Document Length:        11 bytes

Concurrency Level:      15
Time taken for tests:   15.320 seconds
Complete requests:      50000
Failed requests:        0
Keep-Alive requests:    50000
Total transferred:      8900000 bytes
HTML transferred:       550000 bytes
Requests per second:    3263.73 [#/sec] (mean)
Time per request:       4.596 [ms] (mean)
Time per request:       0.306 [ms] (mean, across all concurrent requests)
Transfer rate:          567.33 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     3    5   2.1      4     122
Waiting:        0    1   1.9      1     116
Total:          3    5   2.1      4     122

Percentage of the requests served within a certain time (ms)
  50%      4
  66%      4
  75%      5
  80%      5
  90%      6
  95%      6
  98%      6
  99%      6
 100%    122 (longest request)
```

OS X, Mono, Warn-level logging in Suave.

**Comment by haf** [comment]
Based on just this I'd say congratulations to @ademar for writing the libuv transport =)
