### ISSUE TITLE
Question about Embedded.sendResourceFromDefaultAssembly and Embedded.resourceFromDefaultAssembly

### ISSUE THREAD

**Issue by KevinRansom** [SuaveIO/suave#322]
I'm trying to port suave.dll to the corclr version of the F# compiler, and to run on the coreclr, which is proving to be interesting. A number of F# MVPs have been helping out.

Is Embedded.sendResourceFromDefaultAssembly commonly used.  The reason I ask is that it eventually ends up using  defaultSourceAssembly

Which is defined:
````
    let defaultSourceAssembly =
      /// GetEntryAssembly is currently not available on coreclr, it may be added back eventually.
      /// GetCallingAssembly is fragile and gone for good, it will not be added back.
      if Assembly.GetEntryAssembly() = null
      then Assembly.GetCallingAssembly()
      else Assembly.GetEntryAssembly()
````
neither GetEntryAssembly() or GetCallingAssembly() are available on the coreclr, GetEntryAssembly() may be added back, but GetCallingAssembly() is a bit fragile due to in-lining and the like and so it is likely to not make a return.

I'm not sure there is a good alternative, and it would be better if users used sendResource and resource anyway and explicitly passed the assembly they wanted the resources to come from.

Does that make sense?

Kevin

**Comment by ademar** [comment]
> and explicitly passed the assembly they wanted the resources to come from

Hi Kevin, yes I think that makes sense. I think there aren't many users of this feature and it would be simpler if the user pass the assembly in. So I think we can change that for the better good.

**Comment by KevinRansom** [comment]
Sweet, I will fix it that way.

**Comment by haf** [comment]
I don't think it'll be simpler to pass it in, which is why I have sane defaults, and I'm actually using this feature myself, so I would rather do a conditional compile in this case.

**Comment by haf** [comment]
Thinking a bit more about it; a conditional compile is a terrible thing to do maintenance wise, so sure, remove it, I'll figure out a way.

**Comment by KevinRansom** [comment]
Lol !!! the compiler codebase has about a thousand lifetimes worth of conditional compiles.

**Comment by haf** [comment]
Life is too short for conditional compiles.

**Comment by KevinRansom** [comment]
Okay ... so I have suave.io building, although I needed to move it to project.json for nuget V3 support.

You can check out the code here: https://github.com/KevinRansom/suave

The changes to your code was really quite small.  I will submit a PR when I figure out the nuget stuff.

Kevin

**Comment by ademar** [comment]
Hi Kevin, thanks for doing this. The PR is welcome.

**Comment by haf** [comment]
Yeah, looking forward to this very much! Did some reviewing in the code-base.

**Comment by KevinRansom** [comment]
From the commits you will see that @westleyl @tpetricek @reedcopsey were a big part of getting this done.  And I'm not quite done yet :-(

**Comment by kolektiv** [comment]
Sorry to jump in here :)

What's involved in porting things to the coreclr F# world at the moment? I'd like to look at making sure my libs/frameworks (Aether, Chiron, Hekate, Freya.*, etc.) work too in the long run, but i'm not sure what "getting started" looks like! Was very interested to see that this is happening in some places!

**Comment by haf** [comment]
@KevinRansom Are you saying there *needs* to be a custom .json file, and you need to figure out how to write it correctly?

I wouldn't be against you sending a PR already and we can have this discussion there, pointing to commits, lines, and what-not.

**Comment by KevinRansom** [comment]
In order to get deployment working, I need a nuget v3 project.json file. Integrating that with the build, getting all of the right versions etc … is still tricky.

**Comment by haf** [comment]
I think this question has been answered.
