### ISSUE TITLE
Socket.Disconnect(true) and coreclr

### ISSUE THREAD

**Issue by KevinRansom** [SuaveIO/suave#323]
While porting suave to coreclr, I encountered the public API:

[CompilationMapping(SourceConstructFlags.Module)]
public static class Tcp
{
      public static void closeSocket(Socket s)

This API is implemented using:
````
/// Disconnect a socket for reuse
let closeSocket (s : Socket) =
  try
    if s <> null then
      if s.Connected || s.IsBound then 
        s.Disconnect true
  with _ -> ()
````
CoreClr does not have an implementation for Disconnect(true) [https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs)

The best it has is Dispose.  The name of your API doesn't really imply re-use, but it may well be that users are dependent on this implementation detail.  Also your comment advertises the re-use behavior.  
We have two choices:
1.  Modify the semantics to dis-allow re-use on the coreclr
2. Lobby the coreclr team to implement Disconnect.  My personal preference is to disallow re-use.  Semantics based on implementation details are tricky when moving cross-platform.

Please advise of your preference.

Kevin

**Comment by ademar** [comment]
Actually you can delete `closeSocket` and `shutdownSocket`; they are not been used.

**Comment by KevinRansom** [comment]
even nicerer, however, they are public apis on suave.dll though so in theory someone else can use them right?.

**Comment by haf** [comment]
That is another TODO for v1; go through and remove all public APIs that should not be there. There's a batch of them in the utils projects as well as the TCP code.

**Comment by haf** [comment]
Closing in favour of https://github.com/SuaveIO/suave/pull/334
