### ISSUE TITLE
Throw if port is already in use on server start

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#329]
It looks like they've hanged. Quite annoying for dev life.

**Comment by philsquared** [comment]
I'm presuming this is the same issue: I'm seeing startWebService just return if the port is taken - previously would throw an exception (behaviour I'm relying on so I can try the next port in a range).
Is that a deliberate change?

**Comment by haf** [comment]
No, it's a change that may have come with the new socket layer.

**Comment by ademar** [comment]
Yeah, what Henrik said.

I have been thinking of introducing dynamic ports; like:

```
type Port = Fixed of uint16 | Range of (uint16 * uint16)
```

What do you guys think about that?

**Comment by haf** [comment]
Functionality-wise very positive. If we can make it so that it continues to be easy to pass the value to the configuration, then that's also important.

**Comment by philsquared** [comment]
@ademar's proposal suits my usage.
Regarding the current change in behaviour, though, is this considered a regression? Is it being tracked somewhere else? Should I raise a separate issue - or is this the most appropriate place?

**Comment by haf** [comment]
I created this issue to track it; it's a direct outcome. I didn't consider it a regression when I created the issue because we've never promised anything about exceptions being thrown from these methods. If you'd be interested in getting your feet wet, it would be interesting/fun to have a discussion with you over a PR (unless @ademar has already started work on it).

**Comment by philsquared** [comment]
That's a fair point regarding nothing being promised (so *that's* why I find it so hard to find anything documented ;-) ).
Personally I'm not so concerned how it's expressed (exceptions/ return values/ callback/ whatever) but I do find it essential to know that the port could not be bound to. Even if a port range could be passed I need to be able to communicate what's going on to other layers. Perhaps the facility was there "by accident" before - but I hope you agree it is valuable?

I could have a stab at a PR but the only times I've looked into the Suave.IO source so far have been to track down some other undocumented behaviour.

**Comment by haf** [comment]
@philsquared I think it's very valuable, and I think you should go for it! Send us a PR and we'll work together to get it merged!

**Comment by haf** [comment]
I'm creating a new issue for port randomisation/intervals, which you can work on. I've fixed the annoying part of this issue; tests seemingly hanging now.
