### ISSUE TITLE
Websocket Broadcasting with events

### ISSUE THREAD

**Issue by flotrek** [SuaveIO/suave#337]
Hello,

I have been trying to broadcast data to websocket clients with the following code without success. Do you have any advice on how to implement a broadcasting mechanism with Suave.Websocket ?

            let msgEvent = new Event<byte[]>()
            let published = msgEvent.Publish

            let echo (webSocket : WebSocket) =
              fun cx -> 
                published.Add(fun data-> let _ = webSocket.send Text data true
                                         ())
                socket { 
                let loop = ref true

                while !loop do
                  let! msg = webSocket.read()      
                  match msg with
                  | (Text, data, true) ->
                    let str = UTF8.toString data
                    msgEvent.Trigger(data)        
                  | (Ping, _, _) ->
                    do! webSocket.send Pong [||] true
                  | (Close, _, _) ->
                    do! webSocket.send Close [||] true
                    loop := false
                  | _ -> () 
 
              }

**Comment by ademar** [comment]
You could run two async loops side by side, in one of them use Async.AwaitEvent. 

Similar patter here http://stackoverflow.com/a/33040460/48401

**Comment by flotrek** [comment]
Thanks. I tried the following code. The event is well triggered and caught in the second loop, but still nothing is sent to the web socket ( the ws.send doesn't seem do send anything). Am i missing something ?

    let broadCast = new Event<byte[]>()
    let broadCasted = broadCast.Publish

    let handleWebsocketConnection (ws: WebSocket) =
        let notifyLoop = async { 
          while true do 
            let! msg = Async.AwaitEvent broadCasted
            let _ =  ws.send Text msg    // do! ws.send Text msg throw an error !?
            ()}
        let cts = new CancellationTokenSource()
        Async.Start(notifyLoop, cts.Token)

        fun context -> 
            socket {
              let loop = ref true
              while !loop do
                let! m = ws.read()
                match m with
                | Text,data,true ->  broadCast.Trigger(data)             
                | Ping,_,_ ->   ()
                | Close,_,_ ->  loop := false
                | _ -> ()
              }

**Comment by ademar** [comment]
On the notify loop you should do:

`let! _ =  ws.send Text msg`

Your code above is missing the !

**Comment by flotrek** [comment]
Just adding the ! to my example gives me a "No overload match for method Bind".
With the example found in the other thread, I came up with a working solution, but that looks heavy to me. Do you see anything better than that ?

    type broadcastMessage =
      | Subscribe of MailboxProcessor<Opcode * byte[] * bool>
      | Unsubscribe of MailboxProcessor<Opcode * byte[] * bool>
      | Broadcast of byte[]

     let broadcastAgent = MailboxProcessor<broadcastMessage>.Start (fun inbox -> 
        let rec loop subscribers = async {
                                        let! msg = inbox.Receive()
                                        match msg with
                                        | Subscribe(mailbox) -> do! loop (mailbox::subscribers)
                                        | Unsubscribe(mailbox) -> do! loop (subscribers |> List.filter(fun x -> not (x=mailbox)))
                                        | Broadcast(data) ->    subscribers |> List.iter(fun x-> x.Post(Text,data,true))
                                                                Console.WriteLine "Broadcasting??"
                                                                do! loop subscribers
                                    }
        loop List.empty)

     let handleWebsocketConnection (ws: WebSocket) =
        fun context -> 
            let loop = ref true
            let inbox = MailboxProcessor.Start (fun inbox -> async {
                let close = ref false
                while not !close do
                    let! op,data,fi = inbox.Receive()
                    let! _ = ws.send op data fi
                    close := op = Close                    
            })
            broadcastAgent.Post(Subscribe(inbox))
            socket {
                while !loop do
                    let! m = ws.read()
                    match m with
                    | Text,data,true ->  broadcastAgent.Post(Broadcast(data))                 
                    | Ping,_,_ -> 
                        inbox.Post (Pong, [||], true)
                    | Close,_,_ -> 
                        inbox.Post (Close, [||], true)
                        loop := false
                    | _ -> ()
            }

That would be great to have a comprehensible example of Broadcasting in suave, like a simple chat.

**Comment by ademar** [comment]
Yeah that is too heavy. The following works for me:

```
let notifyLoop = async { 
      while true do 
        let! msg = Async.AwaitEvent broadCasted
        let! a =  webSocket.send Text msg false
        return ()
        }
```
Note that your usage of `send` above was missing a boolean parameter.

**Comment by flotrek** [comment]
Brillant ! working like a charm.
Thank you.
