### ISSUE TITLE
Using Suave.LibUv in a c# project

### ISSUE THREAD

**Issue by rezakhanmirzaee** [SuaveIO/suave#343]
In the documentation there is an example in F# that tells us how config Suave to use libuv like this :
let cfg = { defaultConfig with tcpServerFactory = LibUvServerFactory() }
I want to config it in a c# project but tcpServerFactory is a read only property.Is there any way to use it in c# ?

**Comment by ademar** [comment]
@haf what can we do here?

**Comment by haf** [comment]
We can do something like this easily:

``` csharp
var cfg = Web.DefaultConfig.With(x => x.TcpServerFactory, new LibUv.ServerFactory())
```

A bit of https://stackoverflow.com/questions/18151969/can-we-get-access-to-the-f-copy-and-update-feature-from-c for the With, and a bit of `CompiledName` for the properties.

**Comment by ademar** [comment]
A fix for this have been committed to master.
