### ISSUE TITLE
Suave is not building on linux

### ISSUE THREAD

**Issue by azumikav** [SuaveIO/suave#345]
```
Errors:

/home/azumi/.sources/suave/src/Suave.sln (default targets) ->
(Build target) ->
/home/azumi/.sources/suave/src/Suave/Suave.fsproj (default targets) ->

	/home/azumi/.sources/suave/src/Suave/Suave.fsproj: error : Target named 'Build' not found in the project.

/home/azumi/.sources/suave/src/Suave.sln (default targets) ->
(Build target) ->

	/home/azumi/.sources/suave/examples/TopshelfService/TopshelfService.fsproj: error : /home/azumi/.sources/suave/examples/TopshelfService/TopshelfService.fsproj: The required attribute "Project" in Import is empty

	 7 Warning(s)
	 2 Error(s)
```
```
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
```
this seems related to this http://stackoverflow.com/questions/21998962/building-vs2013-f-project-on-heroku-fails-with-the-required-attribute-project since it works if you replace the `Choose` block in every project file.

**Comment by haf** [comment]
Please post the version of any mono/mono-complete/fsharp packages you may have as well as the command sequence you do for building.

**Comment by kavafis** [comment]
I'm build with just `build.sh`
I'm using openSUSE-Leap 42.1
fsharp-4.0.0.3-1.8
mono-complete-4.2.1.102-0.xamarin.1

**Comment by haf** [comment]
Sorry, I haven't had time (or have time) to try this; could you PR a Dockerfile to master that showcases it to make it easier for us to reproduce it? It would be very welcome.
