### ISSUE TITLE
bufferSize and maxOps explanation

### ISSUE THREAD

**Issue by xkrt** [SuaveIO/suave#348]
Hi,
https://twitter.com/ad3mar/status/673370235714473984

I'm trying to use Suave for real production service in my company and faced this problem too. I believe that it is necessary to add to documentation explanation of `bufferSize` and `maxOps` configurations.

What values should I set?
On which values they depend?
What restrictions they impose? (preallocatted memory size?)

Anyway, System.InvalidOperationException should not occur in runtime regardless to `bufferSize` and `maxOps`.

**Comment by haf** [comment]
I agree. Preferable would be to have an auto-growing buffer, perhaps?

**Comment by xkrt** [comment]
@haf yes, I think it will be awesome, and maybe auto-reducing logic is needed too (like Thread Pool). But I'm afraid this may be long task and if so - can you shed a light on current parameters?

**Comment by haf** [comment]
Yes, it's pre-allocated and supports something like 100 concurrent connections by default (small transfers). Each connection takes a few buffers for itself. They are handed back afterwards. You can configure another number than 100 by setting maxOps to another value. I don't think you need to change buffer size, it's fairly standard. You could possibly double it.

If you have a web server that's only Suave you can alter these two to suit how much memory (concurrent connections) Suave should take versus how much your app needs.

**Comment by haf** [comment]
The docs are now markdown and editable through PR here: https://github.com/SuaveIO/suave/tree/master/docs

**Comment by ademar** [comment]
This is not as important anymore as we auto-grow the buffer pool.
