### ISSUE TITLE
[WebSocket] Sub-protocols not supported

### ISSUE THREAD

**Issue by jhugard** [SuaveIO/suave#355]
Suave.WebSocket.handShake does not appear to support sub-protocol negotiation ([See RFC 6455 1.9](http://tools.ietf.org/html/rfc6455#page-12)).

Something like the following _might_ work (have not tested); however, IMHO this is a feature missing for WebSocket compliance.  Also, setting the reply header before calling handShake feels rather brittle.

``` F#
let subprotocol subprotocol continuation (ctx : HttpContext) = async {
    let swsp = "sec-websocket-protocol"
    let r = ctx.request
    match r.header swsp with
    // Is it the supported sub-protocol?
    | Choice1Of2 str when str.Contains subprotocol ->
        // Yes, make sure the response has that subprotocol
        let! ctx' = Writers.addHeader swsp subprotocol ctx
        match ctx' with
        | Some ctx'' ->
            // Do the handshake
            return! handShake continuation ctx''
        | _ ->
            return None
    | _ ->
        return None
    }


let app =
    choose [
        path "/api/echo"
            >=> subprotocol "test" echo
        GET >=> choose [
            path "/" >=> OK "Hello!"
            ]
        NOT_FOUND "Found no handlers."
        ]

```

**Comment by ademar** [comment]
> setting the reply header before calling handShake feels rather brittle

I agree it feels out of place there.  

Perhaps we may introduce a new combinator `hadShakeWithSubprotocol` ?

**Comment by jhugard** [comment]
+1
Use case is to support multiple protocols, each with either their own websocket handler or a shared parameterized handler.

**Comment by jhugard** [comment]
Still learning how to think functionally... As a design question (if you have time), why does handShake take a continuation, rather than returning an Async<WebSocket option>?

**Comment by ademar** [comment]
@jhugard I think because then it wouldn't be a `WebPart` and it wouldn't compose with `choose` and the other combinators.

**Comment by ademar** [comment]
So I'm thinking that `handShakeWithSubprotocols` should take a list of sub-protocols and then we can add a property `Subprotocol` of type `string option` to class `WebSocket` so people can devise different strategies based on its value inside the continuation. What do you think of that?

**Comment by jhugard** [comment]
Sounds like that'd work just fine: caller can either handle different protocols within one continuation, or chain individual protocols with independent handlers.  Nice.

**Comment by jhugard** [comment]
Consider also building a ws client, for both unit testing and for connecting to other services.
