### ISSUE TITLE
IIS

### ISSUE THREAD

**Issue by tforkmann** [SuaveIO/suave#356]
Hi there,

is it possible to use IIS with suave?
I'm pretty new in the F# so I would be very thankful for some help.

Thanks in advance!

**Comment by ademar** [comment]
Suave is a stand-alone web server on itself - so no, there is not way of using Suave within IIS.

**Comment by tforkmann** [comment]
Ok, thanks for the info.

**Comment by kolektiv** [comment]
If you really want to write in Suave though, but need to use IIS for other reasons as the outward facing server, you could run Suave locally and use IIS to proxy some or all traffic to the Suave server. That may still work out a nicer experience if your two choices are Suave or something like WebApi!

**Comment by haf** [comment]
And you could probably do a fair amount of work and implement the socket workflow but against the respnose stream in IIS's requests... There's a pushed branched to this repo that starts that work: https://github.com/SuaveIO/suave/tree/feature/IIS-hosting
