### ISSUE TITLE
HTTP request headers search in lower case

### ISSUE THREAD

**Issue by kos59125** [SuaveIO/suave#370]
Request headers are stored in lower case while `HttpRequest.header` function doesn't take care of letter case. If I search a header by string in upper case, it always falls into `Choice2Of2`.

An illustrating code is the following:

```fsharp
match req.header "X-Forwarded-For" with
| Choice1Of2 value -> // never
| Choice2Of2 error -> // always

match req.header "x-forwarded-for" with
| Choice1Of2 value -> // possible
| Choice2Of2 error -> // possible
```

It seems better if the argument of `req.header` is forced to be lower case in the `header` function rather than in user codes.

**Comment by haf** [comment]
I'd say this is a breaking change, but not a big one... What do you think @ademar ? v1 or v2?

**Comment by haf** [comment]
@kos59125 This would be a good PR.

**Comment by ademar** [comment]
Yeah actually surprised it was not already like that.

On Wednesday, 6 January 2016, Henrik Feldt <notifications@github.com> wrote:

> @kos59125 <https://github.com/kos59125> This would be a good PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/370#issuecomment-169374581>.
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar
