### ISSUE TITLE
PathRegex for woff2 font files is not matched

### ISSUE THREAD

**Issue by Dzoukr** [SuaveIO/suave#375]
I got routes defined like this:

    choose [
        ... (omited)
        pathRegex "(.*)\.(css|js|png|otf|eot|svg|ttf|woff|woff2|ico|xml|json)" >=> Files.browseHome
        pathRegex "(.*)" >=> Pages.error404
    ]

Every static file is successfully matched, but not files with extension long 5+ chars (woff2, etc...). Unfortunately, WOFF2 is quite common font file extension in these days.

Thanks

**Comment by ademar** [comment]
woff2 is not listed in the default mime map; so you will need to add it. See https://suave.io/files.html

**Comment by Dzoukr** [comment]
Oh, my fault. Thanks @ademar for the help - closing issue now.

**Comment by haf** [comment]
If you want, woff2 could be added to list of defaults

**Comment by Dzoukr** [comment]
Well, I was actually thinking about making pull request for this, but AFAIK woff2 specification is still in draft. On the other hand, I would not expect extension to changed + it is widely used across many UI frameworks (e.g. Bootstrap) so adding this would make it easier to use. It is your call guys, but I really appreciate your lightning fast communication and taking care! Thanks again!
