### ISSUE TITLE
Bytes.transferBounded will transfer less than requested

### ISSUE THREAD

**Issue by rmunn** [SuaveIO/suave#384]
Unless I'm very much mistaken, there's a bug in [`Bytes.transferBounded`](https://github.com/SuaveIO/suave/blob/master/src/Suave/Utils/Bytes.fs#L53-L64) that will sometimes cause it to transfer less than the maximum number of requested bytes, even if the input source could have supplied more. Here's `transferBounded` as it is now:

```fsharp
  let transferBounded (toStream : Stream) (from : Stream) len =
    let bufSize = 0x2000
    let buf = Array.zeroCreate<byte> bufSize
    let rec doBlock left = async {
      let! read = from.AsyncRead(buf, 0, Math.Min(bufSize, left))
      if read <= 0 || left - read = 0 then
        do! toStream.FlushAsync()
        return ()
      else
        do! toStream.AsyncWrite(buf, 0, read)
        return! doBlock (left - read) }
    doBlock len
```

I believe the `left - read` check is in the wrong place. As it is now, if `len` is, say, 1024 bytes, the `from.AsyncRead` is probably going to read the entire 1 KiB and return it. So `read` will be 1024, `left - read` will be 0, and the "to" stream will be flushed without any data having been written. Or if `len` was 9216 (8192 + 1024), the first 8 KiB will be written to the "to" stream, but the remaining 1024 bytes won't make it.

I suggest moving the `left - read = 0` check further down:

```fsharp
  let transferBounded (toStream : Stream) (from : Stream) len =
    let bufSize = 0x2000
    let buf = Array.zeroCreate<byte> bufSize
    let rec doBlock left = async {
      let! read = from.AsyncRead(buf, 0, Math.Min(bufSize, left))
      if read <= 0 then
        do! toStream.FlushAsync()
        return ()
      else
        do! toStream.AsyncWrite(buf, 0, read)
        if left - read <= 0 then
          do! toStream.FlushAsync()
          return ()
        else
          return! doBlock (left - read) }
    doBlock len
```

This duplicates the `toStream.FlushAsync()` call, which is a little ugly, but it avoids making an unnecessary `from.AsyncRead(buf, 0, 0)` call. However, if asking `AsyncRead` for 0 bytes is cheap and not worth worrying about, the above could be simplified down to:

```fsharp
  let transferBounded (toStream : Stream) (from : Stream) len =
    let bufSize = 0x2000
    let buf = Array.zeroCreate<byte> bufSize
    let rec doBlock left = async {
      let! read = from.AsyncRead(buf, 0, Math.Min(bufSize, left))
      if read <= 0 then
        do! toStream.FlushAsync()
        return ()
      else
        do! toStream.AsyncWrite(buf, 0, read)
        return! doBlock (left - read) }
    doBlock len
```

which is, quite simply, removing the `left - read = 0` check entirely.

Either way this is fixed, this should sent up to `len` bytes to the output stream, rather than "the smallest multiple of `bufSize` that is no greater than `len`" bytes.

Note that I haven't yet tested this, just read the code and noticed what looks like a bug. If I test this and find out that I'm wrong and `transferBounded` *does* transfer the entire `len` bytes even when `len` is not a multiple of `bufSize`, I'll come back and close the issue.

**Comment by rmunn** [comment]
The same thing happens in `AsyncSocket.transferStreamBounded`:

```fsharp
let transferStreamBounded (toStream : Connection) (from : Stream) len =
  let bufSize = 0x2000
  let buf = Array.zeroCreate<byte> bufSize
  let rec doBlock left = socket {
    let! read = SocketOp.ofAsync <| from.AsyncRead(buf, 0, Math.Min(bufSize, left))
    if read <= 0 || left - read = 0 then
      return ()
    else
      do! send toStream (new ArraySegment<_>(buf,0,read))
      return! doBlock (left - read) }
  doBlock len
```

On the last pass, if there are 1024 bytes left in the bound and 1024 bytes are read, the `toStream` will never receive those final 1024 bytes. Same suggested fix: move the `left - read = 0` check to a point *after* having written to the `toStream`, or else get rid of it (which will cause a final pass through the loop with a 0-byte limit).

**Comment by ademar** [comment]
> just read the code and noticed what looks like a bug

Nice catch and nice solution, thanks!

These functions are not been used so I think I will just remove them.

**Comment by haf** [comment]
Sounds like a good plan
