### ISSUE TITLE
TryGetValue on DeltaDictonary does not behave as expected

### ISSUE THREAD

**Issue by kolektiv** [SuaveIO/suave#385]
See https://github.com/freya-fs/freya.examples/issues/4 for some analysis and a potential fix. The ref value with the current implementation always seems to end up as null, regardless of the actual value in the dictionary when doing TryGetValue. This may be some obscure F# collections bug. A potential fix is given in the linked issue...

**Comment by kjnilsson** [comment]
for completeness here is a likely fix keeping the original structure.

This line:
https://github.com/SuaveIO/suave/blob/dc816de9c7830a8ebcd48ecd4553976537ceecc3/src/Suave/Owin.fs#L407

Should be:
member x.TryGetValue (key, [<Out>] res : byref<string[]>) = (x.Delta :> IDictionary<_, _>).TryGetValue(OwinKey key, &res)

**Comment by haf** [comment]
Released v1.1.1 with a fix for this.

**Comment by kolektiv** [comment]
Confirmed that this fixes the particular issue seen in Freya :smile: Thanks! (I've discovered another one, but am assuming that's a Freya one for now...)
