### ISSUE TITLE
OWIN Dictionary TryGetValue only works for known keys?

### ISSUE THREAD

**Issue by kolektiv** [SuaveIO/suave#387]
It seems from this, at first sight, that https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L712-L717 means that TryGetValue will only return true and a value if the key was in a pre-existing set of keys. This means: 

```fsharp
dict.["someKey"] <- "hello"

let hello = dict.["someKey"]

// hello = "hello"

let maybeHello =
    match dict.TryGetValue "someKey" with
    | true, v -> Some v
    | _ -> None

// maybeHello = None (!)
```

Freya adds some values in to the OWIN dictionary as it processes requests, but given this, it can't get them out again using TryGetValue (which is how the relevant Freya optic for environment dictionaries works)!

Is this intended behaviour? I would expect that the OWIN dictionary would, to external consumers, act like a normal dictionary...

**Comment by panesofglass** [comment]
@kolektiv an OWIN dictionary _should_ behave like a `Dictionary<string, object>` with `StringComparison.OrdinalIgnoreCase` applied to key comparisons.

**Comment by panesofglass** [comment]
@haf is there a problem using `owinRW` for everything? Why do you need the `owinKeys` `Set`? Is that just an optimization?

**Comment by panesofglass** [comment]
@haf @kolektiv I'm adding tests for this right now and will push a PR soon.

**Comment by panesofglass** [comment]
Looks like the `state` is not used for `Keys`, `ContainsKey`, or `TryGetValue`, just the `owinKeys` and `owinRW` snapshots taken when the `OwinDictionary` instance was created.

**Comment by haf** [comment]
Ah I haven't seen this issue. Thanks for the tests @panesofglass

**Comment by Andrew-Webb** [comment]
@kolektiv "Freya adds some values in to the OWIN dictionary as it processes requests"

The downside to this is that the following (from the Freya docs) doesn't cause any kind of complaint:-

    state.Environment.["owin.RepsonseReasonPhrase"] <- "Awesome"

:bowtie:

Incidentally, even when I corrected the spelling of `Repsonse`, Suave still didn't pass back "Awesome" to the client.  Is this known about, do you know?  This has come after my very first attempt to work with Freya - hosted on Suave - a success!  -- except for the reason phrase business.

**Comment by ademar** [comment]
at the moment Suave wont let you change the reason phrase see https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L540

**Comment by Andrew-Webb** [comment]
@ademar - thank you for the quick response.  Are there plans to support this?  My REST APIs tend to use the reason phrase quite heavily - e.g.

[http://developer.statpro.com/Revolution/WebApi/Intro#statusCodes](http://developer.statpro.com/Revolution/WebApi/Intro#statusCodes)

**Comment by ademar** [comment]
I would be in favour of allowing to change it cc @haf @panesofglass what’s the consensus on this ?

**Comment by kolektiv** [comment]
This problem is actually worse than just reason phrases not working on Suave - it effectively makes quite a lot of Freya not work on Suave! For example, the router adds data to a new key in the environment so it can be accessed later (values in matched routes, etc.) but this silently fails because it's trying to add a "non-whitelisted" key. It's kind of a showstopper for Freya, although hopefully not for long!

**Comment by Andrew-Webb** [comment]
>  My REST APIs tend to use the reason phrase quite heavily

Well, the last time I evaluated this approach was when RFC 2616 was still viable.  In light of [
http://tools.ietf.org/html/rfc7230#section-3.1.2](
http://tools.ietf.org/html/rfc7230#section-3.1.2)

    The reason-phrase element exists for the sole purpose of providing a
    textual description associated with the numeric status code, mostly
    out of deference to earlier Internet application protocols that were
    more frequently used with interactive text clients.  A client SHOULD
    ignore the reason-phrase content.

I think will use the response message body from now on.

**Comment by haf** [comment]
I'll try to fix the tests in a few days; or if someone else has some interest in this bug, don't let me beat you to the punch. If you're adding new keys, we should probably just ave them in `userState`.

I think the reason phrase should be a separate issue, but I wouldn't be against adding support for it.

**Comment by kolektiv** [comment]
I might try and take a look at this in a bit, although that does depend on
whether I get some other current Freya vNext bits working! Probably 50/50.
What was the idea behind the restriction to a known set of keys in the
first place? (It seems like that simply needs ripping out, but I also know
that the people who write Suave are probably smart enough to have had some
reason for doing it to start with... ?)

:smile:

**Comment by haf** [comment]
There's not any particular design reason; the OWIN module was done like this (give or take):

 1. OWIN, eh, sounds fun, let's write a spike to see if it's feasible
 2. Spike proves I can compose the program the way I thought in my head, not as fun anymore
 3. FF 6 months
 4. Someone wants it, I point to spike
 5. FF 1.5 months
 6. Someone else wants it, I point to spike
 7. FF 1 month
 8. Someone compares Suave to another web server and says we don't have OWIN
 9. "Dammit!", I finish spike to level of no known bugs and can run basic OWIN apps

So its very much borne from people wanting it and using it. A minimum viable OWIN, if you wish. It's completely reliant on people like you all in this thread to chime in with issues and maybe even PR. Right now I'm finishing up a bit of backlog in Logary and in F# TV, but as always I merge PRs :).

**Comment by Andrew-Webb** [comment]
> an OWIN dictionary should behave like a Dictionary<string, object> with StringComparison.OrdinalIgnoreCase applied to key comparisons

@panesofglass From my reading of the relevant [section in the spec](http://owin.org/html/spec/owin-1.0.html#3-2-environment), the key comparison should be `Ordinal`.  Only the comparison of the keys in the request / response header dictionaries should be `OrdinalIgnoreCase`.
