### ISSUE TITLE
Custom HTTP status codes

### ISSUE THREAD

**Issue by simendsjo** [SuaveIO/suave#390]
I'm using Suave in an internal application. I would like to use custom statuscodes to indicate some warnings in the application, but unfortunately, Suave only supports standard HTTP status codes. This means I would have to reuse a statuscode to indicate a different condition specific to my application.

Would a PR to allow custom statuscodes be accepted? Or is the stance only to allow these predefined status codes? As Suave is a good fit for microservices that has an HTTP API, I would hope for the former.

**Comment by haf** [comment]
Yes, but not if you change any code that concerns HTTP status codes. Instead, let me point you towards how it could be done nicely. Suave is built in a modular fashion, so if you set your HttpResult to *not* write the [preamble](https://github.com/SuaveIO/suave/blob/master/src/Suave/ParsingAndControl.fs#L403-L459) you can replace it with your own status code.

You can create a combinator that replaced the preamble with a custom HTTP code. That should make your WebPart just a few lines of code, while not removing the totality of functions with HttpCode inputs.

What do you think?
