### ISSUE TITLE
Static files with URL-escaped chars in their names aren't found

### ISSUE THREAD

**Issue by jhorv** [SuaveIO/suave#392]
Say I'm running a WebPart like this:

        let app : WebPart =
            choose [
                Filters.GET >=> choose [ Filters.path "/" >=> Files.file "index.html"; Files.browseHome ]
                RequestErrors.NOT_FOUND "Page not found." 
            ]

This fails for static file/path names containing a URL-escaped character.

Example: requesting `/map 2.jpg` causes the browser to request `/map%202.jpg`, Suave doesn't unescape that when mapping to the file system, and the result is that the static local file is not found.  Renaming the static local files with the proper URL escapes works as expected.

**Comment by haf** [comment]
Fix coming up (see linked issues)!
