### ISSUE TITLE
Some assembly info for Suave.dll would be useful

### ISSUE THREAD

**Issue by Andrew-Webb** [SuaveIO/suave#394]
I see in the `src` that two examples and `Suave.Testing` have assembly info, but I think it would be useful for `Suave.dll` itself to have assembly info too - e.g. at least _one_ version number.

I know that the package has a version number, but sometimes it can be very useful to examine a DLL in a deployed `bin` folder and see at a glance what its file / assembly / product version number is.

I saw a couple of issues pertaining to `AssemblyInfo.fs` files, but didn't really understand them, nor understand why `Suave.dll` would not have one.

**Comment by ademar** [comment]
Suave does have version information. 

The AssemblyInfo file is generated automatically at build time by the Rake script.

**Comment by Andrew-Webb** [comment]
@ademar - I have to disagree.  If I look at the properties for Suave.dll (as pulled from `https://nuget.org/api/v2`) then, on the Details tab, I see no information at all for:-

* File description
* File version
* Product name
* Product version
* Copyright
* Language

Freya.Core.dll (for example) has all these things, except for Copyright.

Re. version, if I use JetBrains dotPeek to look inside Suave.dll, I can see that you have a $AssemblyVersionInfo class... but it's empty.

**Comment by ademar** [comment]
Hum .. you are correct; let me check what's going on here.

**Comment by ademar** [comment]
I have checked that v1.0 have the version information properties set and the build script (still) produce binaries with the correct assembly information.

So I'm guessing we made a mistake when we build the nugets for v1.1.0 and v1.1.1.

**Comment by haf** [comment]
Strange given that I built those with rake too.

**Comment by ademar** [comment]
This is now working correctly in v1.1.3 but in v2.x we are failing to include the assembly information in the netcore binary.
