### ISSUE TITLE
Reason phrase should be settable via OWIN

### ISSUE THREAD

**Issue by Andrew-Webb** [SuaveIO/suave#397]
Arising from discussion in #387 

Although use of the reason phrase is downplayed by [RFC 7230](http://tools.ietf.org/html/rfc7230#section-3.1.2), there seems to be no good reason for not allowing it to be set in Suave via OWIN.

**Comment by kolektiv** [comment]
Although it's not mandatory, as an example, returning 200 Ok and 200 Options is quite common. It's not semantically significant, but it is nice to be able to do!

**Comment by ademar** [comment]
I wrote a fix for this #399
