### ISSUE TITLE
OWIN dictionary keys not compared using Ordinal string comparison

### ISSUE THREAD

**Issue by Andrew-Webb** [SuaveIO/suave#398]
The [OWIN specification](http://owin.org/html/spec/owin-1.0.html) is clear:-

* the keys of the environment IDictionary&lt;string, object&gt; must be compared using `StringComparer.Ordinal` (i.e. non-cultural, case-sensitive)
* the keys of the contained headers IDictionary&lt;string, string[]&gt; must be compared using `StringComparer.OrdinalIgnoreCase` (i.e. non-cultural, case-insensitive)

Suave's OWIN implementation uses case-insensitive comparison (+ equality test) for both types of dictionary, so it's half right and half wrong.

The following illustrates:-

    // Works, but shouldn't...
    let headers = state.Environment.["owin.requestheaders"] :?> IDictionary<string, string[]>

    // Works, and should
    let host = headers.["HOST"]     // the key in the dictionary is actually "host"

**Comment by Andrew-Webb** [comment]
@ademar: Thank you for addressing this issue, as well as #397 and #387 - great work!
I look forward to trying it.

To me it makes sense to create the underlying .NET dictionaries directly, specifying the correct `StringComparer` value in the ctor of these dictionaries.

However, there is a residual use of `StringComparer.OrdinalIgnoreCase` outside of dictionary creation [on this line](https://github.com/SuaveIO/suave/blob/master/src/Suave/Owin.fs#L344).

I don't know for sure - I've just perused the code - but it seems to me that if `mapFindLens` were being used for the headers dictionary then this would make sense, but I believe it's being used for the environment dictionary, in which case maybe `StringComparer.Ordinal` would make more sense?

Just my two cents after a short and cursory "code review".

**Comment by ademar** [comment]
@statpro-awebb thanks! it is fixed now 3d317e92a90c4bdac1e4266795c87763119f0c28

**Comment by panesofglass** [comment]
@Andrew-Webb, wow, as one of the OWIN maintainers, I never realized the environment dictionary keys were `StringComparison.Ordinal`. Thanks for the catch!

Thanks for fixing this, @ademar!
