### ISSUE TITLE
WebParts / HttpMethods naming collision

### ISSUE THREAD

**Issue by daxfohl** [SuaveIO/suave#400]
This is confusing because this compiles:

```
open Suave
open Suave.Filters
open Suave.Operators
open Suave.Successful
let blankServer = GET >=> NO_CONTENT
```

but this doesn't:

```
open Suave.Filters
open Suave.Operators
open Suave.Successful
open Suave
let blankServer = GET >=> NO_CONTENT
```

This could easily frustrate a new user.  I'd posit that actually all these things should be in the core `Suave` module; having them spread out makes things harder to find, makes it more difficult to copy and paste code from tutorials/stackoverflow (which rarely includes the `open` directives) and increases chances of naming collisions.

**Comment by ademar** [comment]
This issue will disappear in the next release. It is a byproduct of trying to stay backward compatible when we introduced the new operators.
