### ISSUE TITLE
Graping strings for all pages out of a webpart

### ISSUE THREAD

**Issue by tforkmann** [SuaveIO/suave#402]
Hi there,

i'm using Suave in a commercial project and I'm loving it.

I just have an issue which is hart for me to solve. You probably know an solution but I can't figure it out.

Here is my issue: 

I'm using links to pass information from page to page. 
For example I grab the login information (username and password) and use it in my internal authentication function:
`pathScan "/login/%s/%s/" (fun (username, password) -> Auth.authSite username password)` 

After successful authentication i want to redirect the client.
I'm able to do it like that:
`pathScan "/login/%s/%s/" (fun (username, password) -> Auth.authSite username password) >=> Redirection.redirect "/welcome/"`

The authSite function looks like that:
`let authSite username password = delay (fun () ->
    let userName = username
    let user = userQuery(userName,password)
    let authData =
        { Username = userName }
    DotLiquid.page "welcome.html" authData)`

Now I still want to use the username (string) for all other pages. 
The problem is that I don't know how to grab the string from the webpart 'delay fun() ->'.
Its seem a bit difficult because the webpart is a asynchon function.

There is probably an solution for that.

Do you have any ideas?

Thanks in advance,

Tim

**Comment by haf** [comment]
You can write it to `userData`, [like here](https://github.com/logibit/Logibit.Hawk/blob/master/src/Logibit.Hawk.Suave/Hawk.fs#L156) to use it in downstream web parts, as long as they are matching (Some XX).

I also save the user id to [a cookie](https://github.com/SuaveIO/suave/blob/master/src/Suave/Authentication.fs#L77).

**Comment by tforkmann** [comment]
Thanks going to try this out!
