### ISSUE TITLE
Owin success and next semantics

### ISSUE THREAD

**Issue by Tarmil** [SuaveIO/suave#410]
There seems to be a discrepancy between Suave and Owin in terms of determining whether a request has been handled or still needs to be worked on. In Owin, one invokes the `next` function to let the next middleware in the chain handle the request. For example, the following is an identity handler, which does nothing and lets the rest of the application handle the request:

```fsharp
let doNothing = OwinMidFunc(fun next -> OwinAppFunc(fun env -> next.Invoke(env)))
```

 However, Suave passes an ignore function as `next` and always considers that the Owin handler has successfully handled the request. This means that the above handler will leave a request hanging indefinitely. For example if you do this:

```fsharp
choose [
  OwinApp.ofMidFunc "/" doNothing
  GET >=> path "/hello" >=> OK "hello get!"
]
```

and request `GET /hello`, instead of receiving "hello get!" as Owin semantics would suggest, the request hangs. This has been a problem with WebSharper applications, as reported [here](https://github.com/intellifactory/websharper.suave/issues/9) and [here](http://websharper.com/question/81291/playing-nicely-with-suave-webpart-choose).

**Comment by haf** [comment]
So what if the "identity handler" actually makes a change, like adding something to the headers that the next web part then would expect to be there? In your example above, the OwinApp.ofMidFunc would not change the HttpRequest at all, even if it wanted to? Should we expect that owin apps that *do* call `next` will have given up their right to make changes to the context?

**Comment by Tarmil** [comment]
I don't think I'm familiar enough with Suave's inner workings to speak authoritatively, but this seems a reasonable compromise. Proper Owin semantics would require applying any changes the middleware has done to the Owin environment back to the context that is passed to subsequent handlers, but I'm not sure this really makes sense within Suave.

**Comment by haf** [comment]
Each web part either succeeds or fails, and if it fails it won't have changed any data for the next web parts (this is the `choose` combinator, but we can probably create a side-effecting combinator to use instead). 

Consider this:

```
OwinApp.ofMidFunc "/" middlewareAuth >=> choose [
  GET >=> path "/a" >=> OK "Yup"
  GET >=> path "/b" >=> OK "Nope"
]
```

In this case the middleware would call `next()` but wouldn't expect the WebPart to fail, because it wants its side-effects visible.

But in this case:

``` fsharp
choose [
  OwinApp.ofMidFunc "/" doNothing
  GET >=> path "/hello" >=> OK "hello get!"
]
```

You probably want the call to `next()` to mean that the Owin WebPart didn't match?

We could make it mean one of these things...

**Comment by Tarmil** [comment]
The "`next()` = no match" case would definitely be sufficient for WebSharper users, and I think most if not all Suave+Owin users. I don't expect many people will want to use Owin middleware to apply side-effects on Suave WebParts. So I think implementing `next()` as a simple fail and mentioning the caveat in the documentation should be enough.

**Comment by haf** [comment]
I'm digging into this issue... The problem if we just fail the web part if next() is called is that you can't have middleware call into an Owin app properly.

It would not be able to apply its changes. Instead, we need to let the API separate the middleware from the app, because that's how Owin is built.

**Comment by ademar** [comment]
This is an interesting problem.  So we will need two combinators, for the different behaviour, is that what you mean ?

**Comment by haf** [comment]
Mid functions:

 - either mutate and call next
 - or mutate and return a new task and don't call next

App functions:

 - mutate

Mid funcs like auth should be able to cancel evaluation by not calling next.

In this case `OwinMid.ofFunc auth >=> OK "Authenticated"`, the mid func has no way of changing control flow. This is a problem.

`OwinMid.ofFunc auth (OK "authed")` would have its `next` be the next web part.

**Comment by panesofglass** [comment]
@haf the `around` appears to fail to handle the 403 case correctly, but perhaps I don't fully understand what `around` is trying to do. In general, a `MidFunc` may call next and pass control or complete the request. I don't think `around` or `control` fully represent this scenario. An `AppFunc` should always complete:

> The application MUST eventually complete the returned Task, or throw an exception.

The challenge is that, in keeping with Katana's soft-404 fallthrough, many `MidFunc` implementations should _really_ be `AppFunc`s, as is the case with the `Sitelet` middleware. In this case the `MidFunc` is doubling as a routing mechanism and `AppFunc`. It's an unfortunate by-product of how we specified things and how Katana apps encourage development. Contrast with the obvious branching provided by Suave.

I think a better default might be to create something that checks for a `next.Invoke` call and returns control to Suave. We did something [similar in Freya](https://github.com/freya-fs/freya/blob/master/src/Freya.Core/Integration.fs#L139-L182).

**Comment by haf** [comment]
@panesofglass "may pass control or complete the request" -> aren't they supposed to be chainable? If we abort their chain anytime they call next, then can you really use middleware that only mutates state with suave?

**Comment by panesofglass** [comment]
@haf you would have to thread the Suave response back through the OWIN middleware chain if the middleware chain was first invoked, yes.

**Comment by ademar** [comment]
I have submitted some changes on #418 which are relevant to this discussion.

As per the spec the only way to know if a middleware has handled the request is if it has written to the response stream.

**Comment by haf** [comment]
Closing with reference to #418 from @ademar – ping us if you want it reopened and there's more to add to the discussion.
