### ISSUE TITLE
is Composing.md out of date?

### ISSUE THREAD

**Issue by theburningmonk** [SuaveIO/suave#411]
I was going through the doc with a colleague to show him how Suave works, and on the 'Composing bigger programs : combinators' page, some of the examples don't work anymore:
- `HttpRequest.query` is type `(string * string option) list` and I'm getting an error saying `(string * string option) list, string' doesn't support the`^^` operator
- I can't find the `Option.ofChoice` utils function anywhere, looks like it used to be in `Utils\YoLo.fs` but that seems to be gone
- I can't find the definition for the `^^` operator either, it's not in the [Operators.fs](https://github.com/SuaveIO/suave/blob/master/src/Suave/Operators.fs)

**Comment by ademar** [comment]
Hi Yan. 

Yes, the documentation is inaccurate; I think we lost some operators (those in particular) in the last release.

We should bring then back in the v2.0 release together with a more robust foundation.

**Comment by danieljsummers** [comment]
FWIW - ^^ is defined in [Suave.Utils.Collections.fs](https://github.com/SuaveIO/suave/blob/master/src/Suave/Utils/Collections.fs)

**Comment by haf** [comment]
Aka the *smiley* operator ^^
