### ISSUE TITLE
Copy of html files in bin folder

### ISSUE THREAD

**Issue by tforkmann** [SuaveIO/suave#412]
Hi there,

right now I'm trying to set up our intranet on a productive system.
After building the webpage with `build.cmd` in my developing system I copy the bin folder to the productive system.

Afterwards I'm using Topshelve to install the suave webserver as a windows service on the productive system. Like this:
`Run WebSite.Service.exe install (in admin mode)`

@forki 's https://github.com/forki/backgroundjobs is an sample project which shows those features.

I'm able to run the suave webserver as a service but the webpage is running into an error because the html files are no getting complied into the bin folder.

Here the error message as an example:

> 
[E] 2016-03-23T07:45:41.8866520Z: request failed [Suave.Web.defaultErrorHandler]
 exn:
System.IO.DirectoryNotFoundException: One part of the path "C:\Users\...\code\WebSite\templates\landing.html" can not be found.
   with System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   with System.IO.FileStream.Init(String path, FileMode mode, FileAccess access,
Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions
options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boole
an useLongPath, Boolean checkHost)
   withSystem.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
 FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
 bFromProxy)
   withSystem.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
 FileShare share)
   with Suave.DotLiquid.loadTemplate@73.Invoke(Unit unitVar) in Z:\ademar\Project
s\suave\src\Suave.DotLiquid\Library.fs:row 74.
   withMicrosoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1
args)
> 

Is there a way to get the html files compiled to the bin folder?
I believe then Suave would be able to find the right html files and the webserver would run smoothly.

Thanks in advance!

Tim

**Comment by ademar** [comment]
> Is there a way to get the html files compiled to the bin folder?

Yes.

In Visual Studio, in the solution explorer right click on the file, go to Properties and set Copy to Output Directory to "Copy if Newer"

**Comment by forki** [comment]
But wouldn't it be better to have it compiled into the service?

**Comment by ademar** [comment]
@forki  Do not know; that is not what he asked.

**Comment by forki** [comment]
I know that tim asked it differently. Your proposed solution will most probably work - but having a single exe for the service would still be beneficial.

**Comment by ademar** [comment]
OK cool then he can use the combinators from Suave.Embedded and set build action for the html files to Embedded resource.

**Comment by tforkmann** [comment]
Thanks,

do you have an example where you used the combinators from Suave.Embedded?

**Comment by ademar** [comment]
Sorry, not much in form of example. They follow the same pattern that the ones in Suave.Files

https://github.com/SuaveIO/suave/blob/master/src/Suave/Combinators.fsi#L1401

**Comment by tforkmann** [comment]
Thank you again.

I used Visual Studio to copy the html files. It worked fine!
