### ISSUE TITLE
Could not load type 'Suave.Web' from assembly 'MyAssembly'

### ISSUE THREAD

**Issue by CodEFouR** [SuaveIO/suave#414]
Hi,
I've setup my `paket.dependencies` as well `paket.references` and run `paket install` so I guess the reference to Suave is working as I saw my `.fsproj` has the reference tag produced correctly. And I tried 
```
open Suave
[<EntryPoint>]
let main _ = 
    startWebServer defaultConfig (Successful.OK "Hello, world!")
    0
```
Then I build the application but it showed me `Could not load type 'Suave.Web' from assembly 'MyAssembly'`. 
However if I did the above in the F# Interactive everything was fine and I could see the web page opened.

**Comment by ademar** [comment]
I suspect this has nothing to do with Suave.

**Comment by ademar** [comment]
To not leave you hanging .. could you share your project so we can take a look ?

**Comment by CodEFouR** [comment]
Thanks for your quick response @ademar and yes your intuition is right, it's not a Suave issue and I got it fixed.

**Comment by AlfranKeith** [comment]
@CodEFouR, could you tell me what the issue was? Trying to follow https://theimowski.gitbooks.io/suave-music-store/content/en/hello_world_from_suave.html and I'm getting that exception during the first step. Thanks.

**Comment by haf** [comment]
It's probably something like your project being compiled with .Net 4.0 rather than .Net 4.5. @AlfranKeith

**Comment by AlfranKeith** [comment]
Yes, something like that. I have it resolved now, just slept on it then it
hit me haha. Thank you.
