### ISSUE TITLE
file "index.html" doesn't find file when running from Docker container

### ISSUE THREAD

**Issue by dustinmoris** [SuaveIO/suave#440]
I noticed that the following code works when I run it from the self hosted console app on Windows, but doesn't when I run it from a Docker container:

```
path "/" >=> file "index.html"
```

In the Docker container I end up on the failed path here: https://github.com/SuaveIO/suave/blob/a2f6d8683fe63613e08ac80d9e8143a4def9f6fc/src/Suave/Combinators.fs#L437

It works both ways when I use `browseFileHome`.

**Comment by haf** [comment]
Most likely you have different working directories in docker versus otherwise. Try the `WORKDIR` stanza in your Dockerfile.

This is very unlikely a bug in Suave, I'm afraid. I'm closing until you provide more information, like a repro dockerfile.

**Comment by dustinmoris** [comment]
I haven't tested it but I think you are right, I didn't set the WORKDIR in my Dockerfile to my app's root folder. Thanks.
