### ISSUE TITLE
Suave 2.0.0-alpha3 doesnt support netstandard (.NET Core)

### ISSUE THREAD

**Issue by enricosada** [SuaveIO/suave#444]
## repro

1. clone https://github.com/SuaveIO/Suave-CoreCLR-sample
2. change Suave version inside project.json from `2.0.0-alpha2` to `2.0.0-alpha3`
3. dotnet restore 

## actual

```
error NU1002: The dependency Suave 2.0.0-alpha3 does not support framework .NETStandard,Version=v1.5
```

## expected

restore successful (exit code 0) and after `dotnet run` the suave sample works

## issue

the nuget package is wrong.

correct: https://www.myget.org/F/enrico-ci/api/v2/package/Suave/2.0.0-alpha2

unzip and check:
- the `lib` folder contains `netstandard1.5`
- the `Suave.nuspec` contains `<group targetFramework=".NETStandard1.5">`

### why

i dont understand why was published like that.
the rakefile should correctly create the packages and merge it.
or by hand:

- `rake nugets` ( or `appveyor`)
- `rake dotnetcli:do_netcorepackage`
- `rake dotnetcli:merge`

@haf was the .net core package manually copied inside the other package?
We can continue in skype to fix it, sry yesterday night i was not avaiable to answer to pr's comment

**Comment by haf** [comment]
I first ran `rake dotnetcli:do_netcorepackage` then `rake nugets` then `rake dotnetcli:merge`. It created a package like the one I published.

**Comment by enricosada** [comment]
1. rake nugets
2. rake dotnetcli:do_netcorepackage
3. rake dotnetcli:merge

**Comment by haf** [comment]
Can't we make dotnetcli:merge depend on the two before?

**Comment by enricosada** [comment]
sure, i'll send a pr. 
i'll add `dotnetcli:merge` as deps of `rake appveyor` otherwise if there are two different rake execution, it's gonna rebuild the base package

**Comment by haf** [comment]
Ok. You could also add `XXXX_quick` without dependencies if you wish. It's useful when trying things out.

**Comment by enricosada** [comment]
it's ok atm, it's possible to have an `-alpha4` ?

**Comment by ademar** [comment]
@enricosada I've just published `alpha4`.

**Comment by enricosada** [comment]
@ademar @haf :+1: 
i tested it on all supported plat (osx/win/docker/ubuntu), and updated the https://github.com/SuaveIO/Suave-CoreCLR-sample repo (docs and code, build is green)

**Comment by enricosada** [comment]
i'll close because `alpha4` is on nuget.org and work
