### ISSUE TITLE
Websocket push and SSL

### ISSUE THREAD

**Issue by zoren** [SuaveIO/suave#453]
I'm having trouble when pushing to websockets through SSL. Pushing to non-SSL works fine. And access to pull resources via SSL works as expected.

The following example extends the echo example to push the current time to the client every second. When I open the insecure websocket I get the time every second as expected. When using the secure websocket I only get one timestamp. Yet the connection remains open.

```fsharp
open Suave
open Suave.Operators
open Suave.Filters
open Suave.Successful
open Suave.Logging
open Suave.Sockets
open Suave.Sockets.Control
open Suave.WebSocket

open System
open System.Threading
open System.Net
open System.Text

let echoTime (webSocket : WebSocket) =
  fun cx ->
    let timeSender =
        async {
          while true do
            let timeString = DateTime.Now.ToString()
            let timeBytes = Encoding.UTF8.GetBytes timeString
            let! res = webSocket.send Text timeBytes true
            Threading.Thread.Sleep(1000)
        }
    let cts = new CancellationTokenSource()
    Async.Start(timeSender, cts.Token)
    socket {
      let loop = ref true
      while !loop do
        let! msg = webSocket.read()
        match msg with
        | (Text, data, true) ->
          do! webSocket.send Text data true
        | (Ping, _, _) ->
          do! webSocket.send Pong [||] true
        | (Close, _, _) ->
          do! webSocket.send Close [||] true
          cts.Cancel()
          loop := false
        | _ -> ()
    }

let app : WebPart =
  choose [
    path "/" >=> OK "Hello World"
    path "/websocket" >=> handShake echoTime
  ]
open System.Security.Cryptography.X509Certificates
let sslCert = new X509Certificate2("../certificate.pfx", "")

startWebServer { defaultConfig with logger = Loggers.ConsoleWindowLogger LogLevel.Verbose
                                    bindings =
                                      [
                                      HttpBinding.mk HTTP (IPAddress.Loopback) 8080us
                                      HttpBinding.mk (HTTPS sslCert) (IPAddress.Loopback) 8443us
                                      ]
                                    } app
```

**Comment by ademar** [comment]
The answer to why it does not work is here http://stackoverflow.com/questions/9745249/html5-websocket-with-ssl

Basically you need to change the websocket url to use the ssl channel instead

```javascript
var wsUri = "wss://localhost:8443/websocket";
```

**Comment by zoren** [comment]
No sorry, that's not it. Chrome won't allow connections on non-443 ports, so I have set up port forwarding from 8443 -> 443(should have said so in my post sorry).

I still experience the same issue. Connection succeeds on 443, but I receive only one timestamp, and the connection remains open. On port 80(that i have forwarded to 8080) I receive a stream of timestamps as expected.

**Comment by zoren** [comment]
I'm using this html file to test the websocket(with the 80 -> 8080 and 8443 -> 443 port forwards mentioned above):

```html
<!DOCTYPE html>
<meta charset="utf-8" />
<title>WebSocket Test</title>
<script language="javascript" type="text/javascript">

var output;

function init()
{
  output = document.getElementById("output");
  testWebSocket();
}

function testWebSocket()
{
  var wsProtocol = window.location.protocol == "https:" ? "wss" : "ws"
  var wsUri = wsProtocol + "://localhost/websocket"
  websocket = new WebSocket(wsUri);
  websocket.onopen = function(evt) { onOpen(evt) };
  websocket.onclose = function(evt) { onClose(evt) };
  websocket.onmessage = function(evt) { onMessage(evt) };
  websocket.onerror = function(evt) { onError(evt) };
}

function onOpen(evt)
{
  writeToScreen("CONNECTED");
  doSend("Rock rocks");
}

function onClose(evt)
{
  writeToScreen("DISCONNECTED");
}

function onMessage(evt)
{
  writeToScreen('<span style="color: blue;">RESPONSE: ' + evt.data+'</span>');
  if(evt.data=="CLOSE"){
    websocket.close();
  }
}

function onError(evt)
{
  writeToScreen('<span style="color: red;">ERROR:</span> ' + evt.data);
}

function doSend(message)
{
  writeToScreen("SENT: " + message);
  websocket.send(message);
}

function writeToScreen(message)
{
  var pre = document.createElement("p");
  pre.style.wordWrap = "break-word";
  pre.innerHTML = message;
  output.appendChild(pre);
}

window.addEventListener("load", init, false);

</script>

<h2>WebSocket Test</h2>

<div id="output"></div>

```

**Comment by ademar** [comment]
OK, I have reproduced the issue now. I will spend sometime this afternoon trying to fix it.

**Comment by zoren** [comment]
Thank you so much! 👍

**Comment by ademar** [comment]
I have found the root of the problem which is `SslStream` not supporting multiple readers and writers simultaneously.  I continue working on a solution.

**Comment by ademar** [comment]
@zoren I've pushed a pre-release nuget v2.0.0-beta4. Can you give it a try ?

**Comment by zoren** [comment]
Thanks @ademar. I'm having trouble installing the package using paket. It reports:
```
Suave 2.0.0-alpha4 requested package Microsoft.FSharp.Core.netcore: >= 1.0.0-alpha-160509
```
Apparently only ```1.0.0-alpha-160304,``` is available, am I missing a nuget source(only have https://www.nuget.org/api/v2)?

**Comment by ademar** [comment]
Hum .. don't know what's going up with paket there, it seems it is referencing the `netcore` assembly.
Standard nuget.exe seems to work fine; at least on Xamarin Studio which is where I tested it.

**Comment by haf** [comment]
/cc @enricosada 

@zoren It's because 1) you don't constrain the paket.dependencies with `framework net45` or whichever is applicable to you, and 2) because it would seem enrico hasn't pushed that build to nuget (could you?)

**Comment by ademar** [comment]
He is pushing `Microsoft.FSharp.Core.netcore` to myget.org see https://github.com/SuaveIO/Suave-CoreCLR-sample/blob/master/NuGet.Config#L4

**Comment by haf** [comment]
Yes, I know, I was there when the repo was created ;)... I guess I'm asking whether it's something that will be pushed to the general nuget?

**Comment by enricosada** [comment]
@ademar it's not me pushing fsharp.core to myget, that's the the visualfsharp team feed

I think now with preview1 on nuget.org it's a good idea to push a prerelease `FSharp.Core.netcore` version too on nuget.org, we need to ask @KevinRansom about that

Meanwhile like in the sample repo, just add the `nuget.config` file in the same directory, or modify the global nuget config adding the myget feed

**Comment by zoren** [comment]
Thanks @ademar that fixed it for me! Great work!

Also thanks for helping me out with nuget @haf @enricosada

**Comment by haf** [comment]
Hurrah at bugfixes :)
