### ISSUE TITLE
Document how to start / stop the server?

### ISSUE THREAD

**Issue by mark4asp** [SuaveIO/suave#454]
This is coming from one who just followed the suave example on pages 26 - 27 of Expert F# 4.0 by Don Syme et al.  The example describes two webpages and the 2nd just follows on from the first. Examples are instantiated with:
1st: startWebServer defaultConfig (OK html)
2nd: startWebServer defaultConfig (OK fancyText)
Both examples work but it seems one can't switch between examples without closing down the devenv (which is a tedious way to do it).

So I looked at the suave.io website and did my google searches
  stop site:suave.io
  restart site:suave.io
There's nothing about stopping the instance, or restarting it. Maybe you have your special terminology. It would be nice if you put a sentence in the documentation which could be found using either of those searches which explains the situation w.r.t. start / stop / restart

**Comment by haf** [comment]
Hi @mark4asp 

You're right, it's not well documented. I'll write something on suave.io. :)

Stopping is done by disposing the cancellation token: https://github.com/SuaveIO/suave/blob/master/src/Suave.Testing/Testing.fs#L84-L88 which is allocated on line 110.

**Comment by GrahamMeintjes** [comment]
Thanks @haf.  I'm just starting with Suave.

That code won't compile because startWebServer returns unit. Line 3 needs the async method used in your Testing.fs:

`let listening, server = startWebServerAsync conf (OK "Hello World")`

**Comment by haf** [comment]
The task for someone who wants to contribute a bit is to take the docs I just wrote above and send a PR to the docs folder for it.

**Comment by YaroslavSchubert** [comment]
Hi! I can do it.

**Comment by haf** [comment]
@YaroslavSchubert That would be excellent =)

**Comment by john-patterson** [comment]
@YaroslavSchubert Hey, I recently had to piece together all these puzzle pieces. Did you get a chance to do a PR yet, or should I do a write-up? 

Additionally, is there a workflow for the "hey I just saved a file, please automatically restart the server and serve my new changes?" For instance, I'm used to the ring extensions for Leiningen where after you run `lein ring server` any changes to the views that you make are automatically mirrored on the local website.

Currently it seems that you have to stop the server, rebuild the project, and then restart the server. Is there something I might be missing or is this a feature request?
