### ISSUE TITLE
DotLiquid Option Types

### ISSUE THREAD

**Issue by jackmott** [SuaveIO/suave#455]
It looks like currently DotLiquid can't handle option types, if that is correct, and there is interest in adding them let me know, I can take a stab at it.

**Comment by haf** [comment]
Could you sketch the outcome; what would it look like?

**Comment by jackmott** [comment]
Good question!  I was thinking it would behave the same as if you had a null field in a C# project, but perhaps that would be counter to idiomatic F# to allow that behavior at all. Thoughts?

Alternatively maybe there would be a way to get a compile time failure if an option type is included in a dot liquid template? Currently you don't find out till runtime.

I will think about it and update here if I come up with a good solution.

**Comment by samritchie** [comment]
I’d expect `None` to be falsy (mapped to `null` or `false`?), and `Some` to be unwrapped, so you can do things like:

    {% if model.maybe_string %}
        {{model.maybe_string}}
    {% endif %}

Otherwise maybe something like `issome`/`isnone`/`value` filters, unsure how well this would work in dotliquid though:

    {% if model.maybe_string | issome %}
        {{model.maybe_string | value}}
    {% endif %}

**Comment by jackmott** [comment]
I tried to set up some filters along those lines, and it doesn't seem to work. DotLiquid complains that "Some(x)" is not a valid even if you feed it to a filter.

What if we just unwrapped Some x -> x and None -> Unchecked.defaultof

?

**Comment by jackmott** [comment]
See PR for option support here:
https://github.com/SuaveIO/suave/pull/478

If this gets merged I will close this.

**Comment by jackmott** [comment]
Options can now be used like so:
```html
{% for decoder in model.decoders %}  
  {% if decoder.Value %}               
    <option value="{{decoder.Value.x}}">{{decoder.Value.x}}</option>
  {% endif %}
{% endfor %}
```
