### ISSUE TITLE
cannot open namespace Suave.Types

### ISSUE THREAD

**Issue by halcwb** [SuaveIO/suave#456]
I have added Suave using the following dependencies:

> nuget Suave
> nuget Suave.Testing

However I cannot open the namespace Suave.Types. 

When I try the test case, I have to manually add System.Net.Http and I get errors:

```
#load "load-project-release.fsx"

#time

open Suave
open Suave.Types
open Suave.Testing

open Fuchu

testCase "parsing a large multipart form" <| fun _ ->

  let res =
    runWithConfig (OK "hi")
    |> req HttpMethod.POST "/" (Some byteArrayContent)

  Assert.Equal("should get the correct result", "hi", res)

```

Suave.Types is not defined, also runWithConfig and byteArrayContent are undefined?

**Comment by ademar** [comment]
There is no such namespace Suave.Types.

**Comment by halcwb** [comment]
Thanks, I just went through all of the release notes and discovered this. However, everywhere in the suave docs, the old api is used. Also, when I cloned Suave and tried to build it, (on windows with VS2013), using the build.cmd it fails, also using VS it fails.

**Comment by ademar** [comment]
@halcwb yeah the "How to build" section is somewhat incorrect. The only supported/working build procedure involves using the rake script.

I have opened #457 for this matter.
