### ISSUE TITLE
Support for request body compression

### ISSUE THREAD

**Issue by toburger** [SuaveIO/suave#461]
A client can send a `Content-Encoding: gzip` to signal that the body of the request ist compressed.
At the moment this isn't handled by suave.

When a client sends a gzipped body to suave the server doesn't respond.
The RFCs are saying, that if the server doesn't support this header it should respond with a 415 respond (Unsupported Media Type).

I'm no expert regarding HTTP server implementations but it would be nice if it would be possible somehow to optionally handle this header. From what I have seen this header isn't widely supported by servers and could be a thread because of [Zip Bomb attacks](https://en.wikipedia.org/wiki/Zip_bomb), but it would be nice to have the possibility to handle such requests as an opt in.

Can I intercept the pipeline to read the header and unzip the body myself somehow?

**Comment by ademar** [comment]
> Can I intercept the pipeline to read the header and unzip the body myself somehow?

Yes, it should be possible to write a combinator that does this.

```fsharp
let unzipBody : WebPart =
  fun ctx -> WebPart.asyncOption {
    if ctx.request.header "content-encoding" = Choice1Of2 "gzip" then 
      return { ctx with request = { ctx.request with rawForm = Utils.Compression.gzipDecode ctx.request.rawForm} } 
    else 
      return ctx }
```

That does not work right now because the Compression module is internal; I think we should change that.

**Comment by toburger** [comment]
It works!
I had the same idea, but somehow it didn't work. Suave got stuck when reading the form body and didn't run to my WebPart.
I was using a test client provided for me to test the api specifications.
After your solution I got curious if maybe the test client is the problem. After writing a test client by myself I noticed that the client program was wrong, not the implementation of suave!
