### ISSUE TITLE
Serving static files with white space in the name

### ISSUE THREAD

**Issue by supertom44** [SuaveIO/suave#464]
Hi,

I've noticed that when using Files.browseHome to serve static files from a directory, if the file has any white space characters in it, the path cannot be resolved.

Here is a simple example:

```fsharp
module FileServer
  
open Suave
open Suave.Web
open Suave.Http
open Suave.Logging


let app = Files.browseHome 

#if INTERACTIVE
#else
let cfg =
  { defaultConfig with
      bindings = [ HttpBinding.mkSimple HTTP  "127.0.0.1" 8011 ]
      homeFolder = Some @"C:\StaticFiles"
      logger = Loggers.saneDefaultsFor LogLevel.Verbose  }
let _, server = startWebServerAsync cfg app
Async.Start(server)
System.Diagnostics.Process.Start("http://localhost:8011") |> ignore
System.Console.ReadLine() |> ignore
#endif
```

I have two files in the directory StaticFiles:

- test.jpg
- test with spaces.jpg

I can access "test.jpg" no problem however when I try to access "test with spaces.jpg" it appears that it is looking for the file on disk using the url encoded path, ie: "test%20with%20spaces.jpg".

Here is the log output for when I try to access "test with spaces.jpg"

> [V] 2016-06-11T09:02:45.1117527Z: Files.browse trying file (local file url:'/test%20with%20spaces.jpg' root:'C:\StaticFiles') [Suave.Http.Files.browse]
[V] 2016-06-11T09:02:45.1122534Z: failed to find resource by key 'C:\StaticFiles\test%20with%20spaces.jpg' [Suave.Http.ServeResource.resource]

**Comment by ademar** [comment]
This was fixed a while ago. Which version are you running ?

**Comment by ademar** [comment]
Sorry, I see this is broken in the 1.x branch. 

If you feel adventurous you can give a try to pre release version `v2.0.0-alpha4`

**Comment by supertom44** [comment]
Hey,

Thanks for responding, it's not a major issue, I can work around it for the time being by ensuring none of the paths contain white space, until V2 is released.

Cheers.
