### ISSUE TITLE
Indicate build success: "FsLibTool: Failed to resolve" looks like build failure

### ISSUE THREAD

**Issue by theimowski** [SuaveIO/suave#466]
This happens for `:docs:reference` rake task:

```
packages\docs\FsLibTool\tools\FsLibTool.exe src docs/_site
Generating reference for Suave.
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: mk
Failed to resolve: path
Failed to resolve: path
Failed to resolve: empty
Failed to resolve: path
Failed to resolve: HttpRuntime
Failed to resolve: mk
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: HttpContext
Failed to resolve: path
Failed to resolve: Http
Failed to resolve: Http.host
Failed to resolve: empty
Failed to resolve: empty
Failed to resolve: mk
Failed to resolve: HttpRuntime
```

Should this fail the build as well? Looks like currently these failures are ignored

**Comment by polytypic** [comment]
The `Failed to resolve` just means that the symbol lookup hack of FsLibTool failed to find a definition to link to a symbol.  You can usually ignore those.

**Comment by theimowski** [comment]
I see, it confused me cause when you see this wall of "fails" at the very end of build output you might think the build itself failed. Anyways I'd suggest to print some indication of build success at the end, so that no more dev gets confused by `Failed to resolve` msgs.
