### ISSUE TITLE
Document state-passing between web parts

### ISSUE THREAD

**Issue by vasily-kirichenko** [SuaveIO/suave#482]
I don't like to use a mutable variable here https://github.com/vasily-kirichenko/FsAutoComplete/blob/refactoring/src/FsAutoComplete.Suave/FsAutoComplete.Suave.fs#L41, which is reassigned in this code  https://github.com/vasily-kirichenko/FsAutoComplete/blob/refactoring/src/FsAutoComplete.Suave/FsAutoComplete.Suave.fs#L74

So, we have a bunch of handlers like this:

``` fsharp
POST >=>
        choose [
            path "/parse" >=> handler (fun (data : ParseRequest) -> commands.Parse state data.FileName data.Lines)
            //TODO: Add filewatcher
            path "/project" >=> handler (fun (data : ProjectRequest) -> commands.Project state data.FileName DateTime.Now false)
            path "/declarations" >=> handler (fun (data : DeclarationsRequest) -> commands.Declarations state data.FileName)
...
```

Each handler may modify (create new) `state`, then assigns it to a mutable variable. It's not very functional.

**Comment by kolektiv** [comment]
I don't know if there's a Suave specific way of doing this, but I usually make (shared) state "agent" based in some way with web applications, either a simple mailbox or Hopac. That lets me control the concurrency of usage, and usually create some small control grammar via "commands" or actions against that agent. I've not found a better approach than an agent/functional hybrid like that (and the internals of the agent and the handlers themselves usually remain pure).

**Comment by vasily-kirichenko** [comment]
@kolektiv A mutable var / MBP / Hopac server, all of them effectively represent a mutable state, external to Suave loop (I guess there is one). I don't like the fact that Suave handlers are imperative, i.e. they are supposed to perform some side effect. I'd prefer that `app` thing to be an explicit recursive loop, like we do in Hopac `Job.iterateServer initialState <| fun _ -> job { ... return newState }`. It would look like:
```fsharp
let app = 
    POST >=>
    choose [
        path "/foo" >=> fun r state -> ...; newState
        path "/bar" >=> fun r state -> ...; newState
    ]

startApp app initialState
```
Maybe it's already possible, I know very little about Suave.

**Comment by ademar** [comment]
It is not very well documented but we have some modules to persist requests across request:

https://github.com/SuaveIO/suave/blob/master/src/Suave/State.fs

**Comment by kolektiv** [comment]
@vasily-kirichenko that's interesting - not something i'd considered doing too much, but i'm almost tempted to prototype something which creates a server which has a monadic global state as well as a local (request/response) type state. The only problem with it would be that it assumes the only thing likely to be changing your state is functions handling requests, so you'd need a mechanism to allow other parts of the system to change that global state, and potentially make changes clear/pushed. Interesting concept though.

**Comment by haf** [comment]
@vasily-kirichenko Are you thinking of the server just as an API towards some actor-like loop?

You'd probably need some more actor-like loops around that for doing actual side-effecting tasks to the rest of the environment around the Suave process, such as DB calls... Just like Andrew mentions.

**Comment by danieljsummers** [comment]
I think the page I'm working around #608 could cover both sessions and user data.
