### ISSUE TITLE
Allow sending of byte ArraySegment's on websocket

### ISSUE THREAD

**Issue by mvkra** [SuaveIO/suave#484]
When using the Websocket support in Suave the send method on the Websocket object is of the form:

member Send: opcode: Opcode -> bs: byte[] -> fin: bool-> Async<Choice<unit, Error>>

The problem with the above method is that if I'm using this framework with large big-data style messages the large object heap quickly fills up and I get application OutOfMemoryException's due to the use of the byte array as a parameter. Large byte[] arrays go on the large object heap and cause fragmentation quickly.

I'm proposing adding an overload that takes in an ByteSegment instead allowing the user to reuse byte[] array buffers and avoiding the issue of sending large messages to the client along with other optimisations to avoid allocating additional byte arrays before sending it to the SocketAsyncEventArgs (e.g in the frame function of the Websocket module in particular with the MemoryStream being created to build the frame payload). 

member SendSegment: opcode: Opcode -> bs: ByteSegment -> fin: bool-> Async<Choice<unit, Error>>

I've done the change and it doesn't seem too hard on my laptop with tests passing; just wanting your opinion before I bother to put it up whether this is a feature you also want upstream in the library.

**Comment by haf** [comment]
Hi @mvkra ,

Can everything be rewritten to this new signature, so that the old one can be dropped? That way we could try to keep the interfaces small.

**Comment by mvkra** [comment]
No problem. I kept the old method there bit it is now simply a wrapper
around the new one. I made the assumption that you might of wanted to keep
Api compatibility and therefore it would be allowed as a minor version
release.

As long as that's what you want I.e changing the signature of the existing
send method I'm happy to change it.

**Comment by haf** [comment]
I think we'll be aiming for v2 fairly shortly. When we have CoreCLR support and that is completely reproducible. Since @enricosada has been doing wonders with regards to supporting CoreCLR, that may not be very long. I'm planning to test it when I can homebrew install CoreCLR on my OS X.

**Comment by enricosada** [comment]
the netcore suave is ok.
About brew formula, i added another comment in the homebrew issue in dotnet/cli, let's see. 
maybe we should ask in twitter for help, dunno
