### ISSUE TITLE
DataContractSerializer broken on mono

### ISSUE THREAD

**Issue by halcwb** [SuaveIO/suave#487]
Your default json handler is `DataContractSerializer`, but I think the `DataContractSerializer` is broken on mono, see: http://stackoverflow.com/questions/38163968/unable-to-return-a-json-with-suave-f/38200662#38200662 and https://bugzilla.xamarin.com/show_bug.cgi?id=42446.

Wouldn't it be better to just stick to using Newtonsoft? Far easier and more reliable?

**Comment by ademar** [comment]
Hi.  

Thanks, but no we rather do not take a dependency. See here, you can pass your own serializer if you do not like the BCL serializer.

https://github.com/SuaveIO/suave/blob/master/src/Suave/Json.fs#L27

**Comment by haf** [comment]
@halcwb I only use [Chiron](https://github.com/xyncro/chiron/) myself. It can be added as a single file, but we'd also need to add Aether (single file) and FsParsec (many files/dll) dependencies then.

**Comment by halcwb** [comment]
I understand your reasoning, but just my curiosity, does your `Suave.Tests/Json.fs` pass on mono??

**Comment by ademar** [comment]
@halcwb Yes, it does.

**Comment by halcwb** [comment]
That's weird. I also posted a question on [stackoverflow](http://stackoverflow.com/questions/38276829/is-datacontractserialization-broken-on-mono) about this. Am I doing something wrong?

**Comment by halcwb** [comment]
P.s. `mapJsonWith` doesn't exist in your official latest release.
