### ISSUE TITLE
Suave.Html.Xml

### ISSUE THREAD

**Issue by everystone** [SuaveIO/suave#489]
Hi,

Im learning Suave and F#, and struggling with a part in the MusicStore example  
(https://theimowski.gitbooks.io/suave-music-store/content/en/create_album.html)

This part: 
```
type Field<'a> = {
    Label : string
    Xml : Form<'a> -> Suave.Html.Xml
}
```

the Type Xml does not exist in Suave.Html.
I tried using Suave.Xml.Xml, but then I get errors when trying to use select and selectInput later, their return type is Node, and I need Xml. 

Sorry if this is the wrong place to ask, 
Cheers.

**Comment by theimowski** [comment]
Right, the book is based on Suave and Suave.Experimental 1.0 - not the best option but it should work if you downgrade to that version.

**Comment by haf** [comment]
@theimowski Do you have plans for handling the upgrade to v2.0? The APIs of Suave core haven't changed much, but I think experimental has changed a lot.

**Comment by theimowski** [comment]
I do but my biggest issue is with that i have permalinks to specific commits in the book -  don't know yet how to handle the upgrade then. Rebasing whole branch is a bit of pain.  Anyways i hope to find some time soon to do the upgrade

**Comment by FoggyFinder** [comment]
Well, it's still alpha version. In my opinion it makes sense to upgrade when will be a final release.

**Comment by iltay** [comment]
type Field<'a> = {
    Label : string
    Xml : Suave.Form.Form<'a> -> Suave.Xml.Xml
}
