### ISSUE TITLE
Does Suave support OWIN?

### ISSUE THREAD

**Issue by ktodyruik** [SuaveIO/suave#491]
Hi,

I was searching around to see if Suave supports OWIN, and how to set it up if it does. A google search turned up the owin.fs file in the suave github repository. Is OWIN currently supported? If so, could anybody point me to or provide an example?

Thanks

**Comment by JohnDoeKyrgyz** [comment]
Hello @ktodyruik 

Suave can host owin middleware, and owin applications. As an example check out the [IdentityServerIntegration](https://github.com/SuaveIO/suave/tree/master/examples/IdentityServerIntegration) project in the Examples folder. Identity Server is an OWIN middleware for generating tokens.
