### ISSUE TITLE
Header routing combinator

### ISSUE THREAD

**Issue by mjgpy3** [SuaveIO/suave#503]
First off let me just say that this is a brilliant library! I find it very useful and intuitive.

Would there be any value in adding routing combinators for headers? I'm thinking something like `pathScan` but for headers.

I'm not sure if anyone would find use in these, I've had a couple of instances so far.

**Comment by haf** [comment]
Sure, it could be useful and probably low maintenance too. Send a PR so we can have a look.

**Comment by mjgpy3** [comment]
Will do, thank you!

**Comment by haf** [comment]
I'm closing this issue as it's just a question, but I'm looking forward to your PR :)
