### ISSUE TITLE
Suave is doing > 99% CPU all the time in OSX

### ISSUE THREAD

**Issue by leolorenzoluis** [SuaveIO/suave#506]
Using Mono JIT compiler version 4.4.1, and running a basic suave application. 

Is there a way for me to give you more information on why is this happening? 

Repro steps is just run a simple suave.

Could it be something related like [this question](http://stackoverflow.com/questions/31685597/how-to-fix-mono-using-100-cpu)

**Comment by haf** [comment]
Mono 4.4.1 has a broken JIT. They released a backported bugfix to their GC last week, but we had moved on to 4.6.0 by then.

**Comment by leolorenzoluis** [comment]
I assume the solution is to move to 4.6.0?

**Comment by haf** [comment]
Yes, or their latest patch, or 4.2.3.

**Comment by leolorenzoluis** [comment]
Still same. CPU > 100% After upgrading Mono to 4.6.0.

**Comment by haf** [comment]
@leolorenzoluis That's an issue; do you have a way to repeatedly reproduce it that you can share?

**Comment by leolorenzoluis** [comment]
You could pull the [repository](https://github.com/leolorenzoluis/Datamasa) that I'm running against with. 

Also I'm on OS X El Capitan 10.11.6

Attaching also what I see from Activity Monitor.

<img width="400" alt="screen shot 2016-09-17 at 11 12 53 am" src="https://cloud.githubusercontent.com/assets/15150044/18609105/dbab7efa-7cc7-11e6-9d17-6b567a3fcb5a.png">
<img width="554" alt="screen shot 2016-09-17 at 11 13 21 am" src="https://cloud.githubusercontent.com/assets/15150044/18609106/dbaf2a28-7cc7-11e6-9002-d9c90eea2ca5.png">

**Comment by haf** [comment]
This seems to be an artifact of your build script:

<img width="852" alt="screen shot 2016-09-17 at 18 15 14" src="https://cloud.githubusercontent.com/assets/193115/18609451/c41403f8-7d02-11e6-824c-77013ee93d70.png">

It would seem that your solution is continuously reloading and re-compiling the fsx file, despite that not being necessary.
