### ISSUE TITLE
additional Suave assemblies don't support netstandard (.NET Core)

### ISSUE THREAD

**Issue by quezlatch** [SuaveIO/suave#508]
when i have an dot net core project, adding "Suave": "2.0.0-alpha5" to project.json works fine. however, any other packages such as "Suave.Experimental" or "Suave.Razor" report
`error NU1002: The dependency Suave.Experimental 2.0.0-alpha5 does not support framework .NETCoreApp,Version=v1.0.`
when i attempt to `dot net build`

**Comment by danieljsummers** [comment]
This doesn't seem to be an issue with 2.0.0-rc1.

**Comment by danieljsummers** [comment]
I may have to take my previous comment back; I don't think I had the right packages in project.json.  I'll verify this when I have a chance.

**Comment by danieljsummers** [comment]
Looking at `Rakefile`, line 202 as it currently sits, that's where the standard nupkg and the core nupkgs are merged into a single package.  It looks like this is only for Suave.[version].nupkg.  As a comparison, line 235 in the task "create_nugets_quick" creates a projects list from the `fsproj` files it finds in the tree.  I suspect that the package merge needs to use a similar concept to merge all the packages, not just Suave.

*(This is my first attempt at reading Ruby, so I could be way off.)*

**Comment by haf** [comment]
Thee reading of the Code of Ruby is true ;). 

So a loop?

**Comment by danieljsummers** [comment]
I had a bit, and took a stab at it.  Here's what I've got; there's one line here that's obviously not Ruby; I couldn't find any documentation of what properties exist for `|f|`.  Lines 4 and 5 are new (with matching `end`s), and the others use the interpolation with the project name; I just don't know how to derive the name of the project.

```
  desc 'Merge standard and dotnetcli nupkgs; note the need to run :nugets before'
  task :merge => :coreclr_binaries do
    Dir.chdir("src/Suave") do
      projects.each do |f|
        proj = f.something.without.fsproj <-- What goes here?
        version = SemVer.find.format("%M.%m.%p%s")
        sourcenupkg = "../../build/pkg/#{proj}.#{version}.nupkg"
        clinupkg = "bin/#{Configuration}/#{proj}.#{version}-dotnetcli.nupkg"
        system dotnet_exe_path, %W|mergenupkg --source "#{sourcenupkg}" --other "#{clinupkg}" --framework netstandard1.5|
      end
    end
  end
end
```
