### ISSUE TITLE
TCP request processing failed, invalid url: ''

### ISSUE THREAD

**Issue by jc776** [SuaveIO/suave#513]
```
[W] 2016-10-03T07:58:04.9902039+00:00: TCP request processing failed [Suave.Tcp]
 - errors: [System.Exception: invalid url: ''
   at <StartupCode$Suave>.$ConnectionFacade.get_processRequest@431-2.Invoke(String _arg47)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)]
```

I occasionally get this in the logs after uploading a file, when running the server through (VS's) FSI or as an exe file. This doesn't affect using the website (the handlers/side effects still happen), but when I host the server on IIS (ASP NET Core Handler - this just runs the exe file, specifying a port), uploading sometimes results in a large IIS error page, '502 - Web server received an invalid response while acting as a gateway or proxy'. (The exception is always present when I get the error page, but doesn't always cause that error page)

My routes handler is a `choose []` that ends with `request (fun r -> NOT_FOUND (r.path))`, so "an empty url" should be handled.

The upload routes are a `warbler (fun htc -> [side effects]; Redirection.redirect (htc.request.path))` to make e.g. `POST /aaa/files` redirect to `GET /aaa/files`.

How do I prevent or catch this error to stop IIS complaining?

**Comment by ademar** [comment]
What version of Suave is this ? I think this is fixed in the v2.0 line.

**Comment by haf** [comment]
Yes the v2.0 nuget is probably the right choice for you. We're still cooking some features on it, which is why it's unreleased, but tests are passing.

**Comment by jc776** [comment]
I'm using 2.0.0-alpha5. I'll try changing to alpha6, then.

**Comment by haf** [comment]
We've moved to v4.5 at the least I suppose is what happened. After all, v4.0 is six years old.

I'm closing this for a number of reasons:

 1. The latest version isn't being tested by OP
 2. Suave is both a web server and we don't explicitly support running behind IIS
 3. No logs or other debugging material have been supplied
 4. The last entry was 29 days ago about something other than the issue.
