### ISSUE TITLE
Replace HttpClient for Http.fs in tests

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#523]
Let's move towards supporting F# projects by supporting the Http.fs client rather than the HttpClient.

Most likely this means we'll be able to compose requests that automatically start their backing HTTP servers while they are running (using the compositional abilities of Http.fs).

We should also be able to improve Suave.Testing through this.

**Comment by ademar** [comment]
Is this really necessary for v2 though? I do not like rewrite working code just for the love of it.

**Comment by haf** [comment]
No it's not necessary for v2 at all. It's more like I'm documenting what I'm aiming for if there's enough time.

I talked a bit with forki and enrico and they are planning to contribute preview3 support for .net core to this repo when that support in the F# compiler is finished. They expect that to be in two weeks. I suggest we await that and make v2 a dotnet core-focused release.

That way we can also fix up docs till then.

I like working through code to remove development friction amongst developers and this is one way to do that.
