### ISSUE TITLE
Parallel DotLiquid renderings sometimes crash

### ISSUE THREAD

**Issue by kuffis** [SuaveIO/suave#530]
After updating to 2.0.0rc1 a program I'm developing no longer worked reliably. The program renders long Javascript files (100k - 300k) as DotLiquid templates and writes them to cache. From cache it serves them as plain text.

```
      printfn "Rendering & writing to cache:%s" fileName
      let pageContent = Async.RunSynchronously (DotLiquid.renderPageFile fileName mySnippet)
      File.WriteAllText(cacheFileName, pageContent, System.Text.Encoding.UTF8)
      printfn "Rendered & wrote to cache, now writing to server"
      OK pageContent http

```
The exception below happens, when two large DotLiquid templates happen to be rendered in parallel (browser sends parallel requests for Javascript files, the cache is empty and different files get rendered to cache in parallel.)

```
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds
  at System.Array.Copy (System.Array sourceArray, Int32 sourceIndex, System.Array destinationArray, Int32 destinationIndex, Int32 length) <0x7f7d42655930 + 0x003f8> in <filename unknown>:0 
  at Suave.Sockets.AsyncSocket+asyncWriteBufferedBytes@66-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) <0x4158fa90 + 0x00043> in <filename unknown>:0 
  at <StartupCode$Suave>.$SocketMonad+Bind@16-1[a,b].Invoke (Microsoft.FSharp.Core.FSharpChoice`2 _arg1) <0x41557ba0 + 0x0015c> in <filename unknown>:0 
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@835-1[a,b].Invoke (a a) <0x4153d590 + 0x000af> in <filename unknown>:0 
```

There is also something else going on, sometimes when loading a page the 6th or 7th request freeze. The browser shows loading swirl and nothing happens, but when I stop suave.io then also browser shows aborted requests. This doesn't require DotLiquid rendering, but it does require 'time-consuming requests'. The aborted requests never enter the written code.

OS: Ubuntu 14.04 LTS in Windows 10 VirtualBox
CLR: Mono JIT 4.2.2
SuaveIO: 2.0.0rc1  (no problems with 1.1.3, except lack of DotLiquid.renderPageFile from API :)

Server initialization:

```
let app =
  choose
    [ GET >=> choose
        [ path       "/favicon.ico" >=> staticFile
          pathStarts "/images"      >=> staticFile
          path       "/crud/deck"   >=> Writers.setMimeType "application/json; charset=utf-8" >=> getDecks
          pathStarts "/"            >=> formattedSnippet  ]
    ]
startWebServer defaultConfig app 

```

**Comment by ademar** [comment]
While there is certainly a bug in our code, as indicated by the "Destination array was not long enough" exception and that we shall address; there is something in your code that called my attention and I thought I should mention to you. 

It is in general bad practice to make long blocking calls inside an async workflow. In this case the recommended way of writing the above code would be something like this.

```fsharp 

let mypart : WebPart =
  fun (x : HttpContext) ->
    async {
      let! pageContent = DotLiquid.renderPageFile fileName mySnippet
      do! File.WriteAllTextAsync(cacheFileName, pageContent, System.Text.Encoding.UTF8)
      return! OK pageContent x
    }

```
note that `WriteAllTextAsync` above is a made up function but you get the idea.

**Comment by ademar** [comment]
OK I've located what appears to be the bug and will be pushing a fix for it tomorrow.

**Comment by kuffis** [comment]
Thanks for the introduction to async WebParts!

**Comment by ademar** [comment]
@kuffis I've commit a fix for this. It should be out in the release, hopefully very soon.

**Comment by ademar** [comment]
v2.0.0-rc2 is out with this fix. Give it a try and let us know how it goes.

**Comment by kuffis** [comment]
It goes smoothly and without a hint of error.
