### ISSUE TITLE
Connections sometimes terminate early

### ISSUE THREAD

**Issue by mavnn** [SuaveIO/suave#534]
Running suave pre-release behind nginx, we've been experiencing intermittent incomplete chunk encoding errors and content length mismatches.

The nginx logs suggest that these connections are being terminated early by the suave server itself rather than the content length header being calculated incorrectly.

The errors only seem to occur on reasonably large responses, and only occur intermittently; we've not managed to identify any particular circumstances that lead to them happening. For example, they occur even under very light load.

**Comment by ademar** [comment]
@mavnn it sounds like a bug I fixed a few days ago. https://github.com/SuaveIO/suave/commit/a795add90e9bba99c5360b64ecad5c4e5c66a6db

**Comment by mavnn** [comment]
@ademar you might be right actually - I was just looking at that commit, thinking that it might have caused the regression... while actually it was merged just after the last pre-release! Would it be possible for you or @haf to do an other pre-release which includes this fix?

**Comment by ademar** [comment]
I'll do it later today if @haf doesn't do it first.

**Comment by ademar** [comment]
funny this bug is biting me right now

**Comment by ademar** [comment]
@mavnn  I just pushed v2.0.0-rc2 give it a try

**Comment by haf** [comment]
Fixed with rc2
