### ISSUE TITLE
suave 2.0: invalid url: '' when posting form-data

### ISSUE THREAD

**Issue by toburger** [SuaveIO/suave#541]
Given the simplest configuration possible:

```fsharp
open Suave
startWebServer defaultConfig (Successful.OK "hello world!")
```

When posting the following request to suave:

```http
POST http://localhost:8083/ HTTP/1.1
cache-control: no-cache
Accept: */*
Host: localhost:8083
content-type: multipart/form-data; boundary=--------------------------752619164212289462303303
content-length: 161
Connection: keep-alive

----------------------------752619164212289462303303
Content-Disposition: form-data; name="foo"

bar
----------------------------752619164212289462303303--
```

suave returns sucessfully, but throws also an exception:

```
System.Exception: invalid url: ''
   bei <StartupCode$Suave>.$ConnectionFacade.get_processRequest@442-2.Invoke(String _arg48) in Z:\workarea\suave\src\Suave\ConnectionFacade.fs:Zeile 442.
   bei Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
````

PS: don't know why it prints `Z:\workarea\suave`...

**Comment by ademar** [comment]
Is there an extra newline at the end of the post data?

**Comment by toburger** [comment]
Yes, exactly, I found this a moment ago.. ;)

**Comment by toburger** [comment]
.NET and Postman (didn't test it with other libs) are automatically adding newlines at the end.

**Comment by ademar** [comment]
> .NET and Postman (didn't test it with other libs) are automatically adding newlines at the end.

Are they really ? I mean we have similar tests (with the .NET client) in our suite and we do not see this behavior. On the other hand I do have seen text editors adding a gratuitous new line at EOF.

In any case this do not seem like a Suave bug .

**Comment by toburger** [comment]
Using HttpClient/RestSharp, the error gets thrown (https://gist.github.com/toburger/bdf340882f0e7a8f8e9d6e11a21b43d7).

The problem is that I have no control over the lib my client is using and suave 1.0 does not have this behavior.

**Comment by ademar** [comment]
This should be easy to test, as shown in your gist. Can you submit a PR with a failing test case ?

We already have  tests for POST parsing  but we may be missing something.

https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/HttpVerbs.fs
https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Parsing.fs
https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Model.fs
https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/regressions/Bug256-FormDataParsing.fs

**Comment by toburger** [comment]
Sure! I will send you a PR when ready!

**Comment by ademar** [comment]
This should be fixed now in the latest pre-release.

**Comment by toburger** [comment]
it works! thx!
