### ISSUE TITLE
bug in owin handling means signalr doesn't connect

### ISSUE THREAD

**Issue by robertpi** [SuaveIO/suave#547]
I'm been trying to get signalr working with suave. It seems most things go okay, but due to a bug when the connect url is called, it's treated as a 404.

There's already a fix available here: https://github.com/TheAngryByrd/suave/tree/signalrdemo

but it doesn't seem to have been merged into the master branch. Should I add the fix to my own clone of suave and send a PR? Or can a PR be send from TheAngryByrd's repo?

Thanks,
Rob

**Comment by haf-lynx** [comment]
We could start by pinging @theangrybyrd to see if he has any comments on his branch and code - then if you the PR we'd be very pleased. =)

**Comment by ademar** [comment]
It think what he does there is equivalent to the following, so you may don't need the patch:

```fsharp
context(fun ctxt -> owin ctx.request.path)
```

**Comment by TheAngryByrd** [comment]
@ademar 
So like this? 
```
let owin path = builder.Build() |> OwinApp.ofAppFunc path
        let app = 
            
            choose [
                GET >=> path "/" >=> Files.browseFileHome "index.html"
                context(fun ctx -> owin ctx.request.path)
            ]
```

Still doesn't seem to work =\

**Comment by ademar** [comment]
Hum .. yeah what I said above does not work. But I still think there is something (even if it works) incorrect with your fix because `requestPathBase`  is not the same as `ctx.request.path` at least conceptually.

**Comment by ademar** [comment]
In your example `requestPathBase` should be `"/"`

**Comment by TheAngryByrd** [comment]
Yeah that's what's really weird. 

If I set requestPathBase to "" it works, but if I set it to "/" it doesn't. =\

**Comment by ademar** [comment]
> If I set requestPathBase to "" it works, but if I set it to "/" it doesn't. =\

We are onto something here.

**Comment by TheAngryByrd** [comment]
That's with the "patch" I made to `Owin.fs`.  

If I undo the patch, the error I get from signalr is

```
 http://127.0.0.1:8083/connect?transport=longPolling&clientProtocol=1.5&conn…2F77z7EqRgPoxMuavTHf&connectionData=%5B%7B%22name%22%3A%22demohub%22%7D%5D 
```

I remember stepping through SignalR and they do some magics to come up with urls.

**Comment by ademar** [comment]
> OWIN spec requires request path base to be either the empty string or start with "/"

So I guess it is not wrong to set it to `""`

**Comment by ademar** [comment]
OK, I'll spend sometime with your example and see whats going on.

**Comment by TheAngryByrd** [comment]
If I set  requestPathBase to "/" I get

```
OPTIONS http://negotiate/?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22demohub%22%7D%5D&_=1482334759129 net::ERR_NAME_NOT_RESOLVED
```

**Comment by TheAngryByrd** [comment]
Without "patch" and setting `requestPathBase` to `""`.  SignalR doesn't work.

```
--> owinRequestUri.Path --> /signalr/js/js/reconnect
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js/js/reconnect
--> owinRequestUri.Path --> /signalr/js
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js
--> owinRequestUri.Path --> /signalr/negotiate
--> requestPathBase --> 
--> ctx.request.path --> /signalr/negotiate
--> owinRequestUri.Path --> /connect
--> requestPathBase --> 
--> ctx.request.path --> /connect
--> owinRequestUri.Path --> /connect
--> requestPathBase --> 
--> ctx.request.path --> /connect
--> owinRequestUri.Path --> /signalr/abort
--> requestPathBase --> 
--> ctx.request.path --> /signalr/abort
```
Without "patch" and setting `requestPathBase` to `"/"`. SignalR doesn't work.

```
--> owinRequestUri.Path --> signalr/js
--> requestPathBase --> /
--> ctx.request.path --> /signalr/js
```

With "patch" and setting `requestPathBase` to `""`.  SignalR works.
```
--> owinRequestUri.Path --> /signalr/js
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js
--> owinRequestUri.Path --> /signalr/js/negotiate
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js/negotiate
--> owinRequestUri.Path --> /signalr/js/js/connect
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js/js/connect
--> owinRequestUri.Path --> /signalr/js/start
--> requestPathBase --> 
--> ctx.request.path --> /signalr/js/start
```

**Comment by ademar** [comment]
I found the root of the problem, will be pushing a fix soon.

**Comment by robertpi** [comment]
Thanks again for looking into this!



Quick aside, seems the nuget version of suave won't allow this:



            choose [    GET >=> path "/" >=> Files.browseFileHome
            "index.html"    context(fun ctx -> owin ctx.request.path) ]


The build fails with this error:

         C:\code\ChatSampleSignalr\src\ChatSampleSignalr\Library.fs(49,-
           41): error FS0193: Type constraint mismatch. The type 
           HttpRequest    is not compatible with type    HttpCookie
           The t ype 'HttpRequest' is not compatible with the type
           'HttpCookie' [C:\code\ChatSampleSignalr\src\ChatSampleSignal-
           r\ChatSampleSignalr.fsproj]


The version last source from github do compile okay, but makes no
difference.


One detail that might be important is it's only the calls to "connect"
that fail as they are not "/signalr/connect" but to "/connect" directly.
The other calls all seem to be made to /signalr correctly. When load the
page I see:
http://localhost:8083/connect?transport=serverSentEvents&clientProtocol=1.5&connectionToken=<token> (404)
http://localhost:8083/signalr/js (200)

http://localhost:8083/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22demohub%22%7D%5D&_=1482340294817 (200)
http://localhost:8083/connect?transport=longPolling&clientProtocol=1.5&connectionToken=<token> (404)
http://localhost:8083/signalr/abort?transport=longPolling&clientProtocol=1.5&connectionToken=<token> (200)


Guess I could work around by having suave redirect /connect calls to
/signal/connect


On Wed, Dec 21, 2016, at 05:12 PM, Jimmy Byrd wrote:

> Without "patch" and setting requestPathBase to "".  SignalR
> doesn't work.


> --> owinRequestUri.Path --> /signalr/js/js/reconnect -->
> requestPathBase --> --> ctx.request.path --> /signalr/js/js/reconnect
> --> owinRequestUri.Path --> /signalr/js --> requestPathBase --> -->
> ctx.request.path --> /signalr/js --> owinRequestUri.Path -->
> /signalr/negotiate --> requestPathBase --> --> ctx.request.path -->
> /signalr/negotiate --> owinRequestUri.Path --> /connect -->
> requestPathBase --> --> ctx.request.path --> /connect -->
> owinRequestUri.Path --> /connect --> requestPathBase --> -->
> ctx.request.path --> /connect --> owinRequestUri.Path -->
> /signalr/abort --> requestPathBase --> --> ctx.request.path -->
> /signalr/abort
>
> Without "patch" and setting requestPathBase to "/". SignalR
> doesn't work.


> --> owinRequestUri.Path --> signalr/js --> requestPathBase --> / -->
> ctx.request.path --> /signalr/js
>
> With "patch" and setting requestPathBase to "".  SignalR works.


> --> owinRequestUri.Path --> /signalr/js --> requestPathBase --> -->
> ctx.request.path --> /signalr/js --> owinRequestUri.Path -->
> /signalr/js/negotiate --> requestPathBase --> --> ctx.request.path -->
> /signalr/js/negotiate --> owinRequestUri.Path -->
> /signalr/js/js/connect --> requestPathBase --> --> ctx.request.path
> --> /signalr/js/js/connect --> owinRequestUri.Path -->
> /signalr/js/start --> requestPathBase --> --> ctx.request.path -->
> /signalr/js/start
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/SuaveIO/suave/issues/547#issuecomment-268562409

**Comment by ademar** [comment]
> Guess I could work around by having suave redirect /connect calls to
/signal/connect


That would be cheating! :)

**Comment by robertpi** [comment]
That would be a nice hack :)



But quite a difficult one, since there doesn't seem to be an easy way to
add the parameters to the redirect in suave, so I guess I'll just wait
for the fix.




On Wed, Dec 21, 2016, at 06:18 PM, Ademar Gonzalez wrote:

>> Guess I could work around by having suave redirect /connect calls to
>>  /signal/connect



> That would be cheating! :)



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/SuaveIO/suave/issues/547#issuecomment-268580542

**Comment by ademar** [comment]
This is fixed now in the latest pre-release.
