### ISSUE TITLE
Suggestion to join .NET Foundation

### ISSUE THREAD

**Issue by Biarity** [SuaveIO/suave#551]
I've been enjoying this very well done library the past few weeks with no regrets. So I was thinking, why isn't Suave a .NET Foundation project? 

Joining the .NET Foundation would be, in my view, really beneficial to Suave. This would promote the project, expose it to a larger audience (which means potentially more contributors), as well as provide legal & financial support.

Suave already meets (exceeds, actually) almost all of .NET Foundation's [criteria](https://github.com/dotnet/home/blob/master/guidance/new-projects.md) so joining would be quite easy.

Both ASP.NET Core & Nancy are already members so it would make sense for Suave to also be one!

Sorry if this is a little misplaced but I thought it would be an excellent opportunity. (Note: I have nothing to do with the .NET Foundation, just making a suggestion).

**Comment by ademar** [comment]
Thanks for the suggestion but we have other plans for Suave.
