### ISSUE TITLE
How to change ip address of server?

### ISSUE THREAD

**Issue by DonSchenck** [SuaveIO/suave#554]
Suave defaults to 127.0.0.1

How do I change that? #

**Comment by adamchester** [comment]
@DonSchenck you modify the configuration with different bindings, like this: https://github.com/SuaveIO/suave/blob/master/examples/Example/Program.fs#L205

**Comment by haf** [comment]
https://suave.io/binding.html too

**Comment by haf** [comment]
I think this is sufficiently documented.

**Comment by DonSchenck** [comment]
Got it! Thanks!
