### ISSUE TITLE
.Net Core merge nupkg broken

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#557]
```
    ├── lib
    │   ├── net40
    │   │   ├── Suave.2.0.0-dotnetcli.nupkg
    │   │   ├── Suave.2.0.0-dotnetcli.symbols.nupkg
    │   │   ├── Suave.dll
    │   │   ├── Suave.dll.config
    │   │   ├── Suave.dll.mdb
    │   │   └── Suave.xml
    │   └── netstandard1.6
    │       └── Suave.dll
    └── package
        └── services
            └── metadata
                └── core-properties
                    └── coreProp.psmdcp
```

@enricosada May I ask you to have a look at it? The line in question is `system dotnet_exe_path, %W|mergenupkg --source "#{sourcenupkg}" --other "#{clinupkg}" --framework netstandard1.6` but that command doesn't actually tell me what folder it's placing the nupkg in.

This affects release v2.0 (and presumable all the RCs as well).

**Comment by ademar** [comment]
I have published new nugets that do not have this problem. Basically I had forgotten to clean my build before packaging.
