### ISSUE TITLE
Suave 2.0 can't be included on a .net 4.6 project

### ISSUE THREAD

**Issue by baronfel** [SuaveIO/suave#559]
Hi!

I have a project I'm using Suave on that targets .net 4.6 on mono 4.6.2, and when I add Suave 2.0 and build, I get the following build error:

```
"Q:\Experiments\pano-stitcher-dotnet\tests\pano.tests\pano.tests.fsproj" (Build target) (1) ->
      "Q:\Experiments\pano-stitcher-dotnet\src\pano\pano.fsproj" (default target) (2) ->
      (ResolveAssemblyReferences target) ->
        C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary refe
      rence "Suave" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a hig
      her version than the currently targeted framework ".NETFramework,Version=v4.6". [Q:\Experiments\pano-stitcher-dotnet\src\pan
      o\pano.fsproj]
```

What I'm seeing is that a 4.6 project can include Suave, but the assembly cannot actually be referenced via msbuild until the project is retargeted to 4.6.1.

I was able to work around this by retargeting my project to 4.6.1, but I think it would be better to either rebuild suave to target 4.6, or don't let it be installed to projects targeting 4.6.

I am using paket to manage my dependencies, and the msbuild include syntax it generates seems fine and in line with all of my other dependencies.

**Comment by isaacabraham** [comment]
Same here - I tried a net40 console app and a 452 console app - whilst NuGet pulls down the package (because the package is net40), nothing shows up because it's in reality 461 upwards.

Either the package should be changed to 461 explicitly, or the library should be downgraded back to 40.

**Comment by haf** [comment]
Tracked by [this issue](https://github.com/Albacore/albacore/issues/148)

**Comment by ademar** [comment]
I have just published v2.0.1 targeting .NET 4.6; please give it a try. Thanks.

**Comment by forki** [comment]
2.0.1 still doesn't work for NET 452 and below

**Comment by haf** [comment]
@forki That is correct and intended.

**Comment by forki** [comment]
Then why do you put a net40 lib into the nupkg?

Am 18.01.2017 13:01 schrieb "Henrik Feldt" <notifications@github.com>:

**Comment by haf** [comment]
https://github.com/Albacore/albacore/issues/148

**Comment by isaacabraham** [comment]
@haf don't understand :-) can you explain for the simpletons like me.

**Comment by adamchester** [comment]
@isaacabraham Suave is compiled for net46 now, but a bug in the build tools puts the dll in the wrong folder inside the nuget package. This bug confuses some end users and tools, but works ok if you are targeting >=net46

**Comment by chinwobble** [comment]
Looks like PR #566 allowed me to compile an app with suave with .NET Framework 4.6. 

@adamchester is there anything we can do to fix the bug you mentioned or is it independent on fixing a bug in a upstream dependency?

**Comment by adamchester** [comment]
@chinwobble yes it's part of albacore. hopefully somebody will help with https://github.com/Albacore/albacore/issues/148

**Comment by haf** [comment]
Albacore #148 has been resolved thanks to @danieljsummers 

Releasing v2.1.1 now if dotnet core will let me :)
