### ISSUE TITLE
Managing Session State between Server restarts and two different browser sessions

### ISSUE THREAD

**Issue by tamizhvendan** [SuaveIO/suave#569]
I am using `statefulForSession` and `HttpContext.state` to persist the user login status in a browser session, and it works as expected. 

However, either if I restart the `suave webserver` or `quit and restart the browser`, the persisted login status is no longer available, and I need to log in again 

Here is a code snippet of the code base

### Combinators to set state

```fsharp
let sessionSet failureF key value = 
  statefulForSession
  >=> context (fun ctx ->
                match HttpContext.state ctx with
                | Some state -> state.set key value
                | _ -> failureF
              )

let sessionGet failureF key successF = 
  statefulForSession 
  >=> context (fun ctx ->
                match HttpContext.state ctx with
                | Some store -> 
                  match store.get key with
                  | Some value -> successF value
                  | _ -> failureF
                | _ -> failureF
  )

let clearSession = 
  unsetPair SessionAuthCookie
    >=> unsetPair StateCookie
```

### Setting State Upon Successful Login

```fsharp
let userCookieName = "fstweet_user"

let loginSuccess (user : User) =
  authenticated Cookie.CookieLife.Session false      
    >=> sessionSet (redirectToLoginPage "unable to login") userCookieName user
    >=> Redirection.FOUND ("/" + user.Username.Value)
```

### Authentication to show User Profile

```fsharp
let secured onFail webpart = 
  sessionGet onFail userCookieName webpart

let renderUserProfilePage username =
  let renderProfile' (user : User) =
    page "user_profile.liquid" (toProfileViewModel user)
  secured (Redirection.FOUND loginPath) renderProfile'
```

Here are the requirements that I'd like to figure it out

1. If two suave server instances of the same application running behind a load-balancer, how can we seamlessly manage the session state irrespective of which instance is responding to the request?

2. I understand `statefulForSession` is meant for a browser session but is there a way where I persist the cookies between browser restarts?

**Comment by haf** [comment]
1. You set the configuration's `serverKey`.
2. Yes, instead of the default `Session` longevity you choose a timespan. See the `Cookie` module's types.

**Comment by tamizhvendan** [comment]
Thanks, @haf both suggestions worked like a charm!
