### ISSUE TITLE
NullReferenceException on request body for DELETE method

### ISSUE THREAD

**Issue by dedale** [SuaveIO/suave#583]
# Description
When handling DELETE Rest requests, I want to get inputs from request body.
But request body is empty.
I would expect this to work the same way as POST requests.

# Repro steps
```fs
open Hopac
open HttpFs.Client
open Newtonsoft.Json
open Newtonsoft.Json.Serialization
open Suave
open Suave.Filters
open Suave.Operators
open Suave.Successful
open System
open System.Text
open System.Threading
open System.Net
open System.Net.Sockets

type ClientId = 
    { value : Guid }

type ItemId = 
    { value : int }

let findPort() = 
    let tcpListener = TcpListener(IPAddress.Loopback, 0)
    tcpListener.Start()
    let port = (tcpListener.LocalEndpoint :?> IPEndPoint).Port
    tcpListener.Stop()
    uint16 port

let toJson x = 
    let settings = new JsonSerializerSettings()
    settings.ContractResolver <- new CamelCasePropertyNamesContractResolver()
    JsonConvert.SerializeObject(x, settings)

let JSON x = toJson x
             |> OK
             >=> Writers.setMimeType "application/json; charset=utf-8"
let fromJson<'a> json = JsonConvert.DeserializeObject(json, typeof<'a>) :?> 'a

let getResource<'a> (req : HttpRequest) = 
    let getString bytes = Encoding.UTF8.GetString(bytes)
    req.rawForm
    |> getString
    |> fromJson<'a>

let badRequest = RequestErrors.BAD_REQUEST "Resource not found"

let parts() = 
    let tryHandle (client, item) = Some true
    
    let handle requestError body = 
        function 
        | Some _ -> body |> OK
        | _ -> requestError
    
    let part body = 
        request (getResource
                 >> tryHandle
                 >> handle badRequest body)
    
    path "/route" >=> choose [ POST >=> (part "Posted!")
                               DELETE >=> (part "Deleted!") ]

[<EntryPoint>]
let main argv = 
    use cts = new CancellationTokenSource()
    let binding = HttpBinding.create Protocol.HTTP IPAddress.Loopback (findPort())
    
    let conf = 
        { defaultConfig with cancellationToken = cts.Token
                             bindings = [ binding ] }
    
    let listening, server = startWebServerAsync conf (parts())
    Async.Start(server, cts.Token)
    let url = (sprintf "%A://%A" binding.scheme binding.socketBinding.endpoint).ToLowerInvariant()
    let client = { ClientId.value = Guid.NewGuid() }
    let item = { ItemId.value = 42 }
    for httpMethod in [ Post; Delete ] do
        let body = 
            Request.createUrl httpMethod (url + "/route")
            |> Request.bodyString (toJson (client, item))
            |> Request.responseAsString
            |> run
        printfn "body: %s" body
    cts.Cancel()
    0
```

# Expected
Output of code above should be:
> [20:52:33 INF] Smooth! Suave listener started in 25.521 with binding 127.0.0.1:50027
> body: Posted!
> body: Deleted!

# Actual
> [20:53:23 INF] Smooth! Suave listener started in 27.028 with binding 127.0.0.1:50030
> body: Posted!
> [20:53:24 ERR] request failed
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Tuple`2.get_Item1()
>    at Program.tryHandle@47TT.Invoke(Tuple`2 tupledArg) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 47
>    at Program.part@55-2.Invoke(HttpRequest x) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Program.part@55-3.Invoke(HttpRequest x) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
>    at Program.part@55-4.Invoke(HttpContext context) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)
> body: \<h1\>Object reference not set to an instance of an object.\</h1\><br/>System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Tuple`2.get_Item1()
>    at Program.tryHandle@47TT.Invoke(Tuple`2 tupledArg) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 47
>    at Program.part@55-2.Invoke(HttpRequest x) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Program.part@55-3.Invoke(HttpRequest x) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
>    at Program.part@55-4.Invoke(HttpContext context) in D:\prog\_sandbox\SuaveDelete\SuaveDelete\Program.fs:line 55
>    at Microsoft.FSharp.Control.AsyncBuilderImpl.args@835-1.Invoke(a a)

# Versions
```
  <package id="FSharp.Core" version="4.0.0.1" targetFramework="net452" />
  <package id="Hopac" version="0.3.21" targetFramework="net452" />
  <package id="Http.fs" version="4.1.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="Suave" version="2.0.4" targetFramework="net452" />
```

**Comment by ademar** [comment]
Is it possible HttpFs is not sending the body ? cc @haf

**Comment by dedale** [comment]
Body sent only for POST/PUT methods?
https://github.com/haf/Http.fs/blob/5f274f5308f5d4135e5592820049a53f561014f6/HttpFs/HttpFs.fs#L709

**Comment by haf** [comment]
https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Comment by haf** [comment]
I'd say; PR the change to add "DELETE" to Http.fs's ifstatement.

**Comment by dedale** [comment]
Thanks @haf , I'll try to do that PR with a unit test. So my issue is not related to Suave. Closing.
