### ISSUE TITLE
HttpCookie.create with "SameSite" flag as CSRF protection?

### ISSUE THREAD

**Issue by Dzoukr** [SuaveIO/suave#589]
Hi guys,

I know that support for all browsers is still [not 100%](https://www.chromestatus.com/feature/4672634709082112) (if ever will), but I thing we should think about adding possibility to create HttpCookie with `SameSite` flag (having `Lax` or `Strict` options) to increse security and prevent CSRF attack.

What do you think about this? Is it something worth PR?

**Comment by haf** [comment]
Yes, it's definitely worth PRing.

**Comment by haf** [comment]
Merged.
