### ISSUE TITLE
The namespace or module 'Log' is not defined

### ISSUE THREAD

**Issue by davidpodhola** [SuaveIO/suave#591]
On a clean machine when running `build.cmd`, it fails with

`suave\src\Suave\Sockets\BufferManager.fs(18,23): error FS0039: The namespace or module 'Log' is not defined`

This is because in the `src/Logary/Logary.Facede/Façade.fs` it is `Logary.Facade` now. Will do a PR.

**Comment by ademar** [comment]
Because you need to run the Rake build script instead.

**Comment by davidpodhola** [comment]
Then this needs to be fixed I assume (?)

![capture](https://cloud.githubusercontent.com/assets/436605/24082999/2b0ea9b2-0ccf-11e7-80c4-b965823630d2.PNG)

**Comment by ademar** [comment]
Yes it is incorrect, funny it has been rewritten many times and it is still
incorrect.
