### ISSUE TITLE
ctx.request.url returns http://0.0.0.0:8083/ instead of http://localhost:8083/

### ISSUE THREAD

**Issue by pavelhritonenko** [SuaveIO/suave#592]
I'm looking for a way to make a relative link and return it in the response.

Thought about a webpart with code like:

    fun ctx -> OK <| new System.Uri(ctx.request.url, relativePath).ToString()

But it returns http://0.0.0.0:8083/relativePath instead of http://localhost:8083/relativePath
In `ctx.request.host` I have correct `localhost` value

**Comment by haf** [comment]
But then you're building an absolute link?

**Comment by pavelhritonenko** [comment]
Yes, I need an absolute link. I'm only concerned about having binding details in `ctx.request.url` instead request's data.

**Comment by haf** [comment]
Are you looking for the hostname of the request? What if you have a reverse proxy? What if it's being faked by the client? What if the host has multiple names?

Anyway, if you "just want it to work" then you have a property on the request called [clientHostTrustProxy](https://github.com/SuaveIO/suave/blob/master/src/Suave/Http.fs#L390).

Having the binding information in the url is the most correct version since you don't know the deployment configuration from the web server.

**Comment by pavelhritonenko** [comment]
> Are you looking for the hostname of the request?

Yes, the hostname that was in the client's requests.

> What if it's being faked by the client?

Did you mean the situation when a client changed "host" header? It's ok in my case.

> What if the host has multiple names?

But the client mentioned particular one, no? And it is in 'ctx.request.host` field.

> Having the binding information in the url in the url is the most correct version since you don't know the deployment configuration from the web server.

I don't want to know deployment configuration, I only want to know which domain my client visited (with port# and protocol).

I don't understand how binding-information could be used. `http://0.0.0.0:8083/` couldn't even be opened from the browser, and it is the content of `ctx.request.url`.

**Comment by haf** [comment]
> I don't understand how binding-information could be used.

The binding information is useful from the node that the server runs on. Quite often one spawns a few sidekicks running e.g. health checks that then a consul client polls on localhost/0.0.0.0.

Anyway, there's a link above to the info you need, and then if you want to get the port/IP, that's here https://github.com/SuaveIO/suave/blob/master/src/Suave/Http.fs#L563

Also, 8083 is v1, you probably want v2 of Suave.

**Comment by pavelhritonenko** [comment]
> Put them all in the UriBuilder and there you go.

Thanks, have done it already

> health checks that then a consul client polls on localhost/0.0.0.0

How does the consul client use information that available only inside Suave code?

It confused me because for example for IIS-hosted WebApi or self-hosted WebApi it is the simplest way to get absolute urls those make sense for the client inside the app. For example, if I want to send an email with absolute url.

**Comment by haf** [comment]
The information could be used to [place a healthcheck in Consul](https://github.com/logibit/Fakta). But the ability to call a binding is the invariant we/I was after, not necessarily the utility of being able to call it. It also signals that you can have many-hosts per Suave app which is useful in an of itself, but also that the information is not immediately available to the Suave app which could be intended to be deployed on cloud infrastructure where your load balancer or CMDB (configuration mangement database) is the only source of the truth about the host-names.

**Comment by pavelhritonenko** [comment]
Thanks, I've understood it. What in this case is the best way to send and email with the absolute url?

`clientPortTrustProxy` seems like contains the client's port, not the server's one.

**Comment by pavelhritonenko** [comment]
And just for prevention of such queries (hope it would be able to google) - in my situation in production (suave behind the nginx) there is no way to get host/port of original query, so the only thing is to put these settings into config on build.

**Comment by haf** [comment]
Well, your production use-case is identical to what Suave has (also) been designed for; it's why the API mentions the proxy. The header string I linked to ("x-forwarded-host") is what you make [nginx send](https://plone.lucidsolutions.co.nz/web/reverseproxyandcache/setting-nginx-http-x-forward-headers-for-reverse-proxy)
