### ISSUE TITLE
ctx.clientPort / ctx.clientTrustPort contain wrong values

### ISSUE THREAD

**Issue by pavelhritonenko** [SuaveIO/suave#594]
In context `clientPort` fields we have either value of header `x-forwarded-port` or `ctx.connection.port`:

https://github.com/SuaveIO/suave/blob/6033acfe8b858c9984dd3de094a423c0d504c126/src/Suave/Http.fs#L550-L561

According to specification `x-forwarded-port` contains port that client used to connect to balancer (proxy), however in `ctx.connection.port` we have different values for each connection:

    === /ping
    ctx.connection.port: 56751
    === /ping
    ctx.connection.port: 56751
    === /ping
    ctx.connection.port: 56751
    === /ping
    ctx.connection.port: 56779

I assume there is client's socket port value.

**Comment by haf** [comment]
`ctx.connection.port` is the (reverse proxy) client's TCP connection as seen from the server, by design. `x-forwarded-port` is the port the (user) client initially connects to. Only a server can tell the port the client connected to, so `x-forwarded-port` contains the reverse proxy server's view of where the client connected (which it knows for sure). Suave's server listen is in the config.bindings value – and can contain multiple ports.

So this is not an issue.

**Comment by pavelhritonenko** [comment]
I'm coping with Suave-Hawk authentication and see the `clientPortTrustProxy` behaves differently when deployed (beyond nginx, it uses `x-forwarded-port` and the value is 443) and on my local machine, where there is no nginx - in this case there is no `x-forwarded-port` header and it returns `x.connection.port`, and on my local machine it is changed with each tcp-connection, as in the console dump in initial question.

And Logibit Hawk returns auth error either on dev-machine or when deployed. Now it returns correct host-name (it takes it either from `x-forwarded-host` or from `host` header - localhost).

    let settings =
        { Settings.empty<UserSession>() with
            credsRepo = readCredentials
            useProxyHost = true
            useProxyPort = true }

It works when deployed behind Nginx and doesn't work locally (direct connection from the client):

    Unauthorized: BadMac
      ("a76Zlbz0zEXjkY/GE4quY95TA9l6ASN4F7fhfCoanS4=",
       "1vl7/YXytUWm7tkjBqs+e8h+IwKo9YQlktMdldAa7uU=",
       "hawk.1.header
    1490346534
    nMXe2i
    GET
    /api/backups
    localhost
    59562
    
    
    ")

Notice `59562` - I think it should be a real port that client connected to (and this value is part of MAC), 8083 in my case. If I change `useProxyPort = true` to false - it fails on the prod, but works locally, when the client is connecting to 8083 and we listen 8083. So the bug either in Logibit.Hawk or in Suave.

**Comment by pavelhritonenko** [comment]
Ok, looked at code - `suave.hawk` doesn't use `ctx.clientPortTrustProxy` when `useProxyPort = false`.
So I can assume that `clientPortTrustProxy` returns strange `5xxxx` port when it used locally on dev machine, and returns correct port that client connected to (via `x-forwarded-port` header).
