### ISSUE TITLE
Off-by-1 error in new Content-Range code

### ISSUE THREAD

**Issue by rmunn** [SuaveIO/suave#596]
I'm glad to see the new Content-Range code, but I believe there's an off-by-1 error in the headers it sends. The [`sendFile` function](https://github.com/SuaveIO/suave/blob/d997c52f19bcbf311e6b953f0de00e879771d8bf/src/Suave/Combinators.fs#L527) currently sends a `Content-Range` header specifying the range from `start` to `start + fs.Length`, so if we're sending 500 bytes starting at index 0, it would send `Content-Range: bytes 0-500/*`, and 500 bytes starting at index 500 would be `Content-Range: bytes 500-1000/*`. But [the HTTP spec for Content-Range](https://tools.ietf.org/html/rfc7233#section-4.2) specifies the end of the range as "`last-byte-pos`", and the examples show sending 500 bytes by using `Content-Range: bytes 0-499/*` or `Content-Range: bytes 500-999/*`. I believe the end byte in the Content-Range should be calculated as `start + fs.Length - 1` to comply with the HTTP spec. (Two changes needed in `sendFile` as it is currently written).

Note that I have not yet tested this with actual browsers, so I don't know if this is a serious error or if browsers would be able to work around it. This is based simply on reading the code and the HTTP spec.

**Comment by ademar** [comment]
ping @simonhdickson

**Comment by simonhdickson** [comment]
Ah yes, I haven't noticed any issues with browsers but it's likely still worth correcting.
