### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by nojaf** [SuaveIO/suave#603]
As discussed in https://github.com/dustinmoris/Giraffe/issues/32, I'd like to port [Html.fs](https://github.com/SuaveIO/suave/blob/master/src/Experimental/Html.fs) to Giraffe.

I understand that Suave has an [Apache 2 license](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) so that shouldn't be a problem as long as I include all necessary links/texts/rights to Suave.

Could somebody point me in the right direction what I should do to make this concrete?

**Comment by ademar** [comment]
@nojaf You can copy it no problem.

**Comment by nojaf** [comment]
Thanks
