### ISSUE TITLE
how to change port

### ISSUE THREAD

**Issue by hanbindsg** [SuaveIO/suave#604]
how to ？ change   127.0.0.1:8080   to   127.0.0.1:80

**Comment by haf** [comment]
Like this https://suave.io/binding.html

**Comment by hanbindsg** [comment]
let routes =
    
  { defaultConfig with
      bindings =
        [ HttpBinding.create HTTP IPAddress.Loopback 80us
          HttpBinding.createSimple HTTP "10.0.1.34" 9000 ]
      listenTimeout = TimeSpan.FromMilliseconds 3000. }
    GET >=> choose
        [path "/hello" >=> OK "hello "
         path "/time" >=> OK myTime
         path "/bye" >=> OK "Goodbye World"]
         
[<EntryPoint>]
let main argv =
    printfn "hello world"
    startWebServer defaultConfig routes


会报错啊

**Comment by haf** [comment]
Yes? I don't read Chinese.
