### ISSUE TITLE
Bump to Suave 2.1.0

### ISSUE THREAD

**Issue by sjalowoi** [SuaveIO/suave#605]
Hi, 

I have a dependencies problem with Suave.DotLiquid, it depends of Suave 2.0.1 for Dotnetcore version. Is it possible to bump to Suave 2.1.0 version and release a new Suave.DotLiquid Nuget package ? 

Thanks in advance,
Sylvain

**Comment by sjalowoi** [comment]
Hi, 
I see your pullrequest, thank you. 
Do you have an idea of when you will be able to deliver a new version of the package?
Sylvain

**Comment by ademar** [comment]
Sorry i did not continue cause it did not work -- something needs to be
changed in the build script and i dont have the time now.

I'll give it another try later unless somebody else fixs it.

**Comment by enricosada** [comment]
@ademar maybe #624 will fix the build script error
