### ISSUE TITLE
Is version 2.1 incompatible with previous versions?

### ISSUE THREAD

**Issue by pnowosie** [SuaveIO/suave#607]
Please consider [Fibonacci example](https://github.com/SuaveIO/suave/blob/master/examples/Fibonacci/Program.fs). When I run with Suave 2.0.5 everything works OK.
Once switched to 2.1.0 I got compilation error in line "open Suave": 
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0039	The namespace or module 'Suave' is not defined.	Fibonacci	C:\Proj\fsharp\Fibonacci\Program.fs	1	Active

I'm running on Windows 10, VS2017, .NET 4.5.2, resolving nuget package within VS.

Is nuget package for 2.1.0 corrupted or this version is backward incompatible? Thank you!

**Comment by haf** [comment]
It's not backward incompatible.

Cannot reproduce:

```zsh
➜  suavesample monodis --assembly ../packages/Suave/lib/net40/Suave.dll
Assembly Table
Name:          Suave
Hash Algoritm: 0x00008004
Version:       2.1.0.0
Flags:         0x00000000
PublicKey:     BlobPtr (0x00000000)
	Zero sized public key
Culture:

➜  suavesample ./sample.fsx
[22:00:15 INF] Smooth! Suave listener started in 97.804 with binding 127.0.0.1:8080
➜  suavesample cat sample.fsx
#!/usr/bin/env fsharpi

#I "../packages/Suave/lib/net40"
#r "Suave"
open Suave

startWebServer defaultConfig (Successful.OK "HI")
```

Please create a repro project. This is the first I've heard of this problem and 2.1 has been out 10 days.

**Comment by pnowosie** [comment]
@haf I found what was wrong in my project - Target framework was set to 4.5.2 and Suave.2.1.0 dll from nuget is built with .NET Framework 4.6. In that case dll is not loaded and that's the cause of the issue.

Anyway, I wonder it is ok for you. Nuget package suggest it's for .Net 4.0 - but latest is required(?)

**Comment by haf** [comment]
See https://github.com/Albacore/albacore/issues/148

**Comment by haf** [comment]
v2.7.0 has been released of albacore thanks to @danieljsummers – it's now possible to bump the dependency here in Suave and avoid strangeness like in this issue.
