### ISSUE TITLE
statefulForSession throws InvalidDataContractException

### ISSUE THREAD

**Issue by danieljsummers** [SuaveIO/suave#608]
I've added "statefulForSession" in front of my `choose` for routes, and I'm now seeing the following error when I try to go to the home page of my application.

```
[07:43:17 WRN] TCP request processing failed
System.Runtime.Serialization.InvalidDataContractException: Type
'Microsoft.FSharp.Collections.FSharpMap`2[System.String,System.Object]' cannot be serialized. Consider
marking it with the DataContractAttribute attribute, and marking all of its members you want serialized
with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a
parameterless constructor - all public members of the type will then be serialized, and no attributes will
be required.
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at Suave.JsonFormatterSerialiser.Suave-CookieSerialiser-serialise(FSharpMap`2 m)
   at Suave.State.CookieStateStore.stateful@82-2.Invoke(Unit unitVar0)
   at Suave.Cookie.cookieState@236.Invoke(HttpContext ctx)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at Suave.Operators.op_GreaterEqualsGreater@7.Invoke(a arg20@)
   at Suave.ParsingAndControl.loop@72-221.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
```

The code is in [this repository](https://github.com/danieljsummers/myPrayerJournal), and my call to `statefulForSession` (aliased to `session`) is part of [this function](https://github.com/danieljsummers/myPrayerJournal/blob/d34302aa5243b59e0ee3148488226786620fa547/src/App.fs#L88).

(This is on Windows 10 64-bit, `dotnet --version` = `1.0.2`, Suave 2.0 due to the version issue described in #605.)

**Comment by ademar** [comment]
There is no binary serialization in .NET Core, we need to find a workaround.

**Comment by danieljsummers** [comment]
Would that be [this serialization code](https://github.com/SuaveIO/suave/blob/master/src/Suave/CookieSerialiser.fs)?

**Comment by danieljsummers** [comment]
It does look like it's [coming back for netstandard 2.0](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryFormatter.cs).  If the framework itself will fix this by November (I think that's the 2.0 RTM plan), there's probably not a good reason for a really involved workaround.  _(Digging through the history on this issue - what an interesting mess...)_

Maybe a short-term fix would be to implement it with JSON.NET (I know the project is probably trying to actively avoid that dependency), then undo it once 2.0 is targeted.  If you think that might work, I wouldn't mind playing around with it in my fork, and submit a PR if it works.

In my particular case, I'm just wanting to keep track of the JWT I'm getting back from Auth0.  From what I've read, it seems that a cookie is the only way to do that for a non-SPA application.  If there's a different way, though, feel free to point me in that direction.

**Comment by danieljsummers** [comment]
The more I think about that middle paragraph above, it's... not ideal.  Probably the biggest issue I see is that cookies serialized with "workaround" code couldn't be deserialized with the replacement code.  That would be a rude side-effect.

**Comment by haf** [comment]
But it's configurable https://github.com/SuaveIO/suave/blob/master/src/Suave/Web.fs#L89 – how about trying to use a custom serialiser and then telling us what works

**Comment by danieljsummers** [comment]
Nice!  I didn't realize that was an option.  The below works, though I haven't been able to verify that a round-trip does, and my test time is over until much later in the day.

```
type JsonNetCookieSerializer() =
  interface CookieSerialiser with
    member x.serialise m =
      Text.Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(m))
    member x.deserialise m =
      JsonConvert.DeserializeObject<Map<string, obj>>(Text.Encoding.UTF8.GetString(m))
```
then

```
let suaveCfg =
  { defaultConfig with
      ...
      cookieSerialiser = new JsonNetCookieSerializer()
    }
```

Once I verify round-trips, this could be a simple workaround.

(It occurred to me, as I was typing, that I was determining round-trip on whether I could decode the JWT I had in the cookie.  I'll use a much less complex approach when I pick it back up.)

**Comment by danieljsummers** [comment]
OK - the above **does** successfully round-trip.  :)  Would this be worth putting in a NuGet package (if not in this project, I could do it as a community one), or should it just be documented as a .NET Core workaround for cookie serialization?  I didn't see a page on the suave.io site for sessions; I ended up learning-by-example with the Suave Music Store.  I could take a stab at writing a page specific for sessions, and mention the .NET Core (< netstandard2.0) gotcha.

**Comment by haf** [comment]
Writing a page specific for sessions where we mention this as well would be a great resource for people looking for help. We'd be very thankful for your help.

**Comment by danieljsummers** [comment]
OK - take a look at [this page](https://github.com/danieljsummers/suave/blob/52e68b3e3ddd9114629304061ff61bffaffee4c3/docs/sessions.md) and let me know if it is accurate.  :)  (Always the fear when you write up something you've recently learned...)

I also put some "raw" Liquid tags around the [DotLiquid documentation page](https://github.com/danieljsummers/suave/commit/52e68b3e3ddd9114629304061ff61bffaffee4c3#diff-eb334fc833e4940e1d62783ea5e5a1cf), as Jekyll is trying to interpret them - it's not [actually showing the tags in the examples](https://suave.io/dotliquid.html).  I also noticed that the API page config doesn't match what's in the source; I haven't updated it yet, but I thought I'd do that while I'm working a doc PR.

**Comment by haf** [comment]
Completed with docs.
