### ISSUE TITLE
Html.fs: need way to avoid HtmlEncode in Text nodes

### ISSUE THREAD

**Issue by vivainio** [SuaveIO/suave#610]
I observed that Text nodes now get HtmlEncode'd:

https://github.com/SuaveIO/suave/commit/9d85fb35a15df708335905c0bb7fbc466287b28a (by @atifaziz).

This is desirable behavior for most cases, but for text in <script> tags this is not wanted.

Type "Node" probably needs to grow a new discriminated union case RawText, that doesn't perform the encoding, to allow creating scripts with 

```fsharp
tag "script" [] <| rawText ("Hello world <<>>")
```

**Comment by vivainio** [comment]
I made a PR for this: https://github.com/SuaveIO/suave/pull/611

**Comment by haf** [comment]
Thanks, I'm rebuilding currently.
