### ISSUE TITLE
Newbie question: map json input but not output

### ISSUE THREAD

**Issue by Kurren123** [SuaveIO/suave#617]
As far as I can tell `mapJson` maps the input JSON to an object into your function, then maps the output of your function into JSON.

The problem is that I'm happy with the way it maps into my function, but I need to return a json string response rather than have suave serialise my output into JSON for me. How can I do this?

Currently i'm getting my output serialised twice. My code so far:

```
let executeQuery : Query -> string = //function here. Query is my json input, the return value is a json string
let app = POST >=> path "/graphql" >=> Json.mapJson executeQuery >=> setMimeType "application/json; charset=utf-8"
startWebServer defaultConfig app
```

Thanks for any help

Edit: [Stackoverflow question](http://stackoverflow.com/questions/44087985/map-json-input-but-not-output-in-suave) as I wasn't sure where to put this or whether it'll get deleted from SO.

**Comment by ademar** [comment]
Closing as question was answered on SO
