### ISSUE TITLE
YoLo should be in a namespace

### ISSUE THREAD

**Issue by matthid** [SuaveIO/suave#632]
Suave should not pollute my namespace just by adding a reference.

In this particular scenario I was trying to figure out why `let! s = someTask` works in an `async` block.
But the IDE (Was using Rider at that particular time) couldn't help me. 

 > Note: I even tried to write `async.Bind(someTask, fun _ -> async { return () }) |> ignore` but the IDE could not navigate to "Bind" nor did it show in the tooltip where `Bind` is coming from.

I wanted to remove the bind for the asyncbuilder in order to change all the places. (as `AwaitTask` of fscore is broken IMHO).

Finally, I figured out that the Bind extension comes from Suave without any `open` because `YoLo` has no namespace and has `AutoOpen`. Just wanted to inform you about this. It is quite unexpected.

**Comment by haf** [comment]
It's supposed to be 

https://github.com/SuaveIO/suave/blob/master/Rakefile#L24

PR to fix/investigate would be appreciated.

**Comment by matthid** [comment]
Yes, I might come back to this eventually, for now I just wanted to track it. Maybe I just need to update Suave. Was this changed recently?

I guess problem is that we have `module YoLo` instead of `module internal YoLo` so it is not replacing anything?

**Comment by haf** [comment]
You're right, I was on the move and just wanted to get you the info. I've updated the rakefile and can release later today. Sorry about the bug.

**Comment by matthid** [comment]
No problem, thanks for the quick response!

**Comment by haf** [comment]
Fixed.
