### ISSUE TITLE
Update DotLiquid dependency

### ISSUE THREAD

**Issue by jimfoye** [SuaveIO/suave#641]
When I pulled down latest DotLiquid (2.0.158) today in my project via Nuget, I started experiencing a type initialization exception in the Suave.DotLiquid module. After doing some detective work, I think (let's say I'm about 95% certain) that this is due to a recent breaking change in DotLiquid. If so, the right thing now might be to specify a minimum version for DotLiquid of 2.0.158. 

I'm still trying to get the hang of Paket. I tried changing the entry in paket.dependencies for DotLiquid to

`nuget DotLiquid ~> 2.0.158`

then I executed

`paket update DotLiquid`

as I only want to update this package. It does update this package, but it also does some other things, like update YoLo. This strikes me as a bit odd, as I'm specifically asking for only DotLiquid to be updated, and I can't draw any kind of line from DotLiquid to YoLo.

So I can't really submit a PR on this, as I seem now to have hit the limit in my packet capabilities.

**Comment by haf** [comment]
You can manually edit out changes to the `paket.lock` so that it only is changed in the place where it talks about DotLiquid. Then run `paket install --redirects`, but don't commit all (see https://github.com/fsprojects/Paket/issues/2616). Instead commit any/all app.configs and `paket.lock` and nothing else.

**Comment by jimfoye** [comment]
@haf, thanks. That packet command doesn't create a binding redirect for DotLiquid, but maybe that's because Suave.DotLiquid doesn't have an app.config, and now needs one? But it does create other binding redirects (Topshelf, BenchmarkDotNet, etc.), and I don't know if these are desired or not.

And I see another problem now - there is a project for .NET Core (Suave.DotLiquid.netcore.fsproj) that paket did not update. Unfortunately, I only build on Windows at present. I was hoping paket would make fixing this issue straightforward, but I need to step aside and let someone else take this now.

**Comment by haf** [comment]
Of course, I understand. But you should never be afraid of filing a PR, even if it's not perfect. What you got sounds like exactly what you should have 👍 

I'll fix it though. Thanks for trying.

**Comment by jimfoye** [comment]
Is 2.2.1 supposed to fix this? FYI, I updated to 2.2.1 but I still can't upgrade DotLiquid past 2.0.145 or I will see the TypeInitializationException again.

**Comment by haf** [comment]
I'm sorry, but .Net Core 2.0 isn't working on my machine; it gives me NullReferenceException when I try to build. And I don't have time right now to debug it. If you could build this project and see if you can run samples using dotliquid, it would be grand.
