### ISSUE TITLE
CPU utilization becomes 100% if WebSocket client has closed connection not gracefully.

### ISSUE THREAD

**Issue by alexey-belous** [SuaveIO/suave#649]
**EDIT See [Bug 53229](https://bugzilla.xamarin.com/show_bug.cgi?id=53229)**

I've used the WebSocket as provided in [this](https://github.com/SuaveIO/suave/tree/master/examples/WebSocket) example and faced up with the following issue:

If WebSocket client has closed connection not gracefully (in my case Nginx closed the connection by timeout) the application process loads 100% CPU.

Example of code that helps to reproduce the issue:
```
let socket settings (ws: WebSocket) (context: HttpContext) =
        let utfBytes (str: string) = Encoding.UTF8.GetBytes str
        let utfStr bytes = Encoding.UTF8.GetString bytes
        let send text =
            async {
                do! ws.send Text (text |> utfBytes |> ByteSegment) true |> Async.Ignore
            }
            |> Async.Start
        let echo msg = send ("Echoing " + msg)

        let mutable loop = true

         socket {
             try
                 send "Hello from server"
                 while loop do
                        let! msg = ws.read()
                        match msg with
                        | (Text, data, true) ->
                            let str = utfStr data
                            echo str
                        | (Close, _, _) ->
                            let emptyResponse = [||] |> ByteSegment
                            do! ws.send Close emptyResponse true
                        | _ -> ()
            }
...
path "/websocket" >=> handShake (socket settings)

```

I've tried to debug it but after a client has closed connection anything of provided code didn't being executed.

The issue is reproduced only on CentOS 7.
Suave version is 2.0.4.
Mono version is 5.4.0

**Comment by alexey-belous** [comment]
After deep investigation I've found new details about this issue:
The cause of CPU loading is that thread cannot leave the loop in this function https://github.com/SuaveIO/suave/blob/1f52f55215eebc44fdea3a0ed8bf49c1a6f8be9f/src/Suave/WebSocket.fs#L145-L154


That's because when client reset connection this SocketError still is Success in the following code:
https://github.com/SuaveIO/suave/blob/1f52f55215eebc44fdea3a0ed8bf49c1a6f8be9f/src/Suave/Sockets/SocketOp.fs#L123-L128

And [here](https://bugzilla.xamarin.com/show_bug.cgi?id=53229) is the corresponding ticket in the Mono bug tracker.

So, as I see, there is no way to fix it on the Suave-side and the ticket can be closed.

**Comment by haf** [comment]
Well researched.

**Comment by alexey-belous** [comment]
@haf, could you please a look on the temporary solution of this issue that I've come up with?

I propose to handle cases when socket returns a few times an empty buffer as refused connections (see code below).

```
  let readBytes (transport : ITransport) (n : int) =
    let arr = Array.zeroCreate n
    let maxFailedAttempts = 10
    let rec loop i failedAttempts = socket {
      if i = n then
        return arr
      else
        let! read = transport.read <| ArraySegment(arr,i,n - i)
        if failedAttempts >= maxFailedAttempts then failwith "Connection reset by peer"
        return! if read = 0 then failedAttempts + 1 else failedAttempts
                |> loop (i+read)
      }
    loop 0 0
```

If you OK with this solution I'll make a pull request.

**Comment by haf** [comment]
@alexey-belous Yes we could add that to the code base. Will you PR it?

**Comment by alexey-belous** [comment]
@haf, I have a few questions. Might I close the issue and when will be released a new version?

**Comment by haf** [comment]
Yes, let's close this issue. I'll see what I can do about releasing an new version shortly.

**Comment by haf** [comment]
OT: You don't happen to have a dotted-version vector implementation in JS, do you?

**Comment by alexey-belous** [comment]
No, I've never worked with it at all :)
