### ISSUE TITLE
VS 15.3 installs NetStandard dependencies for .Net framework project

### ISSUE THREAD

**Issue by plainionist** [SuaveIO/suave#650]
After having installed VS 15.3 when installing suave from package manager console full .net standard dependencies are downloaded.

I started a discussion at nuget which currently proposes to change the dependency modeling in the nuget spec. pls have a look:

https://github.com/NuGet/Home/issues/5871

do u agree to the proposal?

**Comment by haf** [comment]
@plainionist Can you try the beta nuget please? See #638

**Comment by plainionist** [comment]
dependencies for .net fw 4.6.1 project are now as follows:

PM> install-package suave -version 2.3.0-beta -whatif


Attempting to gather dependency information for package 'suave.2.3.0-beta' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 3,93 sec
Attempting to resolve dependencies for package 'suave.2.3.0-beta' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'suave.2.3.0-beta'
Resolved actions to install package 'suave.2.3.0-beta'
Install Argu.3.2.0
Install DotLiquid.2.0.174
Install FSharp.Core.4.0.0.1
Install Microsoft.AspNet.Razor.3.0.0
Install Mono.Cecil.0.9.6.4
Install Expecto.4.0.3 : Argu [3.2.0, ), FSharp.Core [3.1.2.5, ), Mono.Cecil [0.9.6.4, )
Install RazorEngine.3.9.3 : Microsoft.AspNet.Razor [3.0.0, )
Install Suave.2.3.0-beta : DotLiquid [2.0.174, 2.1.0), Expecto [4.0.3, 4.1.0), FSharp.Core [4.0.0.1, 4.0.1), RazorEngine [3.9.3, 3.10.0)
Time Elapsed: 00:00:04.1199801
PM> 

that seems to be ok - at least matches with the dependencies listed on nugget page

thx!

**Comment by haf** [comment]
Sounds good! :)
