### ISSUE TITLE
build.cmd is broken

### ISSUE THREAD

**Issue by vasily-kirichenko** [SuaveIO/suave#652]
```
'tools\paket.bootstrapper.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by vasily-kirichenko** [comment]
And
```
'msbuild' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```

**Comment by haf** [comment]
@vasily-kirichenko It's been moved to `.paket/paket.bootstrapper.exe`. Would you like to PR that fix?

The msbuild one is not an issue. How do you expect to call msbuild if you don't have it on PATH?

**Comment by vasily-kirichenko** [comment]
I expect to run build.cmd with no issues on a machine with .net build tolls installed.

**Comment by haf** [comment]
Ok then, closing as not an issue.

```
I don't use suave and have no plans to use it. I was trying to port some legacy code from suave version 0 to version 2 and gave up.
```

**Comment by vasily-kirichenko** [comment]
I can make a PR that removes build.cmd. Should I?

**Comment by haf** [comment]
I updated the command and readme in build.cmd. Having msbuild on path is doable if you know how a computer works, so it should work with VS Developer Console, which I presume someone who intends to compile a software like this knows how to use.
