### ISSUE TITLE
Question about injecting/passing per request dependencies

### ISSUE THREAD

**Issue by lambdakris** [SuaveIO/suave#653]
I was wondering if there is a technique for injecting or passing per request dependencies along the request pipeline, or even if this makes sense within the context of Suave? I know the code below doesn't accomplish what I'm asking but it's sort of how I could imagine it working, is there a way to accomplish something along these lines?

```
let handleGet (sql: SqlConnection) (http: HttpContext) =
    ...
let handlePost (sql: SqlConnection) (http: HttpContext) =
    ...

let endpoints = 
    use sql = new SqlConnection(...)
    choose [ 
        path "/" >=> choose [
            GET >=> request (handleGet sql) 
            POST >=> request (handlePost sql)
        ]
    ]

startWebServer defaultConfig endpoints
```

**Comment by haf** [comment]
You have the right idea. The more "static/global" things go at the front of the parameter list of functions.

`startWebServer` and its cousin, `startWebServerAsync`, both support taking a CancellationToken, which is Disposable.

Similarly, you connection is.

So you normally block on SIGINT and when that happens, let loose the semaphore you were waiting for and go ahead and dispose/exit the process.

**Comment by lambdakris** [comment]
Ok, your comment is clearing up a couple of different things in my head that I had not yet worked out for myself. 
- There is controlling the lifetime of the webServer
- Then there is controlling the lifetime of dependencies global to the webServer
- Both these things can be done with the use of a CancellationToken
- Of course, regardless of the host process, shutdown events/signals are never a guarantee, so if possible, best not write your app in such a way that it is necessary to gracefully shutdown in order to avoid corruption
- Finally there is per request dependencies, which after a more carefull read through the docs and thinking about the WebPart type and the combinators, I realized that things like the following are possible:
```
let endpoints = 
    context (fun http -> 
        let input = http.request.rawQuery
        choose [
            path "/" >=> OK (sprintf "/ says echoes %s" input)
            path "/foo" >=> OK (sprintf "foo echoes %s" input)
            path "/bar" >=> OK (sprintf "bar echoes %s" input)
        ]
    )
```
So you can build up webparts inside other webparts and return them.

As to whether this is a good idea w.r.t. 1) maintainability, and 2) performance, I have yet to discern. Since I don't think I've seen use of this pattern in any of the tutorials or presentations I've seen so far, I get the impression that it might have some downsides that I have not yet comprehended.

Nevertheless, thanks for prompting me to think about what is happening a bit more. I'm really appreciating Suave so far.

**Comment by haf** [comment]
@lambdakris I'm happy to hear that. We've built qvitoo similar to how you're describing.

There is one aber that you should consider with the code sketch you gave: if you re-create the routes and all functions every request, you'll start churning a lot of GC; so the global state you need – the connection should be created once and passed into the route factory function `endpoints` so that you get a singleton value `endpoints` that is of type `WebPart`. Then you extract 'live' data as close to the invocation (send e-mail, write to DB, or perform side-effect) as possible, to avoid unnecessary churn.
