### ISSUE TITLE
When serving a compressed file, does Suave need to set an old expiration date?

### ISSUE THREAD

**Issue by jimfoye** [SuaveIO/suave#659]
I don't know if this needs to be done or not, and I'm sure yet of all the particulars. I just want to call attention to it in case it's been missed.

According to various MSDN docs, IIS will set a default expiration date of Jan. 1, 1997 on compressed files.

For example, see [https://www.microsoft.com/technet/prodtechnol/WindowsServer2003/Library/IIS/25d2170b-09c0-45fd-8da4-898cf9a7d568.mspx?mfr=true](url)

> When you enable HTTP compression, compressed files are given a default expiration date of Jan. 1, 1997. This expiration date prevents proxy servers from serving cached copies of compressed files to browsers that are not compression-enabled. This expiration date also forces browsers to return to the server for a fresh copy of the file when the user makes a new request instead of displaying a cached copy of the file.

**Comment by ademar** [comment]
Closing.  We leave up to the user to control this behaviour via Cache-Control headers.
