### ISSUE TITLE
userData not working behind nginx reverse proxy

### ISSUE THREAD

**Issue by V1nzi** [SuaveIO/suave#660]
Hello,

I'm trying to setup an application with suave as webserver behind an nginx reverse proxy. Everything works except for the userData/userState. I use this to return errors/infos/warnings etc. to the user after a redirect.
But the messages  are not even set to the userData when requesting the application. Or I guess they are set at first, but no longer there immediately after the app redirects you. It works fine when requesting the app directly, without the reverse proxy.
I can reproduce this error just by running the app locally and sending my requests over a local nginx server, which then serves it to suave. I've tried fiddling with the nginx config, debugging, changing some settings etc.

My Setup:

* Arch Linux
* Mono 5
* nginx 1.12.1
* Suave 2.2.1

nginx.conf:
```
events {
  worker_connections 768;
}

http {
    server {
        listen 1337 ssl http2;

        ssl_certificate_key /etc/nginx/certs/lns.pem;
        ssl_certificate /etc/nginx/certs/cacert.pem;
        location / {
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwared-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass_header Set-Cookie;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_pass http://127.0.0.1:8088;
        }
    }
}
```

I hope you can help me with this.

**Comment by haf** [comment]
We primarily assume that your app is stateless; why not put it in a cookie?

**Comment by V1nzi** [comment]
I am using statefulForSession for all of my routes, which sets the st and st-client cookie. Like this:
```
let app =
    statefulForSession >=>
    choose [
        //possible paths
    ]
```
Is that what you mean?

**Comment by V1nzi** [comment]
Well, I've got an workaround now, where I put such data in an extra cookie, but I'm not sure that this is how it's supposed to work.
It says in the docs, that you can put data into the http context's userState property, which lasts there for the duration of one request. However this doesn't work in my case with the nginx as a reverse proxy. The data is not there when I want to obtain it after a redirect.

**Comment by haf** [comment]
@V1nzi I think that when you're not using nginx, you have a keep-alive session and thus trigger #647 but with nginx you get two requests; one first that you send 301 back to, then another one for the location in the 301.

Are you expecting to only use a single suave server instance? And what happens if that instance crashes?

This is off the beaten path, because designing stateful HTTP servers is an anti-pattern...

**Comment by V1nzi** [comment]
Hm ok, thanks for the help regarding nginx.

It's a small application I'm building for only a limited amount of users and you have to log in before you can do anything.
For implementing the login I used [the music store tutorial](https://theimowski.gitbooks.io/suave-music-store/content/en/auth_and_session.html) and [the docs](https://suave.io/sessions.html) as help where statefulForSession is also used to authenticate/authorize a user (in the tutorial).
I put statefulForSession at the place it is explicitely needed, but this still makes most paths session-aware, so I can authenticate the users with their cookies similar to the tutorial.
I can replace that in a different way though, so that only a few paths need to be session-aware instead of most of them.
