### ISSUE TITLE
Assembly.Location usage causes "The path is not of a legal form." failures when library is loaded dynamically

### ISSUE THREAD

**Issue by Zagrophyte** [SuaveIO/suave#664]
Assembly.Location can be empty "" when the assembly was not loaded from a path:
[https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx)

>The location of the loaded file that contains the manifest. If the loaded file was shadow-copied, the location is that of the file after being shadow-copied. If the assembly is loaded from a byte array, such as when using the Load(Byte[]) method overload, the value returned is an empty string ("").

The issue seems to occur when Suave is bundled as a resource and loaded dynamically, such as with a tool like Fody.Costura. 

When bundled with Fody.Costura, an exception is thrown from the `startWebServer` method:
```
System.ArgumentException occurred
Message: Exception thrown: 'System.ArgumentException' in mscorlib.dll
Additional information: The path is not of a legal form.
```

When Fody.Costura bundling is disabled, Suave starts properly again.
This issue seems to occur regardless of the value of HomeDirectory in the config.

### Relevant Source:
https://github.com/SuaveIO/suave/blob/39bfec142a1850ad03334764a698df8cea9ad34e/src/Suave/ParsingAndControl.fs#L173
https://github.com/SuaveIO/suave/blob/39bfec142a1850ad03334764a698df8cea9ad34e/src/Suave/ParsingAndControl.fs#L175

----
Other usages that may be problematic but are unrelated to this issue:
https://github.com/SuaveIO/suave/blob/29be7c3d0e6014e6c10f7236c3c5e0956b99f9ec/src/Suave/Combinators.fs#L644
https://github.com/SuaveIO/suave/blob/b8d098f0142db23806d44a7e5555606ccaaa89dd/src/Suave.Xsp/Library.fs#L134

**Comment by ademar** [comment]
fixed in #735
