### ISSUE TITLE
Having trouble with the build

### ISSUE THREAD

**Issue by lambdakris** [SuaveIO/suave#667]
I am having some trouble with the build

**First, here is my enviroment:**
Windows 10
.NET Core 2.0
.NET Framework 4.7.1
Ruby 2.4.2
RubyDevKit
\* I have not installed Libuv, but it seems like that is only to run some sort of integration tests...?

**Now, the issue I'm having:**
In the root of the repository I ran `bundle` then `bundle exec rake`, at which point I see the following:
```
C:\Users\lambdakris\Code\Hobby\suave\src\Suave\Owin.fshttps://github.com/Microsoft/visualfsharp/pull/3729(406,22): error FS0001: This expression was expected to have type↔    'Tuple<'a,'b,'c>'    ↔but here has type↔    ''d * 'e * 'f' [C:\Users\lambdakris\Code\Hobby\suave\src\Suave\Suave.fsproj]
```

Might this be something that I'm doing wrong, or based on the fact that the error is regarding mismatch between types of tuples, might this be related to https://github.com/Microsoft/visualfsharp/pull/3729...?

**Comment by ademar** [comment]
Give a try to the new build script; we got rid of the rake script sometime now.
