### ISSUE TITLE
template for `dotnet new suave`

### ISSUE THREAD

**Issue by enricosada** [SuaveIO/suave#669]
It's missing a template for the .NET template engine, so users with .NET Core Sdk can just

install/update the template: `dotnet new -i "Suave.Template::*"`

and create apps with

```
dotnet new suave
```

template should be added to the official [list of avaiable templates for dotnet-new](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new)

**Comment by enricosada** [comment]
if noone volounteer, i'll do it

**Comment by JacobChang** [comment]
I just write a simple one [here](https://github.com/JacobChang/Suave.Template)

**Comment by haf** [comment]
+1 a template would be awesome.

**Comment by JacobChang** [comment]
Do we need to get it into .net core repo? Or we just create a repo under SuaveIO and published to nuget?

**Comment by haf** [comment]
Sure; transfer it and I'll give you commit access. Will you do the publish as well?

**Comment by theimowski** [comment]
One does need to explicitly register a template in dotnet. NuGet indexes the packages and registers itself the template by its identifier ([example](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/.template.config/template.json#L10-L11))

**Comment by JacobChang** [comment]
@haf Ok, I need commit access or you can just fork my repo, I will start contribute to the new repo
