### ISSUE TITLE
Travis CI builds failing on master with Suave.Experimental.dll.mdb does not exist

### ISSUE THREAD

**Issue by ctaggart** [SuaveIO/suave#680]
You can see that the builds are failing on the master branch:
https://github.com/SuaveIO/suave/commits/master

The error on Travis CI looks like:
```
-> The file "bin/Release/Suave.Experimental.dll.mdb" requested in /home/travis/build/SuaveIO/suave/src/Experimental/paket.template does not exist.
```

**Comment by ademar** [comment]
A new release of albacore should clear this issue cc @haf

**Comment by haf** [comment]
Ok

**Comment by haf** [comment]
v3.0.1 released
