### ISSUE TITLE
File upload fails, using several hundred MBs of RAM on Suave hosted WebSharper project

### ISSUE THREAD

**Issue by reneederer** [SuaveIO/suave#683]
When uploading a file, the process memory usage quickly rises from ~100MB to over 1000 MB (and keeps rising). The server side function is never reached. This happens with a small file, with an empty text file, and even when no file is chosen.
While hosting my WebSharper project on Owin, uploading files worked.

You can recreate the bug by creating a new Visual Studio project with the template "WebSharper 4 Suave-hosted Site". Then replace the Main() function in Client.fs with
```fsharp
    let Main () =
        div
          [ formAttr
              [ attr.method "post"
                attr.action "/about"
                attr.enctype "multipart/form-data"
              ]
              [ inputAttr
                  [ attr.``type`` "file"
                    attr.name "myFile"
                  ]
                  []
                buttonAttr
                  [ attr.``type`` "submit" ]
                  [ text "Upload" ]
              ]
          ]
```

**Comment by haf** [comment]
What version? We upload ~5 MiB files around the clock without rebooting the server for months.

**Comment by reneederer** [comment]
Suave Version:               2.2.1
WebSharper Version:    4.0.195.127
Target Framework:        .NET Framework 4.6.1
Target F# runtime:        F# 4.1 (FSharp.Core, 4.4.1.0)

**Comment by stevehv** [comment]
I am experiencing the same problem with Suave 2.2.1. Is there any information on a fix or workaround?

**Comment by ademar** [comment]
Note that 100 mb is the default max upload size.

https://github.com/SuaveIO/suave/blob/master/src/Suave/Web.fs#L94

You need to increase this value in the configuration record to handle
larger files.

**Comment by ademar** [comment]
Sorry I just realized this issue is probably a bug in the owin
implementation.
