### ISSUE TITLE
Get rid of YOLO and Logary in paket.dependecies

### ISSUE THREAD

**Issue by ademar** [SuaveIO/suave#699]
This practice of including pieces of code from other repositories smell.

https://github.com/SuaveIO/suave/blob/master/paket.dependencies#L16-L17

**Comment by haf** [comment]
https://github.com/haf/expecto/commit/571239140624c7fc727da63d5de7bbd6b2d9b915 — can do the same here. No need for an API change. Suave is Apache 2.0 full out.
