### ISSUE TITLE
Issuw with suave 2.4.1

### ISSUE THREAD

**Issue by mrkaspa** [SuaveIO/suave#700]
I upgraded the dependency from 2.3.1+beta to 2.4.1 and got this error:

My fsproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Db.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Suave.DotLiquid" Version="2.4.1" />
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Npgsql" Version="3.2.5" />
    <PackageReference Include="Suave" Version="2.4.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.4.0" />
  </ItemGroup>
</Project>
```

/usr/local/share/dotnet/sdk/2.1.4/Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "FSharp.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/mrkaspa/code/fs/FLearn/web/web.fsproj]

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by haf** [comment]
Could you https://github.com/SuaveIO/Suave.Template/ please?
