### ISSUE TITLE
License link from suave.io site is broken

### ISSUE THREAD

**Issue by rmunn** [SuaveIO/suave#703]
The https://suave.io/ site has a license link that points to https://github.com/SuaveIO/suave/blob/master/COPYING, but that file was renamed in https://github.com/SuaveIO/suave/commit/82d365135ec2551ba93495ad121b7e991eb76b7b to be called LICENSE instead of COPYING. The site needs to be updated to have the link point to the correct license location again: https://github.com/SuaveIO/suave/blob/master/LICENSE rather than https://github.com/SuaveIO/suave/blob/master/COPYING.

(I couldn't find the repo for the site, or I would be reporting this issue there, since it's not an issue with the Suave library itself.)

**Comment by ademar** [comment]
Hi, 

Thanks I have already updated the link in 90f83eacf65b0acaa7d5026fb1dc0667663688a6.

Just needs to be pushed to the site. cc @haf

**Comment by ademar** [comment]
Actually I have just pushed a copy of the licence in COPYING as there might be links all around the net still pointing to it.

**Comment by haf** [comment]
Ah, will do @ademar
