### ISSUE TITLE
Websockets don't work in firefox

### ISSUE THREAD

**Issue by Zeroto** [SuaveIO/suave#706]
## Description
It seems that firefox includes `keep-alive` in the `connection` header causing Suave to send back a bad request during the websocket handshake

## Current behaviour:
Suave sends back a 400 bad request because it requires the connection header to be just `Upgrade`

## Desired behaviour:
Suave ignores the other values in the `connection` header and processes the connection upgrade

## Workaround
manually strip the other values from the connection header before sending the request to the handshake.

**Comment by ademar** [comment]
Hi @Zeroto I've pushed a new pre-release v2.5.0-beta2 with a fix. Please give it a try. Thanks.

**Comment by Zeroto** [comment]
Works ok now. Thanks 😄
