### ISSUE TITLE
Public API breakage in v2.5-beta2

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#707]
https://github.com/SuaveIO/suave/commit/8058c992555df36593fb4ea6e499875ea8789529

Specifically line https://github.com/SuaveIO/suave/commit/8058c992555df36593fb4ea6e499875ea8789529#diff-092c8e8d86dd3abf516fd70504469b75R209

@ademar If you perf-optimise, 1) make sure this causes an issue by profiling it and start a discussion, 2) see if we can re-use async instances, 3) log less, 4) see if we can filter more on levels, so that instances aren't even created, 5) bump the major version if you want to make this change and talk to me specifically about this interface.

Please don't change the logging interface without a major version bump either; it causes all kinds of breakage amongst downstream consumers.

**Comment by ademar** [comment]
I bumped the minor; I though that will be enough to break the API.

Henrik I am sorry to say I am not interested in discussing any further with you about the direction or architecture of the project. 

As of now I am removing your commit access.  You are free to maintain your own fork of Suave elsewhere with whatever interfaces you want and follow whatever procedures you feel comfortable with. 

Peace.

**Comment by haf** [comment]
No, public API changes are correlated with bumping the major version, not the minor version.

After what you wrote in the other thread about your supposed control of Suave, I haven't been planning on contributing anything more to this project anyway, but as long as I'm a user I want API stability according to semver.
