### ISSUE TITLE
Suave.ScanResult.Error shadows Result.Error from FSharp.Core

### ISSUE THREAD

**Issue by jbrestan** [SuaveIO/suave#715]
`Suave.ScanResult` type (in ConnectionFacade.fs) defines an `Error` constructor, which shadows the built-in `Result.Error` whenever you `open Suave`. This makes it harder to update existing codebases to Suave 2.5.x (introduces compilation errors) and since `ScanResult` is in the same namespace as most of the app composition and other "global" types and functions, it's hard to avoid.

Would it make sense to make the `ScanResult` type internal, or maybe rename its `Error` constructor?

**Comment by ademar** [comment]
@jbrestan I've pushed a new release with this fix; please give it a try. Cheers.

**Comment by jbrestan** [comment]
@ademar 2.5.2 works perfectly, thank you!
