### ISSUE TITLE
Change Collections.fs functions to use the Result type instead of the Choice type

### ISSUE THREAD

**Issue by dam5s** [SuaveIO/suave#718]
I was wondering why the Choice type is used in this file:
https://github.com/SuaveIO/suave/blob/master/src/Suave/Utils/Collections.fs

I was trying to use the HttpRequest.header function and was having a hard time going up the chain to find out what was actually returned. In the end I found the Collections functions.

Is there a particular reason for the usage of the Choice type instead of the Result type for these functions? It would be a lot easier to understand the API if it was returning a Result instead.

If there is a specific reason why Result is not good enough in that case, I would really like to know. Feel free to close the issue if that's the case too.

Thanks!

**Comment by ademar** [comment]
Because the type  `Result` did not existed when the API was designed; it
was introduced with F# 4.1

Nevertheless in the upcomming v3 we will be dropping `Choice` in favour of
`Result` and will be introducing many performance enhacements with the help
of `Span<'T>` and friends.

**Comment by dam5s** [comment]
Oh great, thanks for the quick feedback!
