### ISSUE TITLE
Use `100 Continue` where apropiate

### ISSUE THREAD

**Issue by ademar** [SuaveIO/suave#72]
check out http://jazzy.id.au/default/2013/07/16/100_continue_support_in_play.html

What this issue means is that you can specify a 2-n stage response, where the first stage checks whether the headers are within bounds of what the server is capable of handling, and the 2..n other stages is the receiving of the actual request.

If the web server can handle the request, 100 Continue should be sent.

[Read the specification before implementing.](http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3)

**Comment by haf** [comment]
@ademar What level of confidence do you have with this change? I couldn't find a unit test/integration test for it?

How come you've changed the .fs file to be executable? 
![screen shot 2015-06-10 at 15 46 37](https://cloud.githubusercontent.com/assets/193115/8083863/ec9b1cec-0f87-11e5-834b-ac32d44263eb.png)

**Comment by ademar** [comment]
I'm confident it works. I've tried for a while to write a test but there is too much smartness coded inside HttpClient and couldn't get it to do what I wanted. I'll give it another shot once I have the time.

> How come you've changed the .fs file to be executable? 

I did not noticed, probably while simultaneously working on the same directory from Windows and Mac.

**Comment by haf** [comment]
How about we release v0.29 then? =)

**Comment by ademar** [comment]
Sure, I'll release it later tonite if you haven't done it first.

**Comment by ademar** [comment]
Done.

On Wed, Jun 10, 2015 at 12:49 PM, Ademar Gonzalez <ademar.gonzalez@gmail.com
> wrote:

> Sure, I'll release it later tonite if you haven't done it first.
>
> On Jun 10, 2015, at 11:59 AM, Henrik Feldt <notifications@github.com>
> wrote:
>
> How about we release v0.29 then? =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuaveIO/suave/issues/72#issuecomment-110810979>.
>
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar
