### ISSUE TITLE
How restart in server crash?

### ISSUE THREAD

**Issue by mamcx** [SuaveIO/suave#720]
I embed suave for my mobile app. It sometimes crash. I need to restart (and log why it crash!):

```f#
let startServer(rootPath) =
    let cf = serverConfig rootPath
    printfn "%A" cf
    startWebServerAsync cf app
    |> snd
    |> Async.StartAsTask 

let t = startServer(basePath)

type App() =
    inherit Application()

    let mutable task:System.Threading.Tasks.Task = null

    do
        task <- startServer(basePath) //I hold on the task so it not get GC

        base.MainPage <- form
```

P.D. Asked too in https://stackoverflow.com/questions/53838297/how-restart-an-async-suave-server-if-it-crash

**Comment by ademar** [comment]
What mobile platform are you running Suave on ? I would try to catch the exception with a UnhandledException.

**Comment by mamcx** [comment]
I'm on Xamarin in both iOS/Android

**Comment by mamcx** [comment]
Using the Nuget package.

**Comment by ademar** [comment]
Cool, did not know you could that.

To capture the exception I would try something like this.

```fsharp 
open System
open Suave

let app = Successful.OK "Hello world"

let startServer _ = 
  let a,b = startWebServerAsync defaultConfig app
  Async.Start b

let onUnhandledException (sender:obj) (e:UnhandledExceptionEventArgs) = 
  // TODO: make sure server is really dead before starting again
  startServer ()

[<EntryPoint>]
let main argv =
    AppDomain.CurrentDomain.UnhandledException.AddHandler (new UnhandledExceptionEventHandler(onUnhandledException))

    startServer ()
    0 // return an integer exit code
```

Not sure why you use a task in your example above.

In principle Suave should not crash, if you manage to capture the exception we would be very interested in having a look.

**Comment by mamcx** [comment]
Ok, I use tasks for other reasons. 

But how check this?

> // TODO: make sure server is really dead before starting again
