### ISSUE TITLE
I've created a library to be able to write code in the style of Suave

### ISSUE THREAD

**Issue by wallymathieu** [SuaveIO/suave#722]
https://github.com/wallymathieu/FSharpPlus.AspNetCore#getting-started

Since it uses the IAppliactionBuilder there doesn't need to be that much implementation code.

What are your thoughts?

**Comment by ademar** [comment]
Cool, but isn't this basically what Giraffe does ?

**Comment by wallymathieu** [comment]
Giraffe focuses more on performance so uses `Task<_>` and CPS instead of `Async<_>`. I feel that using `Async<_>`  is more composable (slightly nicer to work with). It could also be that I need to figure out the monad transformers for Giraffe.

**Comment by wallymathieu** [comment]
From a personal perspective I would start out with something Suavish and then go Giraffe if I need to optimize performance further.

**Comment by ademar** [comment]
I see. I agree that `Async<_>` is easier to work with.

**Comment by wallymathieu** [comment]
From talking with @cannorin, it feels like @cannorin has put a lot of thought into scanf, so perhaps could rewrite the scanf implementation in Suave?

**Comment by cannorin** [comment]
My scanf ( https://github.com/cannorin/FSharp.CommandLine/blob/master/src/FSharp.Scanf/scanf.fs ) works faster 10x faster than that of Suave but

1. it introduces additional dependency (FParsec)
2. the optimisation only works with up to 7-tuples, and for 8-tuples and more you have to fall back to reflections which is about 7x slower
