### ISSUE TITLE
Question: stream PUT body to a file?

### ISSUE THREAD

**Issue by njlr** [SuaveIO/suave#725]
In the Node.js world I can stream a PUT request into a file, and avoid having the entire request in memory at one time. 

Is this possible in Suave? I was unable to find documentation about it.

**Comment by ademar** [comment]
Sorry, this is not possible at the moment :(

**Comment by njlr** [comment]
That is a shame! I love the Suave design :cry: 

Would you be able to suggest another F# framework that supports this?

**Comment by ademar** [comment]
I do not know of any that supports this feature. I do plan to implement it for Suave's next version.

**Comment by njlr** [comment]
Good to know! I will follow the developments.
