### ISSUE TITLE
Music Store demo, page 370, can't compile with F# 4.6.2

### ISSUE THREAD

**Issue by BentTranberg** [SuaveIO/suave#727]
I have been working my way through the Music Store demo for two days, and now I got stuck on this weird compiler error when pasting in the source on page 370, chapter **Session type**, from **suave-music-store-en.pdf**

The error is `FS0193 The module/namespace 'Control' from compilation unit 'FSharp.Core' did not contain the val 'ValLinkagePartialKey(OnSuccess)'`

The issue is not spesifically related to Suave, and has been reported here:
https://github.com/Microsoft/visualfsharp/issues/6450

In the issue description, I believe you will find guidance on how this can be resolved in regards to Suave. I am not an expert in these matters, so I could be wrong, but please have a look at it. Anyway I hope to somehow be able to use Suave with the latest FSharp.Core available.

[MusicStore.zip](https://github.com/SuaveIO/suave/files/3065391/MusicStore.zip)

In MusicStore.zip you will find my demo that fails to compile in VS 2019. It does not depend on a database, and it's just compile and run if it compiles. It can be compiled and run if FSharp.Core 4.5.2 is brought in from NuGet, but will otherwise fail with the error mentioned above.

**Comment by enricosada** [comment]
fixing that, i'll send a PR soon

**Comment by enricosada** [comment]
fixed in PR https://github.com/SuaveIO/suave/pull/728

**Comment by ademar** [comment]
@BentTranberg I've pushed a new nuget 2.5.4 containing this fix. Please give it a try and let us know if this does not solve the problem.
