### ISSUE TITLE
Performance issue after .netcore upgrade

### ISSUE THREAD

**Issue by nutshellit** [SuaveIO/suave#729]
Hi,
I have noticed a delay on requests to my suave api that I can't explain after upgrading my api from .net 4.71 to .net core 2.2. In my integration test it takes over a second for the request to arrive from client request to handler (using SuaveTesting) where previously it took milliseconds. 
I suspect that the delay may be the routing lookup (I have about 650 paths) but hopefully someone has encountered a similar issue or can advise me on a way to improve the request performance.

**Comment by ademar** [comment]
The default routing does not scale too many paths. We need to implement a new kind of routing based on [Radix trees](https://en.wikipedia.org/wiki/Radix_tree)
