### ISSUE TITLE
Use HttpListener or HttpApi to share ports

### ISSUE THREAD

**Issue by thinkbeforecoding** [SuaveIO/suave#73]
Windows has HttpApi (used internally by the HttpListener) to enable several applications to use the same port, and dispatch by resource path. It especially enables application to listen on port 80 even when IIS is running.

The HttpListener is also implemented on mono, as far as I know.

Maybe it could be possible to choose between current implementation based on sockets and an implementation based on the HttpListener (that also support SSL in 64bits which would resolve issue #42)

**Comment by haf** [comment]
Closing for lack of action. We can re-open if we decide this is something we want to do.
