### ISSUE TITLE
There must be some issue with site.

### ISSUE THREAD

**Issue by kunjee17** [SuaveIO/suave#730]
I guess there is some issue with [site](https://suave.io/) . Just a heads up.

**Comment by MiyamotoAkira** [comment]
For some pages (not all), I get 
```HTTP Error 502.3 - Bad Gateway
A connection with the server could not be established```

Some pages where it happens: binding.html, api.html, paket.html ...

**Comment by kunjee17** [comment]
We are pointing to home site from https://github.com/kunjee17/awesome-fable and build starts failing so I thought of reporting.

**Comment by ademar** [comment]
Hi, sorry for the inconvenience, the site is back online now. The vm had restarted while I was asleep :)

**Comment by ademar** [comment]
@kunjee17 thanks for the heads up!
