### ISSUE TITLE
Getting Started Suave on Heroku

### ISSUE THREAD

**Issue by dyoshikawa** [SuaveIO/suave#737]
Hello.

[The existing heroku tutorial](https://github.com/SuaveIO/suave/blob/master/docs/heroku.md) looks old.

I suggest the following method.

- [Heroku with Docker](https://www.heroku.com/deploy-with-docker)
- ["PublishSingleFile"  in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#compiledeploy)

I made the sample.

https://github.com/dyoshikawa/heroku-suave-getting-started

This is a way for developers to develop on Heroku in a simple, easy and modern environment.

I want to add this to the documentation.
I will contribute if you feel good.

**Comment by ademar** [comment]
Hi @dyoshikawa, your contribution would be welcome 👍

**Comment by dyoshikawa** [comment]
@ademar Thanks for reading.
I will prepare immediately.
