### ISSUE TITLE
Is there a Suave.io Elmish example?

### ISSUE THREAD

**Issue by olawdy** [SuaveIO/suave#739]
Hi!

My company is interested in adopting Suave for a custom web server backend, but I'm not sure if there is a Suave.io implementation for Elmish. Currently we have a sample web app up and running based on this example here -

https://github.com/The-Dev-Owl/dev-owl-todo-application

However, we would rather use a Suave.io backend instead of the Node backend that the current example comes with.

Please advise :)

**Comment by ademar** [comment]
Hi @olawdy 

I have not used it myself but this may be what you are looking for.

https://github.com/Nhowka/Elmish.Bridge
