### ISSUE TITLE
Customize HTTP Server Header Value

### ISSUE THREAD

**Issue by enkomio** [SuaveIO/suave#755]
I need to customize my server response, and in particular the server name. I see that the HTTP _Server_ header value is set to a read only string and it is not possible to change it.  Is this due to a specific reason? 

What about removing the _server_ header name from https://github.com/SuaveIO/suave/blob/master/src/Suave/HttpOutput.fs#L137?

**Comment by ademar** [comment]
You can disable the server header in the configuration record.

https://github.com/SuaveIO/suave/blob/master/src/Suave/Web.fs#L92

**Comment by enkomio** [comment]
Yeah I know, but in my project I need to send as `Server` header a different string. For example, instead of sending the header:

`Server: Suave (https://suave.io)`

I'd like to send:

`Server: My custom value`

If I set `hideHeader  = true` and use `addHeader "Server" "My custom value"`, the `Server` header is not set due to the `exclusions` list pointed in my previous comment. So, I was wondering if the `server` string can be removed from the `exclusions` list in the `writeResponse` function or provide a mechanism to customize this list.

**Comment by ademar** [comment]
Ok, I've pushed a fix that allows you to set a custom Server header; you still need to set `hideHeader = true` otherwise Suave will output the default Server string.

I'll release a new nuget later today or tomorrow.

**Comment by enkomio** [comment]
Awesome, thanks!
