### ISSUE TITLE
Removing keys from session state

### ISSUE THREAD

**Issue by Rich-F-G-Mills** [SuaveIO/suave#757]
The Suave documentation on [sessions](https://suave.io/sessions.html) shows an example of how a key can be added/fetched from the session state (via `StateStore`)

The current implementation of `StateStore` provides methods for `get` and `set`.

**Would there be any appetite to extend this for an `unset` method?**

This is related to a [question ](https://stackoverflow.com/questions/69828962/removing-key-from-session-state) I asked on StackOverflow where another user has provided a work around.

**Comment by ademar** [comment]
@Rich-F-G-Mills Definitely `unset` would be a welcome addition. I find myself often setting key values to an empty string as a workaround.

**Comment by Rich-F-G-Mills** [comment]
@ademar Thank you for confirming... My initial concern was that I was just missing the point!

**Comment by Rich-F-G-Mills** [comment]
I have made a proposed code change (heavily inspired by the response to my SO question).

It can be found: [https://github.com/Rich-F-G-Mills/suave/commit/34834ddc298aa9c3288a7607c3e46bdc46471b9d](https://github.com/Rich-F-G-Mills/suave/commit/34834ddc298aa9c3288a7607c3e46bdc46471b9d)

**Comment by ademar** [comment]
It looks good, the only change I would ask is to pass the cookie lifetime as a parameter to `remove` the same way `set` does when it calls `write`; otherwise calling `unset` may change the lifetime of the session cookie.

Then send a pull request over.

**Comment by Rich-F-G-Mills** [comment]
@ademar Thank you for looking it over.

This has now been done and a PR created. Note that I have also added another `try` block to capture any exception raised when re-serialising the new `map`.
