### ISSUE TITLE
Support Microsoft Dependency Injection

### ISSUE THREAD

**Issue by jkone27** [SuaveIO/suave#762]
I know in suave we strive to use partial application, but in many cases and e.g. when using external libraries for aspnet, it's quite common to have to register components in DI, and this "shuts off" suave from all this interoperability.

https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection

I love using suave, i know giraffe is a suave-like "clone" for aspnetcore running on kestrel, but suave can run in interactive scripts.
being able to run suave under a standard host with DI capabilities could be useful>?
https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host

this would make it easier to plug "existing  code" into suave maybe?

or maybe all of this is already possible and i just need to figure how to plug all together? :)

**Comment by ademar** [comment]
Sorry, supporting this is out of the scope of our project.
