### ISSUE TITLE
Add more default mime types

### ISSUE THREAD

**Issue by nojaf** [SuaveIO/suave#764]
Hello,

Comparing the default mime types of Suave 

https://github.com/SuaveIO/suave/blob/57d69e39e67a5b1a1c60b7c015c698a1901a9420/src/Suave/Combinators.fs#L90-L114

to the list of ASP.NET Core

https://github.com/dotnet/aspnetcore/blob/86e28e7b267579e2999e06b63eeef27e4836384a/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs#L24-L404

There is quite the delta. Would you be open to having the same list?

**Comment by ademar** [comment]
We rather have a minimal number of preconfigured mime types. It is a security feature.
