### ISSUE TITLE
Log files format

### ISSUE THREAD

**Issue by ademar** [SuaveIO/suave#78]
Implement W3C Extended and/or NCSA Common web log formats

Current log format:

```
D 2014-05-05T10:55:22.2935776+00:00: ("GET", 192.168.47.168, "/healthcheck", seq [], seq [],
 seq
   [[user-agent, curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8y zlib/1.2.5];
    [host, 192.168.47.164:8083]; [accept, */*]])
 [suave/web-requests]
```

In order to solve this issue we need to log first when a request is started and then when the request ends, from within suave, since we can't wrap web parts around the applicatives.

**Comment by haf** [comment]
Isn't this fairly well done, with what information is available in a WebPart? I think we should discuss how something abstract like this is handled 'cross cutting' to the web parts. Do you see how I mean?

**Comment by ademar** [comment]
Logging has improved a log since then, closing.
