### ISSUE TITLE
Documentation web pages down

### ISSUE THREAD

**Issue by rynoV** [SuaveIO/suave#785]
I get HTTP Error 502.3 - Bad Gateway for any of the pages from `docs`

![image](https://github.com/SuaveIO/suave/assets/35615725/0a07ac37-da50-4711-bd83-113bfa101f5b)

**Comment by toraritte** [comment]
I get the same for almost every page on suave.io, but they seem to be loading after a while. For example, I try one page, reload it several times, get the same error page, then when I try to load it on my phone, it works and later it works on my computer as well.

The instructions to build the docs locally still work however, and the generated HTML looks good despite lacking some of the formatting of the main site:

```
git clone https://github.com/SuaveIO/suave
cd suave/docs
# you may need to delete `Gemfile.lock` if your local Ruby version differs.
bundle install
bundle exec jekyll build
```
