### ISSUE TITLE
[question] Is "Suave.ViewEngine" ready?

### ISSUE THREAD

**Issue by toraritte** [SuaveIO/suave#786]
Just curious, because I haven't seen anything about the docs, and the only mention I could find (so far) is in #527 "Documentation overhaul for v2". I didn't have time to try it out, so I presume that it is usable, but undocumented.

For context: I started learning Suave, but didn't like `DotLiquid`, so I continued with Giraffe after learning that its `Giraffe.ViewEngine` is a more functional templating engine - when I unexpectedly saw [the attribution linking back to Suave](https://github.com/giraffe-fsharp/Giraffe.ViewEngine?tab=readme-ov-file#attribution-to-original-authors):)

**Comment by ademar** [comment]
Thats cool they attributed us. Unfortunately the suave view engine never materialized.

I personally use the razor engine via `Suave.Razor`

**Comment by toraritte** [comment]
Thanks! I totally missed `Suave.Razor` as well.
