### ISSUE TITLE
[web] Read suave configuration from file

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#83]
As a user of puppet,
When deploying a service,
I need to configure location of temporary writes, for writeability and security,
And that configuration needs either to be command-line based or configuration file based.

**Comment by MatthiasHarvey** [comment]
I'll try implement this. I'll use JSON + FsPickler unless there are any other suggestions.

**Comment by haf** [comment]
Actually, from reading FsPickler's docs, its JSON format is mostly geared towards being isomorphic to the CLR constructs - and being able to represent all sorts of types, cyclic dependencies etc. I suggest you instead to explore one of these paths:

 - using paket to source-reference the Json files of this folder https://github.com/fsharp/FSharp.Data/tree/master/src/Json - no dependencies, compiled into solution, versioning
 - using Newtonsoft.Json in a separate .Config assembly
 - using Newtonsoft.Json in the same assembly and il-merging/il-packing it with https://github.com/gluck/il-repack or ilmerge http://www.microsoft.com/en-us/download/details.aspx?id=17630 (I've had some problems getting both of [those](https://github.com/gluck/il-repack/issues/68) [to run](https://github.com/gluck/il-repack/issues/66) [on mono](https://github.com/logary/logary/pull/50).

Here's [some background discussion on serialisation with json](https://github.com/SuaveIO/suave/issues/89#issuecomment-40884979). I've investigated the JSON stuff in the BLC, but [it has its own problems](https://twitter.com/henrikfeldt/status/539405194485039104), plus and as for Fleece, it has unwanted dependencies.

So that's some of the research I've done the last year about JSON on .Net... I would like to hear your opinion on what path to take from here, but I don't think FsPickler is right for human-readable JSON.

**Comment by haf** [comment]
All that said; I have one reservation to it. Since we already depend on FsPickler, iff FsPickler can read and generate human-readable JSON, that's probably a good way forward - and a better one than my own alternatives.

**Comment by ademar** [comment]
Or `DataContractJsonSerializer` in `System.Runtime.Serialization.Json` ...

**Comment by ademar** [comment]
FsPickler will be most probably the right aproach here so lets use that.

**Comment by haf** [comment]
As I wrote in the tweet linked, I really don't think System.Runtime.Serialization.Json is the right alternative.

**Comment by ademar** [comment]
We have agreed on FsPickler since we already depend on it. I don't see how the tweet is relevant thought.

**Comment by MatthiasHarvey** [comment]
What should I do about the types that don't have a simple plain text representation? I'm getting NonSerializableTypeException for the CancellationToken

**Comment by haf** [comment]
The aim isn't to generate config for *all* things in the suave config, only the things that are relevant to configure from the outside, like server_key and the bindings and timeouts.

**Comment by varon** [comment]
It seems like we should probably shard the configuration type into two:

The first one should hold the fields you suggest, and should possibly be parsed from a file (with this feature)

It seems as though the name `SuaveConfig` is okay for the thing that's passed into the web server, but what on earth do we call the external configuration elements?

**Comment by haf** [comment]
It's a bit weak to orient the user-facing API after what infrastructure we have to serialise parse it, but it could be done... I would like to see an example though.

**Comment by varon** [comment]
I think probably what we want to do is separate the data from the behaviour. A bit similar to how they do it in the non-functional languages.

I don't really think it's an API failure to design it this way.

I'd propose the following change:

    type ServerProperties =  {
        bindings                : HttpBinding list
        server_key 				: byte []
        listen_timeout          : TimeSpan
        bufferSize              : uint
        max_ops                 : uint
        mime_types_map          : (string * Mimetype option) map
        home_folder             : string option
        compressed_files_folder : string option }

This can get put into the `SuaveConfig` which might look like this:

	type SuaveConfig = { 
		properties 				: ServerProperties
	    error_handler           : ErrorHandler
	    ct                      : CancellationToken
	    logger                  : Logger }

**Comment by haf** [comment]
+1 then

**Comment by MatthiasHarvey** [comment]
FsPickler.Json depends on [Newtonsoft.Json](http://james.newtonking.com/json). Is it ok to add this?

**Comment by haf** [comment]
Like I said, if you're adding that you need to ILMerge it or make it an external lib, imo.

**Comment by ademar** [comment]
Lets rewind a moment here, before complicating things @haf can you tell me what is wrong with using the BCL serializer ? I'm sure it very well can deal with this record + no dependencies.

**Comment by haf** [comment]
After further consideration, in this particular use-case it's probably fine; because the types to be serialised are already well known.

Emotions come to mind when thinking of the bad encounters I've had with that serialiser, that's all ;)

**Comment by MatthiasHarvey** [comment]
Ok cool. I'll try that.

**Comment by haf** [comment]
Half-finished by https://github.com/SuaveIO/suave/pull/187
