### ISSUE TITLE
[http] Combinator for CORS and correspondingly for CSRFs

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#95]
On chat, this example was given:

``` fsharp
let cors statusCode reason content = 
    set_header "Access-Control-Allow-Origin" "*"
    >> set_header "Access-Control-Allow-Methods" "GET, PUT, DELETE" 
    >> response statusCode reason (bytes_utf8 content)
    >> succeed
```

We'd also need to support CSRF-tokens, or we're [undermining the security model](http://halls-of-valhalla.org/beta/articles/cross-site-request-forgery-demystified,47/).

The most common way of doing it is to have a unique value per request that only the server knows about present in the post-back data from a web form. If the data in the hidden field verifies when the server receives the POST request, it's let through, otherwise denied.

hawk/oz HMAC/authentication solves it for API type web servers.

For non-API web servers, using HTTPS, we could normalise the output data, sign the digest of the bytes with the private key and send the signature as a private field. The same thing is done when the request is received: normalise the data, digest it, verify signature. (Digest != shasum, see Length Extension link below)

Take care not to fall prey to [Length-Extension attacks](https://en.wikipedia.org/wiki/Length_extension_attack), so HMAC-SHA1/256 should probably be used for digests.

**Comment by CumpsD** [comment]
Let's link this in just so they are linked: https://github.com/SuaveIO/suave/pull/283

**Comment by haf** [comment]
A merge is needed in https://github.com/SuaveIO/suave/pull/283 then it's all done! :)
