### ISSUE TITLE
"We need to talk" - about persistent data structures

### ISSUE THREAD

**Issue by haf** [SuaveIO/suave#97]
I think we should use persistent data structures and take the performance hit.

If we then decide they are not worth it, we can add a compile-time constant that replaces the calls returning value with calls mutating values and returning the same.

**Comment by panesofglass** [comment]
Glad you went full `Async`. Any thoughts on transitioning to the `AsyncState` approach we have in Freya, e.g. `HttpContext -> Async<'T * HttpContext>`?

**Comment by panesofglass** [comment]
I found this thread from @haf's post on a Freya item. If there's a better place to have the discussion, e.g. gitter or a new issue, please let me know.
